---
audit:
  active: true
  storage:
    filter:
      methods:
        include: ['all']
        exclude: []

  syslog:
    options:
      host: localhost #The host running syslogd, defaults to localhost.
      #port: 514 #The port on the host that syslog is running on, defaults to syslogd's default port.
      protocol: unix #The network protocol to log over (e.g. tcp4, udp4, tls4, unix, unix-connect, etc).
      #protocolOptions:  #Socket connect options. See https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener for available options.
      #path: /dev/log #The path to the syslog dgram socket (i.e. /dev/log or /var/run/syslog for OS X). !! set by audit/config/default-syslog-path.js 
      #pid: #PID of the process that log messages are coming from (Default process.pid).
      #facility: local0 #Syslog facility to use (Default: local0).
      localhost: '' #Host to indicate that log messages are coming from (Default: localhost).
      #type: BSD #The type of the syslog protocol to use (Default: BSD, also valid: 5424).
      app_name: pryv-audit #The name of the application (Default: process.title).
      #eol:  #The end of line character to be added to the end of the message (Default: Message without modifications).

    formats: # define your own template for each type of "log/<format>" event
      default:
        template: "{userid} {type} createdBy:{createdBy} {streamIds} {content}"
        level: notice # One of notice, warning, error, critical, alert, emerg
    filter:
      methods:
        include: ['all']
        exclude: []
