// @flow

// THIS FILE IS AUTOGENERATED FROM test/fixtures/base.proto
// PLEASE DONT EDIT MANUALLY

const Corpus = {
  UNIVERSAL: 0,
  WEB: 1,
  IMAGES: 2,
  LOCAL: 3,
  NEWS: 4,
  PRODUCTS: 5,
  VIDEO: 6,
};
export interface ISearchRequest {
  query: string; // id = 1
  pageNumber: number; // id = 2
  resultPerPage: number; // id = 3
  corpus: 0 | 1 | 2 | 3 | 4 | 5 | 6; // id = 4
}
export interface ISearchResponse {
  results: Array<IResult>; // id = 1
}
export interface IResult {
  url: string; // id = 1
  title: string; // id = 2
  snippets: Array<string>; // id = 3
}
export interface ISearchService {
  search(req: ISearchRequest): Promise<ISearchResponse>;
}
module.exports = { Corpus };
