---
logs:
  prefix: ''
  console:
    active: true
    level: info
    colorize: true
  file:
    active: false
  airbrake:
    active: false
    projectId: ''
    key: ''
database:
  host: 127.0.0.1
  port: 27017
  name: pryv-node
  authUser: ''
  authPassword: ''
nats:
  uri: 'nats://127.0.0.1:4222'
service:
  info:
    serial: '20190101'