// flow-typed signature: e74cba15af6bad59b90c33d0b65dbf86
// flow-typed version: <<STUB>>/airbrake_v^2.1.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airbrake'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'airbrake' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'airbrake/lib/airbrake' {
  declare module.exports: any;
}

declare module 'airbrake/lib/truncator' {
  declare module.exports: any;
}

declare module 'airbrake/test/common' {
  declare module.exports: any;
}

declare module 'airbrake/test/run' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-custom-request-options' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-environment' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-error-event' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-express-handler' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-filter' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-handle-exceptions' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-handle-promise-rejections' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-hapi-handler' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-host' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-ignored-exceptions' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-initialization' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-invalid-api-key' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-notify' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-request-vars' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-severity' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-throw-undefined' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-track-deployment' {
  declare module.exports: any;
}

declare module 'airbrake/test/test-truncator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'airbrake/index' {
  declare module.exports: $Exports<'airbrake'>;
}
declare module 'airbrake/index.js' {
  declare module.exports: $Exports<'airbrake'>;
}
declare module 'airbrake/lib/airbrake.js' {
  declare module.exports: $Exports<'airbrake/lib/airbrake'>;
}
declare module 'airbrake/lib/truncator.js' {
  declare module.exports: $Exports<'airbrake/lib/truncator'>;
}
declare module 'airbrake/test/common.js' {
  declare module.exports: $Exports<'airbrake/test/common'>;
}
declare module 'airbrake/test/run.js' {
  declare module.exports: $Exports<'airbrake/test/run'>;
}
declare module 'airbrake/test/test-custom-request-options.js' {
  declare module.exports: $Exports<'airbrake/test/test-custom-request-options'>;
}
declare module 'airbrake/test/test-environment.js' {
  declare module.exports: $Exports<'airbrake/test/test-environment'>;
}
declare module 'airbrake/test/test-error-event.js' {
  declare module.exports: $Exports<'airbrake/test/test-error-event'>;
}
declare module 'airbrake/test/test-express-handler.js' {
  declare module.exports: $Exports<'airbrake/test/test-express-handler'>;
}
declare module 'airbrake/test/test-filter.js' {
  declare module.exports: $Exports<'airbrake/test/test-filter'>;
}
declare module 'airbrake/test/test-handle-exceptions.js' {
  declare module.exports: $Exports<'airbrake/test/test-handle-exceptions'>;
}
declare module 'airbrake/test/test-handle-promise-rejections.js' {
  declare module.exports: $Exports<'airbrake/test/test-handle-promise-rejections'>;
}
declare module 'airbrake/test/test-hapi-handler.js' {
  declare module.exports: $Exports<'airbrake/test/test-hapi-handler'>;
}
declare module 'airbrake/test/test-host.js' {
  declare module.exports: $Exports<'airbrake/test/test-host'>;
}
declare module 'airbrake/test/test-ignored-exceptions.js' {
  declare module.exports: $Exports<'airbrake/test/test-ignored-exceptions'>;
}
declare module 'airbrake/test/test-initialization.js' {
  declare module.exports: $Exports<'airbrake/test/test-initialization'>;
}
declare module 'airbrake/test/test-invalid-api-key.js' {
  declare module.exports: $Exports<'airbrake/test/test-invalid-api-key'>;
}
declare module 'airbrake/test/test-notify.js' {
  declare module.exports: $Exports<'airbrake/test/test-notify'>;
}
declare module 'airbrake/test/test-request-vars.js' {
  declare module.exports: $Exports<'airbrake/test/test-request-vars'>;
}
declare module 'airbrake/test/test-severity.js' {
  declare module.exports: $Exports<'airbrake/test/test-severity'>;
}
declare module 'airbrake/test/test-throw-undefined.js' {
  declare module.exports: $Exports<'airbrake/test/test-throw-undefined'>;
}
declare module 'airbrake/test/test-track-deployment.js' {
  declare module.exports: $Exports<'airbrake/test/test-track-deployment'>;
}
declare module 'airbrake/test/test-truncator.js' {
  declare module.exports: $Exports<'airbrake/test/test-truncator'>;
}
