// flow-typed signature: 763e9bd8134980208ea8c923819ea3f2
// flow-typed version: <<STUB>>/airbrake-js_v^1.6.8/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airbrake-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'airbrake-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'airbrake-js/dist/client' {
  declare module.exports: any;
}

declare module 'airbrake-js/dist/client.min' {
  declare module.exports: any;
}

declare module 'airbrake-js/dist/instrumentation/express' {
  declare module.exports: any;
}

declare module 'airbrake-js/dist/instrumentation/hapi' {
  declare module.exports: any;
}

// Filename aliases
declare module 'airbrake-js/dist/client.js' {
  declare module.exports: $Exports<'airbrake-js/dist/client'>;
}
declare module 'airbrake-js/dist/client.min.js' {
  declare module.exports: $Exports<'airbrake-js/dist/client.min'>;
}
declare module 'airbrake-js/dist/instrumentation/express.js' {
  declare module.exports: $Exports<'airbrake-js/dist/instrumentation/express'>;
}
declare module 'airbrake-js/dist/instrumentation/hapi.js' {
  declare module.exports: $Exports<'airbrake-js/dist/instrumentation/hapi'>;
}
