// flow-typed signature: 838ee4408a2a9fb2639716471bf9a113
// flow-typed version: <<STUB>>/api-server_vfile:components/api-server/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'api-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'api-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'api-server/src/API' {
  declare module.exports: any;
}

declare module 'api-server/src/application' {
  declare module.exports: any;
}

declare module 'api-server/src/config' {
  declare module.exports: any;
}

declare module 'api-server/src/expressApp' {
  declare module.exports: any;
}

declare module 'api-server/src' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/accesses' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/account' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/auth/login' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/events' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/followedSlices' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/helpers/commonFunctions' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/helpers/mailing' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/helpers/querying' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/helpers/setCommonMeta' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/helpers/string' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/profile' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/service' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/streams' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/streams/ArrayStream' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/streams/DrainStream' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/streams/SetFileReadTokenStream' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/system' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/trackingFunctions' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/utility' {
  declare module.exports: any;
}

declare module 'api-server/src/methods/webhooks' {
  declare module.exports: any;
}

declare module 'api-server/src/middleware/attachment_access' {
  declare module.exports: any;
}

declare module 'api-server/src/middleware/errors' {
  declare module.exports: any;
}

declare module 'api-server/src/middleware/uploads' {
  declare module.exports: any;
}

declare module 'api-server/src/Notifications' {
  declare module.exports: any;
}

declare module 'api-server/src/Result' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/accesses' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/account' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/auth/login' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/auth/register' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/events' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/followed-slices' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/methodCallback' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/Paths' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/profile' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/root' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/service' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/streams' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/system' {
  declare module.exports: any;
}

declare module 'api-server/src/routes/webhooks' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/access' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/accessesMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/accountMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/Action' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/authMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/event' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/eventsMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/followedSlice' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/followedSlicesMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/generalMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/helpers' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/itemDeletion' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/methodError' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/profileMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/service-info' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/service-infoMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/stream' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/streamsMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/systemMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/user' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/validation' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/webhook' {
  declare module.exports: any;
}

declare module 'api-server/src/schema/webhooksMethods' {
  declare module.exports: any;
}

declare module 'api-server/src/server' {
  declare module.exports: any;
}

declare module 'api-server/src/settings' {
  declare module.exports: any;
}

declare module 'api-server/src/socket-io/change_notifier' {
  declare module.exports: any;
}

declare module 'api-server/src/socket-io' {
  declare module.exports: any;
}

declare module 'api-server/src/socket-io/Manager' {
  declare module.exports: any;
}

declare module 'api-server/src/socket-io/message_sink' {
  declare module.exports: any;
}

declare module 'api-server/src/socket-io/nats_publisher' {
  declare module.exports: any;
}

declare module 'api-server/src/socket-io/nats_subscriber' {
  declare module.exports: any;
}

declare module 'api-server/src/socket-io/nats_wire_message' {
  declare module.exports: any;
}

declare module 'api-server/test/acceptance/accesses.test' {
  declare module.exports: any;
}

declare module 'api-server/test/acceptance/userspool.test' {
  declare module.exports: any;
}

declare module 'api-server/test/accesses-app.test' {
  declare module.exports: any;
}

declare module 'api-server/test/accesses-personal.test' {
  declare module.exports: any;
}

declare module 'api-server/test/account.test' {
  declare module.exports: any;
}

declare module 'api-server/test/auditing.test' {
  declare module.exports: any;
}

declare module 'api-server/test/login.test' {
  declare module.exports: any;
}

declare module 'api-server/test/events.test' {
  declare module.exports: any;
}

declare module 'api-server/test/followed-slices.test' {
  declare module.exports: any;
}

declare module 'api-server/test/forbidden-updates.test' {
  declare module.exports: any;
}

declare module 'api-server/test/helpers/child_process' {
  declare module.exports: any;
}

declare module 'api-server/test/helpers/commonTests' {
  declare module.exports: any;
}

declare module 'api-server/test/helpers/dependencies' {
  declare module.exports: any;
}

declare module 'api-server/test/helpers' {
  declare module.exports: any;
}

declare module 'api-server/test/helpers/SourceStream' {
  declare module.exports: any;
}

declare module 'api-server/test/helpers/validation' {
  declare module.exports: any;
}

declare module 'api-server/test/methods/helpers/mailing.test' {
  declare module.exports: any;
}

declare module 'api-server/test/methods/streams/ArrayStream.test' {
  declare module.exports: any;
}

declare module 'api-server/test/methods/streams/DrainStream.test' {
  declare module.exports: any;
}

declare module 'api-server/test/permissions.fixtures/customAuthStepFn.invalid' {
  declare module.exports: any;
}

declare module 'api-server/test/permissions.fixtures/customAuthStepFn' {
  declare module.exports: any;
}

declare module 'api-server/test/permissions.test' {
  declare module.exports: any;
}

declare module 'api-server/test/profile-app.test' {
  declare module.exports: any;
}

declare module 'api-server/test/profile-personal.test' {
  declare module.exports: any;
}

declare module 'api-server/test/result.test' {
  declare module.exports: any;
}

declare module 'api-server/test/root.test' {
  declare module.exports: any;
}

declare module 'api-server/test/service-info.test' {
  declare module.exports: any;
}

declare module 'api-server/test/service-reporting.test' {
  declare module.exports: any;
}

declare module 'api-server/test/sockets.test' {
  declare module.exports: any;
}

declare module 'api-server/test/streams.test' {
  declare module.exports: any;
}

declare module 'api-server/test/support/httpServer' {
  declare module.exports: any;
}

declare module 'api-server/test/support/Mock' {
  declare module.exports: any;
}

declare module 'api-server/test/system.test' {
  declare module.exports: any;
}

declare module 'api-server/test/test-helpers' {
  declare module.exports: any;
}

declare module 'api-server/test/unit/middleware/uploads.test' {
  declare module.exports: any;
}

declare module 'api-server/test/unit/notifications.test' {
  declare module.exports: any;
}

declare module 'api-server/test/unit/routes/login.test' {
  declare module.exports: any;
}

declare module 'api-server/test/unit/schema/validation.test' {
  declare module.exports: any;
}

declare module 'api-server/test/unit/socket-io/nats_publisher.test' {
  declare module.exports: any;
}

declare module 'api-server/test/unit/socket-io/nats_subscriber.test' {
  declare module.exports: any;
}

declare module 'api-server/test/unit/test-helper' {
  declare module.exports: any;
}

declare module 'api-server/test/webhooks.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'api-server/src/API.js' {
  declare module.exports: $Exports<'api-server/src/API'>;
}
declare module 'api-server/src/application.js' {
  declare module.exports: $Exports<'api-server/src/application'>;
}
declare module 'api-server/src/config.js' {
  declare module.exports: $Exports<'api-server/src/config'>;
}
declare module 'api-server/src/expressApp.js' {
  declare module.exports: $Exports<'api-server/src/expressApp'>;
}
declare module 'api-server/src/index' {
  declare module.exports: $Exports<'api-server/src'>;
}
declare module 'api-server/src/index.js' {
  declare module.exports: $Exports<'api-server/src'>;
}
declare module 'api-server/src/methods/accesses.js' {
  declare module.exports: $Exports<'api-server/src/methods/accesses'>;
}
declare module 'api-server/src/methods/account.js' {
  declare module.exports: $Exports<'api-server/src/methods/account'>;
}
declare module 'api-server/src/methods/auth/login.js' {
  declare module.exports: $Exports<'api-server/src/methods/auth/login'>;
}
declare module 'api-server/src/methods/auth/register.js' {
  declare module.exports: $Exports<'api-server/src/methods/auth/register'>;
}
declare module 'api-server/src/methods/events.js' {
  declare module.exports: $Exports<'api-server/src/methods/events'>;
}
declare module 'api-server/src/methods/followedSlices.js' {
  declare module.exports: $Exports<'api-server/src/methods/followedSlices'>;
}
declare module 'api-server/src/methods/helpers/commonFunctions.js' {
  declare module.exports: $Exports<'api-server/src/methods/helpers/commonFunctions'>;
}
declare module 'api-server/src/methods/helpers/mailing.js' {
  declare module.exports: $Exports<'api-server/src/methods/helpers/mailing'>;
}
declare module 'api-server/src/methods/helpers/querying.js' {
  declare module.exports: $Exports<'api-server/src/methods/helpers/querying'>;
}
declare module 'api-server/src/methods/helpers/setCommonMeta.js' {
  declare module.exports: $Exports<'api-server/src/methods/helpers/setCommonMeta'>;
}
declare module 'api-server/src/methods/helpers/string.js' {
  declare module.exports: $Exports<'api-server/src/methods/helpers/string'>;
}
declare module 'api-server/src/methods/profile.js' {
  declare module.exports: $Exports<'api-server/src/methods/profile'>;
}
declare module 'api-server/src/methods/service.js' {
  declare module.exports: $Exports<'api-server/src/methods/service'>;
}
declare module 'api-server/src/methods/streams.js' {
  declare module.exports: $Exports<'api-server/src/methods/streams'>;
}
declare module 'api-server/src/methods/streams/ArrayStream.js' {
  declare module.exports: $Exports<'api-server/src/methods/streams/ArrayStream'>;
}
declare module 'api-server/src/methods/streams/DrainStream.js' {
  declare module.exports: $Exports<'api-server/src/methods/streams/DrainStream'>;
}
declare module 'api-server/src/methods/streams/SetFileReadTokenStream.js' {
  declare module.exports: $Exports<'api-server/src/methods/streams/SetFileReadTokenStream'>;
}
declare module 'api-server/src/methods/system.js' {
  declare module.exports: $Exports<'api-server/src/methods/system'>;
}
declare module 'api-server/src/methods/trackingFunctions.js' {
  declare module.exports: $Exports<'api-server/src/methods/trackingFunctions'>;
}
declare module 'api-server/src/methods/utility.js' {
  declare module.exports: $Exports<'api-server/src/methods/utility'>;
}
declare module 'api-server/src/methods/webhooks.js' {
  declare module.exports: $Exports<'api-server/src/methods/webhooks'>;
}
declare module 'api-server/src/middleware/attachment_access.js' {
  declare module.exports: $Exports<'api-server/src/middleware/attachment_access'>;
}
declare module 'api-server/src/middleware/errors.js' {
  declare module.exports: $Exports<'api-server/src/middleware/errors'>;
}
declare module 'api-server/src/middleware/uploads.js' {
  declare module.exports: $Exports<'api-server/src/middleware/uploads'>;
}
declare module 'api-server/src/Notifications.js' {
  declare module.exports: $Exports<'api-server/src/Notifications'>;
}
declare module 'api-server/src/Result.js' {
  declare module.exports: $Exports<'api-server/src/Result'>;
}
declare module 'api-server/src/routes/accesses.js' {
  declare module.exports: $Exports<'api-server/src/routes/accesses'>;
}
declare module 'api-server/src/routes/account.js' {
  declare module.exports: $Exports<'api-server/src/routes/account'>;
}
declare module 'api-server/src/routes/auth/login.js' {
  declare module.exports: $Exports<'api-server/src/routes/auth/login'>;
}
declare module 'api-server/src/routes/auth/register.js' {
  declare module.exports: $Exports<'api-server/src/routes/auth/register'>;
}
declare module 'api-server/src/routes/events.js' {
  declare module.exports: $Exports<'api-server/src/routes/events'>;
}
declare module 'api-server/src/routes/followed-slices.js' {
  declare module.exports: $Exports<'api-server/src/routes/followed-slices'>;
}
declare module 'api-server/src/routes/methodCallback.js' {
  declare module.exports: $Exports<'api-server/src/routes/methodCallback'>;
}
declare module 'api-server/src/routes/Paths.js' {
  declare module.exports: $Exports<'api-server/src/routes/Paths'>;
}
declare module 'api-server/src/routes/profile.js' {
  declare module.exports: $Exports<'api-server/src/routes/profile'>;
}
declare module 'api-server/src/routes/root.js' {
  declare module.exports: $Exports<'api-server/src/routes/root'>;
}
declare module 'api-server/src/routes/service.js' {
  declare module.exports: $Exports<'api-server/src/routes/service'>;
}
declare module 'api-server/src/routes/streams.js' {
  declare module.exports: $Exports<'api-server/src/routes/streams'>;
}
declare module 'api-server/src/routes/system.js' {
  declare module.exports: $Exports<'api-server/src/routes/system'>;
}
declare module 'api-server/src/routes/webhooks.js' {
  declare module.exports: $Exports<'api-server/src/routes/webhooks'>;
}
declare module 'api-server/src/schema/access.js' {
  declare module.exports: $Exports<'api-server/src/schema/access'>;
}
declare module 'api-server/src/schema/accessesMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/accessesMethods'>;
}
declare module 'api-server/src/schema/accountMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/accountMethods'>;
}
declare module 'api-server/src/schema/Action.js' {
  declare module.exports: $Exports<'api-server/src/schema/Action'>;
}
declare module 'api-server/src/schema/authMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/authMethods'>;
}
declare module 'api-server/src/schema/event.js' {
  declare module.exports: $Exports<'api-server/src/schema/event'>;
}
declare module 'api-server/src/schema/eventsMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/eventsMethods'>;
}
declare module 'api-server/src/schema/followedSlice.js' {
  declare module.exports: $Exports<'api-server/src/schema/followedSlice'>;
}
declare module 'api-server/src/schema/followedSlicesMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/followedSlicesMethods'>;
}
declare module 'api-server/src/schema/generalMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/generalMethods'>;
}
declare module 'api-server/src/schema/helpers.js' {
  declare module.exports: $Exports<'api-server/src/schema/helpers'>;
}
declare module 'api-server/src/schema/itemDeletion.js' {
  declare module.exports: $Exports<'api-server/src/schema/itemDeletion'>;
}
declare module 'api-server/src/schema/methodError.js' {
  declare module.exports: $Exports<'api-server/src/schema/methodError'>;
}
declare module 'api-server/src/schema/profileMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/profileMethods'>;
}
declare module 'api-server/src/schema/service-info.js' {
  declare module.exports: $Exports<'api-server/src/schema/service-info'>;
}
declare module 'api-server/src/schema/service-infoMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/service-infoMethods'>;
}
declare module 'api-server/src/schema/stream.js' {
  declare module.exports: $Exports<'api-server/src/schema/stream'>;
}
declare module 'api-server/src/schema/streamsMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/streamsMethods'>;
}
declare module 'api-server/src/schema/systemMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/systemMethods'>;
}
declare module 'api-server/src/schema/user.js' {
  declare module.exports: $Exports<'api-server/src/schema/user'>;
}
declare module 'api-server/src/schema/validation.js' {
  declare module.exports: $Exports<'api-server/src/schema/validation'>;
}
declare module 'api-server/src/schema/webhook.js' {
  declare module.exports: $Exports<'api-server/src/schema/webhook'>;
}
declare module 'api-server/src/schema/webhooksMethods.js' {
  declare module.exports: $Exports<'api-server/src/schema/webhooksMethods'>;
}
declare module 'api-server/src/server.js' {
  declare module.exports: $Exports<'api-server/src/server'>;
}
declare module 'api-server/src/settings.js' {
  declare module.exports: $Exports<'api-server/src/settings'>;
}
declare module 'api-server/src/socket-io/change_notifier.js' {
  declare module.exports: $Exports<'api-server/src/socket-io/change_notifier'>;
}
declare module 'api-server/src/socket-io/index' {
  declare module.exports: $Exports<'api-server/src/socket-io'>;
}
declare module 'api-server/src/socket-io/index.js' {
  declare module.exports: $Exports<'api-server/src/socket-io'>;
}
declare module 'api-server/src/socket-io/Manager.js' {
  declare module.exports: $Exports<'api-server/src/socket-io/Manager'>;
}
declare module 'api-server/src/socket-io/message_sink.js' {
  declare module.exports: $Exports<'api-server/src/socket-io/message_sink'>;
}
declare module 'api-server/src/socket-io/nats_publisher.js' {
  declare module.exports: $Exports<'api-server/src/socket-io/nats_publisher'>;
}
declare module 'api-server/src/socket-io/nats_subscriber.js' {
  declare module.exports: $Exports<'api-server/src/socket-io/nats_subscriber'>;
}
declare module 'api-server/src/socket-io/nats_wire_message.js' {
  declare module.exports: $Exports<'api-server/src/socket-io/nats_wire_message'>;
}
declare module 'api-server/test/acceptance/accesses.test.js' {
  declare module.exports: $Exports<'api-server/test/acceptance/accesses.test'>;
}
declare module 'api-server/test/acceptance/userspool.test.js' {
  declare module.exports: $Exports<'api-server/test/acceptance/userspool.test'>;
}
declare module 'api-server/test/accesses-app.test.js' {
  declare module.exports: $Exports<'api-server/test/accesses-app.test'>;
}
declare module 'api-server/test/accesses-personal.test.js' {
  declare module.exports: $Exports<'api-server/test/accesses-personal.test'>;
}
declare module 'api-server/test/account.test.js' {
  declare module.exports: $Exports<'api-server/test/account.test'>;
}
declare module 'api-server/test/auditing.test.js' {
  declare module.exports: $Exports<'api-server/test/auditing.test'>;
}
declare module 'api-server/test/login.test.js' {
  declare module.exports: $Exports<'api-server/test/login.test'>;
}
declare module 'api-server/test/events.test.js' {
  declare module.exports: $Exports<'api-server/test/events.test'>;
}
declare module 'api-server/test/followed-slices.test.js' {
  declare module.exports: $Exports<'api-server/test/followed-slices.test'>;
}
declare module 'api-server/test/forbidden-updates.test.js' {
  declare module.exports: $Exports<'api-server/test/forbidden-updates.test'>;
}
declare module 'api-server/test/helpers/child_process.js' {
  declare module.exports: $Exports<'api-server/test/helpers/child_process'>;
}
declare module 'api-server/test/helpers/commonTests.js' {
  declare module.exports: $Exports<'api-server/test/helpers/commonTests'>;
}
declare module 'api-server/test/helpers/dependencies.js' {
  declare module.exports: $Exports<'api-server/test/helpers/dependencies'>;
}
declare module 'api-server/test/helpers/index' {
  declare module.exports: $Exports<'api-server/test/helpers'>;
}
declare module 'api-server/test/helpers/index.js' {
  declare module.exports: $Exports<'api-server/test/helpers'>;
}
declare module 'api-server/test/helpers/SourceStream.js' {
  declare module.exports: $Exports<'api-server/test/helpers/SourceStream'>;
}
declare module 'api-server/test/helpers/validation.js' {
  declare module.exports: $Exports<'api-server/test/helpers/validation'>;
}
declare module 'api-server/test/methods/helpers/mailing.test.js' {
  declare module.exports: $Exports<'api-server/test/methods/helpers/mailing.test'>;
}
declare module 'api-server/test/methods/streams/ArrayStream.test.js' {
  declare module.exports: $Exports<'api-server/test/methods/streams/ArrayStream.test'>;
}
declare module 'api-server/test/methods/streams/DrainStream.test.js' {
  declare module.exports: $Exports<'api-server/test/methods/streams/DrainStream.test'>;
}
declare module 'api-server/test/permissions.fixtures/customAuthStepFn.invalid.js' {
  declare module.exports: $Exports<'api-server/test/permissions.fixtures/customAuthStepFn.invalid'>;
}
declare module 'api-server/test/permissions.fixtures/customAuthStepFn.js' {
  declare module.exports: $Exports<'api-server/test/permissions.fixtures/customAuthStepFn'>;
}
declare module 'api-server/test/permissions.test.js' {
  declare module.exports: $Exports<'api-server/test/permissions.test'>;
}
declare module 'api-server/test/profile-app.test.js' {
  declare module.exports: $Exports<'api-server/test/profile-app.test'>;
}
declare module 'api-server/test/profile-personal.test.js' {
  declare module.exports: $Exports<'api-server/test/profile-personal.test'>;
}
declare module 'api-server/test/result.test.js' {
  declare module.exports: $Exports<'api-server/test/result.test'>;
}
declare module 'api-server/test/root.test.js' {
  declare module.exports: $Exports<'api-server/test/root.test'>;
}
declare module 'api-server/test/service-info.test.js' {
  declare module.exports: $Exports<'api-server/test/service-info.test'>;
}
declare module 'api-server/test/service-reporting.test.js' {
  declare module.exports: $Exports<'api-server/test/service-reporting.test'>;
}
declare module 'api-server/test/sockets.test.js' {
  declare module.exports: $Exports<'api-server/test/sockets.test'>;
}
declare module 'api-server/test/streams.test.js' {
  declare module.exports: $Exports<'api-server/test/streams.test'>;
}
declare module 'api-server/test/support/httpServer.js' {
  declare module.exports: $Exports<'api-server/test/support/httpServer'>;
}
declare module 'api-server/test/support/Mock.js' {
  declare module.exports: $Exports<'api-server/test/support/Mock'>;
}
declare module 'api-server/test/system.test.js' {
  declare module.exports: $Exports<'api-server/test/system.test'>;
}
declare module 'api-server/test/test-helpers.js' {
  declare module.exports: $Exports<'api-server/test/test-helpers'>;
}
declare module 'api-server/test/unit/middleware/uploads.test.js' {
  declare module.exports: $Exports<'api-server/test/unit/middleware/uploads.test'>;
}
declare module 'api-server/test/unit/notifications.test.js' {
  declare module.exports: $Exports<'api-server/test/unit/notifications.test'>;
}
declare module 'api-server/test/unit/routes/login.test.js' {
  declare module.exports: $Exports<'api-server/test/unit/routes/login.test'>;
}
declare module 'api-server/test/unit/schema/validation.test.js' {
  declare module.exports: $Exports<'api-server/test/unit/schema/validation.test'>;
}
declare module 'api-server/test/unit/socket-io/nats_publisher.test.js' {
  declare module.exports: $Exports<'api-server/test/unit/socket-io/nats_publisher.test'>;
}
declare module 'api-server/test/unit/socket-io/nats_subscriber.test.js' {
  declare module.exports: $Exports<'api-server/test/unit/socket-io/nats_subscriber.test'>;
}
declare module 'api-server/test/unit/test-helper.js' {
  declare module.exports: $Exports<'api-server/test/unit/test-helper'>;
}
declare module 'api-server/test/webhooks.test.js' {
  declare module.exports: $Exports<'api-server/test/webhooks.test'>;
}
