/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 81d322fe15ca08996845d4ad5869128b
// flow-typed version: <<STUB>>/awaiting_v^3.0.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'awaiting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'awaiting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'awaiting/dist/awaiting.common' {
  declare module.exports: any;
}

declare module 'awaiting/dist/awaiting.umd' {
  declare module.exports: any;
}

declare module 'awaiting/lib/awaiting' {
  declare module.exports: any;
}

declare module 'awaiting/test/awaited.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/awaiting.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/browser/test' {
  declare module.exports: any;
}

declare module 'awaiting/test/callback.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/delay.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/errorlist.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/failure.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/fixtures/rejection-ignore' {
  declare module.exports: any;
}

declare module 'awaiting/test/fixtures/rejection-multiple' {
  declare module.exports: any;
}

declare module 'awaiting/test/fixtures/rejection-swallow' {
  declare module.exports: any;
}

declare module 'awaiting/test/fixtures/rejection-throw' {
  declare module.exports: any;
}

declare module 'awaiting/test/limit.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/list.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/map.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/node/event.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/node/rejections.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/object.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/result.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/set.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/single.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/success.test' {
  declare module.exports: any;
}

declare module 'awaiting/test/time.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'awaiting/dist/awaiting.common.js' {
  declare module.exports: $Exports<'awaiting/dist/awaiting.common'>;
}
declare module 'awaiting/dist/awaiting.umd.js' {
  declare module.exports: $Exports<'awaiting/dist/awaiting.umd'>;
}
declare module 'awaiting/lib/awaiting.js' {
  declare module.exports: $Exports<'awaiting/lib/awaiting'>;
}
declare module 'awaiting/test/awaited.test.js' {
  declare module.exports: $Exports<'awaiting/test/awaited.test'>;
}
declare module 'awaiting/test/awaiting.test.js' {
  declare module.exports: $Exports<'awaiting/test/awaiting.test'>;
}
declare module 'awaiting/test/browser/test.js' {
  declare module.exports: $Exports<'awaiting/test/browser/test'>;
}
declare module 'awaiting/test/callback.test.js' {
  declare module.exports: $Exports<'awaiting/test/callback.test'>;
}
declare module 'awaiting/test/delay.test.js' {
  declare module.exports: $Exports<'awaiting/test/delay.test'>;
}
declare module 'awaiting/test/errorlist.test.js' {
  declare module.exports: $Exports<'awaiting/test/errorlist.test'>;
}
declare module 'awaiting/test/failure.test.js' {
  declare module.exports: $Exports<'awaiting/test/failure.test'>;
}
declare module 'awaiting/test/fixtures/rejection-ignore.js' {
  declare module.exports: $Exports<'awaiting/test/fixtures/rejection-ignore'>;
}
declare module 'awaiting/test/fixtures/rejection-multiple.js' {
  declare module.exports: $Exports<'awaiting/test/fixtures/rejection-multiple'>;
}
declare module 'awaiting/test/fixtures/rejection-swallow.js' {
  declare module.exports: $Exports<'awaiting/test/fixtures/rejection-swallow'>;
}
declare module 'awaiting/test/fixtures/rejection-throw.js' {
  declare module.exports: $Exports<'awaiting/test/fixtures/rejection-throw'>;
}
declare module 'awaiting/test/limit.test.js' {
  declare module.exports: $Exports<'awaiting/test/limit.test'>;
}
declare module 'awaiting/test/list.test.js' {
  declare module.exports: $Exports<'awaiting/test/list.test'>;
}
declare module 'awaiting/test/map.test.js' {
  declare module.exports: $Exports<'awaiting/test/map.test'>;
}
declare module 'awaiting/test/node/event.test.js' {
  declare module.exports: $Exports<'awaiting/test/node/event.test'>;
}
declare module 'awaiting/test/node/rejections.test.js' {
  declare module.exports: $Exports<'awaiting/test/node/rejections.test'>;
}
declare module 'awaiting/test/object.test.js' {
  declare module.exports: $Exports<'awaiting/test/object.test'>;
}
declare module 'awaiting/test/result.test.js' {
  declare module.exports: $Exports<'awaiting/test/result.test'>;
}
declare module 'awaiting/test/set.test.js' {
  declare module.exports: $Exports<'awaiting/test/set.test'>;
}
declare module 'awaiting/test/single.test.js' {
  declare module.exports: $Exports<'awaiting/test/single.test'>;
}
declare module 'awaiting/test/success.test.js' {
  declare module.exports: $Exports<'awaiting/test/success.test'>;
}
declare module 'awaiting/test/time.test.js' {
  declare module.exports: $Exports<'awaiting/test/time.test'>;
}
