// flow-typed signature: 2ae742d43697f2f37491f96e4639451d
// flow-typed version: <<STUB>>/axon_v2.0.x/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axon/benchmark/pub' {
  declare module.exports: any;
}

declare module 'axon/benchmark/sub' {
  declare module.exports: any;
}

declare module 'axon/lib' {
  declare module.exports: any;
}

declare module 'axon/lib/plugins/queue' {
  declare module.exports: any;
}

declare module 'axon/lib/plugins/round-robin' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/pub-emitter' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/pub' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/pull' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/push' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/rep' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/req' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/sock' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/sub-emitter' {
  declare module.exports: any;
}

declare module 'axon/lib/sockets/sub' {
  declare module.exports: any;
}

declare module 'axon/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axon/benchmark/pub.js' {
  declare module.exports: $Exports<'axon/benchmark/pub'>;
}
declare module 'axon/benchmark/sub.js' {
  declare module.exports: $Exports<'axon/benchmark/sub'>;
}
declare module 'axon/index' {
  declare module.exports: $Exports<'axon'>;
}
declare module 'axon/index.js' {
  declare module.exports: $Exports<'axon'>;
}
declare module 'axon/lib/index' {
  declare module.exports: $Exports<'axon/lib'>;
}
declare module 'axon/lib/index.js' {
  declare module.exports: $Exports<'axon/lib'>;
}
declare module 'axon/lib/plugins/queue.js' {
  declare module.exports: $Exports<'axon/lib/plugins/queue'>;
}
declare module 'axon/lib/plugins/round-robin.js' {
  declare module.exports: $Exports<'axon/lib/plugins/round-robin'>;
}
declare module 'axon/lib/sockets/pub-emitter.js' {
  declare module.exports: $Exports<'axon/lib/sockets/pub-emitter'>;
}
declare module 'axon/lib/sockets/pub.js' {
  declare module.exports: $Exports<'axon/lib/sockets/pub'>;
}
declare module 'axon/lib/sockets/pull.js' {
  declare module.exports: $Exports<'axon/lib/sockets/pull'>;
}
declare module 'axon/lib/sockets/push.js' {
  declare module.exports: $Exports<'axon/lib/sockets/push'>;
}
declare module 'axon/lib/sockets/rep.js' {
  declare module.exports: $Exports<'axon/lib/sockets/rep'>;
}
declare module 'axon/lib/sockets/req.js' {
  declare module.exports: $Exports<'axon/lib/sockets/req'>;
}
declare module 'axon/lib/sockets/sock.js' {
  declare module.exports: $Exports<'axon/lib/sockets/sock'>;
}
declare module 'axon/lib/sockets/sub-emitter.js' {
  declare module.exports: $Exports<'axon/lib/sockets/sub-emitter'>;
}
declare module 'axon/lib/sockets/sub.js' {
  declare module.exports: $Exports<'axon/lib/sockets/sub'>;
}
declare module 'axon/lib/utils.js' {
  declare module.exports: $Exports<'axon/lib/utils'>;
}
