/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 9e27f1f1dd927d123862d79ad56f1ffe
// flow-typed version: <<STUB>>/babel-plugin-transform-class-properties_v^6.24.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-class-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-class-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-class-properties/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-class-properties/lib/index' {
  declare module.exports: $Exports<'babel-plugin-transform-class-properties/lib'>;
}
declare module 'babel-plugin-transform-class-properties/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-class-properties/lib'>;
}
