// flow-typed signature: 2695ece0f4d996aa15af2771b0d45254
// flow-typed version: <<STUB>>/better-sqlite3_v^7.5.1/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'better-sqlite3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'better-sqlite3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'better-sqlite3/deps/copy' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/database' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/aggregate' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/backup' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/function' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/inspect' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/pragma' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/serialize' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/table' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/transaction' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/methods/wrappers' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/sqlite-error' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'better-sqlite3/deps/copy.js' {
  declare module.exports: $Exports<'better-sqlite3/deps/copy'>;
}
declare module 'better-sqlite3/lib/database.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/database'>;
}
declare module 'better-sqlite3/lib/index' {
  declare module.exports: $Exports<'better-sqlite3/lib'>;
}
declare module 'better-sqlite3/lib/index.js' {
  declare module.exports: $Exports<'better-sqlite3/lib'>;
}
declare module 'better-sqlite3/lib/methods/aggregate.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/aggregate'>;
}
declare module 'better-sqlite3/lib/methods/backup.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/backup'>;
}
declare module 'better-sqlite3/lib/methods/function.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/function'>;
}
declare module 'better-sqlite3/lib/methods/inspect.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/inspect'>;
}
declare module 'better-sqlite3/lib/methods/pragma.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/pragma'>;
}
declare module 'better-sqlite3/lib/methods/serialize.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/serialize'>;
}
declare module 'better-sqlite3/lib/methods/table.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/table'>;
}
declare module 'better-sqlite3/lib/methods/transaction.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/transaction'>;
}
declare module 'better-sqlite3/lib/methods/wrappers.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/methods/wrappers'>;
}
declare module 'better-sqlite3/lib/sqlite-error.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/sqlite-error'>;
}
declare module 'better-sqlite3/lib/util.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/util'>;
}
