/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: ae44746d392ec39bb1ecb1e525462f24
// flow-typed version: <<STUB>>/blanket_v^1.2.3/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blanket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blanket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blanket/dist/jasmine/blanket_jasmine' {
  declare module.exports: any;
}

declare module 'blanket/dist/jasmine/blanket_jasmine.min' {
  declare module.exports: any;
}

declare module 'blanket/dist/mocha/blanket_mocha' {
  declare module.exports: any;
}

declare module 'blanket/dist/mocha/blanket_mocha.min' {
  declare module.exports: any;
}

declare module 'blanket/dist/qunit/blanket' {
  declare module.exports: any;
}

declare module 'blanket/dist/qunit/blanket.min' {
  declare module.exports: any;
}

declare module 'blanket/src/adapters/jasmine-2.x-blanket' {
  declare module.exports: any;
}

declare module 'blanket/src/adapters/jasmine-blanket' {
  declare module.exports: any;
}

declare module 'blanket/src/adapters/mocha-blanket' {
  declare module.exports: any;
}

declare module 'blanket/src/adapters/usage-blanket' {
  declare module.exports: any;
}

declare module 'blanket/src/adapters/yui-blanket' {
  declare module.exports: any;
}

declare module 'blanket/src/blanket_browser' {
  declare module.exports: any;
}

declare module 'blanket/src/blanket' {
  declare module.exports: any;
}

declare module 'blanket/src/blanketRequire' {
  declare module.exports: any;
}

declare module 'blanket/src/config' {
  declare module.exports: any;
}

declare module 'blanket/src' {
  declare module.exports: any;
}

declare module 'blanket/src/loaders/blanket_cs' {
  declare module.exports: any;
}

declare module 'blanket/src/node-loaders/cjsx' {
  declare module.exports: any;
}

declare module 'blanket/src/node-loaders/coffee-script' {
  declare module.exports: any;
}

declare module 'blanket/src/node-loaders/dynamic-loader' {
  declare module.exports: any;
}

declare module 'blanket/src/node-loaders/iced-coffee-script' {
  declare module.exports: any;
}

declare module 'blanket/src/node-loaders/simple-node-loader' {
  declare module.exports: any;
}

declare module 'blanket/src/qunit/noautorun' {
  declare module.exports: any;
}

declare module 'blanket/src/qunit/qunit' {
  declare module.exports: any;
}

declare module 'blanket/src/qunit/reporter' {
  declare module.exports: any;
}

declare module 'blanket/src/reporters/lcov_reporter' {
  declare module.exports: any;
}

declare module 'blanket/src/reporters/simple_json_reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blanket/dist/jasmine/blanket_jasmine.js' {
  declare module.exports: $Exports<'blanket/dist/jasmine/blanket_jasmine'>;
}
declare module 'blanket/dist/jasmine/blanket_jasmine.min.js' {
  declare module.exports: $Exports<'blanket/dist/jasmine/blanket_jasmine.min'>;
}
declare module 'blanket/dist/mocha/blanket_mocha.js' {
  declare module.exports: $Exports<'blanket/dist/mocha/blanket_mocha'>;
}
declare module 'blanket/dist/mocha/blanket_mocha.min.js' {
  declare module.exports: $Exports<'blanket/dist/mocha/blanket_mocha.min'>;
}
declare module 'blanket/dist/qunit/blanket.js' {
  declare module.exports: $Exports<'blanket/dist/qunit/blanket'>;
}
declare module 'blanket/dist/qunit/blanket.min.js' {
  declare module.exports: $Exports<'blanket/dist/qunit/blanket.min'>;
}
declare module 'blanket/src/adapters/jasmine-2.x-blanket.js' {
  declare module.exports: $Exports<'blanket/src/adapters/jasmine-2.x-blanket'>;
}
declare module 'blanket/src/adapters/jasmine-blanket.js' {
  declare module.exports: $Exports<'blanket/src/adapters/jasmine-blanket'>;
}
declare module 'blanket/src/adapters/mocha-blanket.js' {
  declare module.exports: $Exports<'blanket/src/adapters/mocha-blanket'>;
}
declare module 'blanket/src/adapters/usage-blanket.js' {
  declare module.exports: $Exports<'blanket/src/adapters/usage-blanket'>;
}
declare module 'blanket/src/adapters/yui-blanket.js' {
  declare module.exports: $Exports<'blanket/src/adapters/yui-blanket'>;
}
declare module 'blanket/src/blanket_browser.js' {
  declare module.exports: $Exports<'blanket/src/blanket_browser'>;
}
declare module 'blanket/src/blanket.js' {
  declare module.exports: $Exports<'blanket/src/blanket'>;
}
declare module 'blanket/src/blanketRequire.js' {
  declare module.exports: $Exports<'blanket/src/blanketRequire'>;
}
declare module 'blanket/src/config.js' {
  declare module.exports: $Exports<'blanket/src/config'>;
}
declare module 'blanket/src/index' {
  declare module.exports: $Exports<'blanket/src'>;
}
declare module 'blanket/src/index.js' {
  declare module.exports: $Exports<'blanket/src'>;
}
declare module 'blanket/src/loaders/blanket_cs.js' {
  declare module.exports: $Exports<'blanket/src/loaders/blanket_cs'>;
}
declare module 'blanket/src/node-loaders/cjsx.js' {
  declare module.exports: $Exports<'blanket/src/node-loaders/cjsx'>;
}
declare module 'blanket/src/node-loaders/coffee-script.js' {
  declare module.exports: $Exports<'blanket/src/node-loaders/coffee-script'>;
}
declare module 'blanket/src/node-loaders/dynamic-loader.js' {
  declare module.exports: $Exports<'blanket/src/node-loaders/dynamic-loader'>;
}
declare module 'blanket/src/node-loaders/iced-coffee-script.js' {
  declare module.exports: $Exports<'blanket/src/node-loaders/iced-coffee-script'>;
}
declare module 'blanket/src/node-loaders/simple-node-loader.js' {
  declare module.exports: $Exports<'blanket/src/node-loaders/simple-node-loader'>;
}
declare module 'blanket/src/qunit/noautorun.js' {
  declare module.exports: $Exports<'blanket/src/qunit/noautorun'>;
}
declare module 'blanket/src/qunit/qunit.js' {
  declare module.exports: $Exports<'blanket/src/qunit/qunit'>;
}
declare module 'blanket/src/qunit/reporter.js' {
  declare module.exports: $Exports<'blanket/src/qunit/reporter'>;
}
declare module 'blanket/src/reporters/lcov_reporter.js' {
  declare module.exports: $Exports<'blanket/src/reporters/lcov_reporter'>;
}
declare module 'blanket/src/reporters/simple_json_reporter.js' {
  declare module.exports: $Exports<'blanket/src/reporters/simple_json_reporter'>;
}
