// flow-typed signature: a7f1b6b9d1235b6b9cdbaa6e6777a53e
// flow-typed version: <<STUB>>/business_vfile:components/business/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'business'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'business' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'business/src' {
  declare module.exports: any;
}

declare module 'business/src/series' {
  declare module.exports: any;
}

declare module 'business/src/series/batch_request' {
  declare module.exports: any;
}

declare module 'business/src/series/data_matrix' {
  declare module.exports: any;
}

declare module 'business/src/series/errors' {
  declare module.exports: any;
}

declare module 'business/src/series/influx_connection' {
  declare module.exports: any;
}

declare module 'business/src/series/namespace_batch' {
  declare module.exports: any;
}

declare module 'business/src/series/repository' {
  declare module.exports: any;
}

declare module 'business/src/series/row' {
  declare module.exports: any;
}

declare module 'business/src/series/series' {
  declare module.exports: any;
}

declare module 'business/src/types' {
  declare module.exports: any;
}

declare module 'business/src/types/basic_type' {
  declare module.exports: any;
}

declare module 'business/src/types/complex_type' {
  declare module.exports: any;
}

declare module 'business/src/types/errors' {
  declare module.exports: any;
}

declare module 'business/src/types/influx_row_type' {
  declare module.exports: any;
}

declare module 'business/src/types/interfaces' {
  declare module.exports: any;
}

declare module 'business/src/types/value_types' {
  declare module.exports: any;
}

declare module 'business/src/webhooks/repository' {
  declare module.exports: any;
}

declare module 'business/src/webhooks/Webhook' {
  declare module.exports: any;
}

declare module 'business/test/acceptance/series/manage_influx_data.test' {
  declare module.exports: any;
}

declare module 'business/test/acceptance/webhooks/support/httpServer' {
  declare module.exports: any;
}

declare module 'business/test/acceptance/webhooks/Webhook.test' {
  declare module.exports: any;
}

declare module 'business/test/test-helpers' {
  declare module.exports: any;
}

declare module 'business/test/unit/series/batch_request.test' {
  declare module.exports: any;
}

declare module 'business/test/unit/series/data_matrix.test' {
  declare module.exports: any;
}

declare module 'business/test/unit/series/repository.test' {
  declare module.exports: any;
}

declare module 'business/test/unit/types.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'business/src/index' {
  declare module.exports: $Exports<'business/src'>;
}
declare module 'business/src/index.js' {
  declare module.exports: $Exports<'business/src'>;
}
declare module 'business/src/series.js' {
  declare module.exports: $Exports<'business/src/series'>;
}
declare module 'business/src/series/batch_request.js' {
  declare module.exports: $Exports<'business/src/series/batch_request'>;
}
declare module 'business/src/series/data_matrix.js' {
  declare module.exports: $Exports<'business/src/series/data_matrix'>;
}
declare module 'business/src/series/errors.js' {
  declare module.exports: $Exports<'business/src/series/errors'>;
}
declare module 'business/src/series/influx_connection.js' {
  declare module.exports: $Exports<'business/src/series/influx_connection'>;
}
declare module 'business/src/series/namespace_batch.js' {
  declare module.exports: $Exports<'business/src/series/namespace_batch'>;
}
declare module 'business/src/series/repository.js' {
  declare module.exports: $Exports<'business/src/series/repository'>;
}
declare module 'business/src/series/row.js' {
  declare module.exports: $Exports<'business/src/series/row'>;
}
declare module 'business/src/series/series.js' {
  declare module.exports: $Exports<'business/src/series/series'>;
}
declare module 'business/src/types.js' {
  declare module.exports: $Exports<'business/src/types'>;
}
declare module 'business/src/types/basic_type.js' {
  declare module.exports: $Exports<'business/src/types/basic_type'>;
}
declare module 'business/src/types/complex_type.js' {
  declare module.exports: $Exports<'business/src/types/complex_type'>;
}
declare module 'business/src/types/errors.js' {
  declare module.exports: $Exports<'business/src/types/errors'>;
}
declare module 'business/src/types/influx_row_type.js' {
  declare module.exports: $Exports<'business/src/types/influx_row_type'>;
}
declare module 'business/src/types/interfaces.js' {
  declare module.exports: $Exports<'business/src/types/interfaces'>;
}
declare module 'business/src/types/value_types.js' {
  declare module.exports: $Exports<'business/src/types/value_types'>;
}
declare module 'business/src/webhooks/repository.js' {
  declare module.exports: $Exports<'business/src/webhooks/repository'>;
}
declare module 'business/src/webhooks/Webhook.js' {
  declare module.exports: $Exports<'business/src/webhooks/Webhook'>;
}
declare module 'business/test/acceptance/series/manage_influx_data.test.js' {
  declare module.exports: $Exports<'business/test/acceptance/series/manage_influx_data.test'>;
}
declare module 'business/test/acceptance/webhooks/support/httpServer.js' {
  declare module.exports: $Exports<'business/test/acceptance/webhooks/support/httpServer'>;
}
declare module 'business/test/acceptance/webhooks/Webhook.test.js' {
  declare module.exports: $Exports<'business/test/acceptance/webhooks/Webhook.test'>;
}
declare module 'business/test/test-helpers.js' {
  declare module.exports: $Exports<'business/test/test-helpers'>;
}
declare module 'business/test/unit/series/batch_request.test.js' {
  declare module.exports: $Exports<'business/test/unit/series/batch_request.test'>;
}
declare module 'business/test/unit/series/data_matrix.test.js' {
  declare module.exports: $Exports<'business/test/unit/series/data_matrix.test'>;
}
declare module 'business/test/unit/series/repository.test.js' {
  declare module.exports: $Exports<'business/test/unit/series/repository.test'>;
}
declare module 'business/test/unit/types.test.js' {
  declare module.exports: $Exports<'business/test/unit/types.test'>;
}
