// flow-typed signature: 82d457275931da82af8720bf6614773b
// flow-typed version: <<STUB>>/business_vfile:source/business/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'business'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'business' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'business/src/index' {
  declare module.exports: any;
}

declare module 'business/src/series/index' {
  declare module.exports: any;
}

declare module 'business/src/series/repository' {
  declare module.exports: any;
}

declare module 'business/test/test-helpers' {
  declare module.exports: any;
}

declare module 'business/test/unit/series/repository.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'business/src/index.js' {
  declare module.exports: $Exports<'business/src/index'>;
}
declare module 'business/src/series/index.js' {
  declare module.exports: $Exports<'business/src/series/index'>;
}
declare module 'business/src/series/repository.js' {
  declare module.exports: $Exports<'business/src/series/repository'>;
}
declare module 'business/test/test-helpers.js' {
  declare module.exports: $Exports<'business/test/test-helpers'>;
}
declare module 'business/test/unit/series/repository.test.js' {
  declare module.exports: $Exports<'business/test/unit/series/repository.test'>;
}
