// flow-typed signature: 163730e89c6058c26dba503546e09647
// flow-typed version: <<STUB>>/charlatan_v^1.1.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'charlatan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'charlatan' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'charlatan/lib/charlatan' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/address' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/app' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/avatar' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/bitcoin' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/business' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/code' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/commerce' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/company' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/date' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/finance' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/hacker' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/helpers' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/internet' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/lorem' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/name' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/number' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/phone_number' {
  declare module.exports: any;
}

declare module 'charlatan/lib/charlatan/team' {
  declare module.exports: any;
}

declare module 'charlatan/lib/locales_browser' {
  declare module.exports: any;
}

declare module 'charlatan/lib/locales' {
  declare module.exports: any;
}

// Filename aliases
declare module 'charlatan/index' {
  declare module.exports: $Exports<'charlatan'>;
}
declare module 'charlatan/index.js' {
  declare module.exports: $Exports<'charlatan'>;
}
declare module 'charlatan/lib/charlatan.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan'>;
}
declare module 'charlatan/lib/charlatan/address.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/address'>;
}
declare module 'charlatan/lib/charlatan/app.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/app'>;
}
declare module 'charlatan/lib/charlatan/avatar.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/avatar'>;
}
declare module 'charlatan/lib/charlatan/bitcoin.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/bitcoin'>;
}
declare module 'charlatan/lib/charlatan/business.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/business'>;
}
declare module 'charlatan/lib/charlatan/code.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/code'>;
}
declare module 'charlatan/lib/charlatan/commerce.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/commerce'>;
}
declare module 'charlatan/lib/charlatan/company.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/company'>;
}
declare module 'charlatan/lib/charlatan/date.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/date'>;
}
declare module 'charlatan/lib/charlatan/finance.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/finance'>;
}
declare module 'charlatan/lib/charlatan/hacker.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/hacker'>;
}
declare module 'charlatan/lib/charlatan/helpers.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/helpers'>;
}
declare module 'charlatan/lib/charlatan/internet.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/internet'>;
}
declare module 'charlatan/lib/charlatan/lorem.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/lorem'>;
}
declare module 'charlatan/lib/charlatan/name.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/name'>;
}
declare module 'charlatan/lib/charlatan/number.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/number'>;
}
declare module 'charlatan/lib/charlatan/phone_number.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/phone_number'>;
}
declare module 'charlatan/lib/charlatan/team.js' {
  declare module.exports: $Exports<'charlatan/lib/charlatan/team'>;
}
declare module 'charlatan/lib/locales_browser.js' {
  declare module.exports: $Exports<'charlatan/lib/locales_browser'>;
}
declare module 'charlatan/lib/locales.js' {
  declare module.exports: $Exports<'charlatan/lib/locales'>;
}
