// flow-typed signature: e487e080062ace6a4943098e8ed00137
// flow-typed version: <<STUB>>/cls-hooked_v^4.2.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cls-hooked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cls-hooked' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cls-hooked/context-legacy' {
  declare module.exports: any;
}

declare module 'cls-hooked/context' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cls-hooked/context-legacy.js' {
  declare module.exports: $Exports<'cls-hooked/context-legacy'>;
}
declare module 'cls-hooked/context.js' {
  declare module.exports: $Exports<'cls-hooked/context'>;
}
declare module 'cls-hooked/index' {
  declare module.exports: $Exports<'cls-hooked'>;
}
declare module 'cls-hooked/index.js' {
  declare module.exports: $Exports<'cls-hooked'>;
}
