/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 8cb6f37b76dc83cf744d1f6fdd5788dc
// flow-typed version: <<STUB>>/date-utils_vlatest/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'date-utils/doc/scripts/bootstrap-dropdown' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/bootstrap-tab' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/docstrap.lib' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/prettify/jquery.min' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/sunlight' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/toc' {
  declare module.exports: any;
}

declare module 'date-utils/doc/scripts/URI' {
  declare module.exports: any;
}

declare module 'date-utils/gulpfile' {
  declare module.exports: any;
}

declare module 'date-utils/lib/date-utils' {
  declare module.exports: any;
}

declare module 'date-utils/lib/date-utils.min' {
  declare module.exports: any;
}

declare module 'date-utils/test/date-format-test' {
  declare module.exports: any;
}

declare module 'date-utils/test/date-language-dos-test' {
  declare module.exports: any;
}

declare module 'date-utils/test/date-language-pt-br-test' {
  declare module.exports: any;
}

declare module 'date-utils/test/date-language-test' {
  declare module.exports: any;
}

declare module 'date-utils/test/date-new-test' {
  declare module.exports: any;
}

declare module 'date-utils/test/date-parse-test' {
  declare module.exports: any;
}

declare module 'date-utils/test/date-validate-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'date-utils/doc/scripts/bootstrap-dropdown.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/bootstrap-dropdown'>;
}
declare module 'date-utils/doc/scripts/bootstrap-tab.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/bootstrap-tab'>;
}
declare module 'date-utils/doc/scripts/docstrap.lib.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/docstrap.lib'>;
}
declare module 'date-utils/doc/scripts/linenumber.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/linenumber'>;
}
declare module 'date-utils/doc/scripts/prettify/jquery.min.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/prettify/jquery.min'>;
}
declare module 'date-utils/doc/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/prettify/lang-css'>;
}
declare module 'date-utils/doc/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/prettify/prettify'>;
}
declare module 'date-utils/doc/scripts/sunlight.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/sunlight'>;
}
declare module 'date-utils/doc/scripts/toc.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/toc'>;
}
declare module 'date-utils/doc/scripts/URI.js' {
  declare module.exports: $Exports<'date-utils/doc/scripts/URI'>;
}
declare module 'date-utils/gulpfile.js' {
  declare module.exports: $Exports<'date-utils/gulpfile'>;
}
declare module 'date-utils/lib/date-utils.js' {
  declare module.exports: $Exports<'date-utils/lib/date-utils'>;
}
declare module 'date-utils/lib/date-utils.min.js' {
  declare module.exports: $Exports<'date-utils/lib/date-utils.min'>;
}
declare module 'date-utils/test/date-format-test.js' {
  declare module.exports: $Exports<'date-utils/test/date-format-test'>;
}
declare module 'date-utils/test/date-language-dos-test.js' {
  declare module.exports: $Exports<'date-utils/test/date-language-dos-test'>;
}
declare module 'date-utils/test/date-language-pt-br-test.js' {
  declare module.exports: $Exports<'date-utils/test/date-language-pt-br-test'>;
}
declare module 'date-utils/test/date-language-test.js' {
  declare module.exports: $Exports<'date-utils/test/date-language-test'>;
}
declare module 'date-utils/test/date-new-test.js' {
  declare module.exports: $Exports<'date-utils/test/date-new-test'>;
}
declare module 'date-utils/test/date-parse-test.js' {
  declare module.exports: $Exports<'date-utils/test/date-parse-test'>;
}
declare module 'date-utils/test/date-validate-test.js' {
  declare module.exports: $Exports<'date-utils/test/date-validate-test'>;
}
