/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 2d2ae72043fa6ed827971a6fe3ffef1d
// flow-typed version: <<STUB>>/dependable_vattentif/dependable#0bb5c4a9ef2b32dded1b24d5d3c0ecccfb0bf7fd/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dependable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dependable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dependable/test/testWhitespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dependable/index' {
  declare module.exports: $Exports<'dependable'>;
}
declare module 'dependable/index.js' {
  declare module.exports: $Exports<'dependable'>;
}
declare module 'dependable/test/testWhitespace.js' {
  declare module.exports: $Exports<'dependable/test/testWhitespace'>;
}
