/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 6a691ffdac9fb9ab78c4a39ec08bd724
// flow-typed version: <<STUB>>/errors_vfile:components/errors/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'errors/src/APIError' {
  declare module.exports: any;
}

declare module 'errors/src/errorHandling' {
  declare module.exports: any;
}

declare module 'errors/src/ErrorIds' {
  declare module.exports: any;
}

declare module 'errors/src/factory' {
  declare module.exports: any;
}

declare module 'errors/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'errors/src/APIError.js' {
  declare module.exports: $Exports<'errors/src/APIError'>;
}
declare module 'errors/src/errorHandling.js' {
  declare module.exports: $Exports<'errors/src/errorHandling'>;
}
declare module 'errors/src/ErrorIds.js' {
  declare module.exports: $Exports<'errors/src/ErrorIds'>;
}
declare module 'errors/src/factory.js' {
  declare module.exports: $Exports<'errors/src/factory'>;
}
declare module 'errors/src/index' {
  declare module.exports: $Exports<'errors/src'>;
}
declare module 'errors/src/index.js' {
  declare module.exports: $Exports<'errors/src'>;
}
