// flow-typed signature: 122aead927071cd7ef6101d3f3f5d1f6
// flow-typed version: <<STUB>>/fs-xattr_v^0.3.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-xattr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-xattr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fs-xattr/index' {
  declare module.exports: $Exports<'fs-xattr'>;
}
declare module 'fs-xattr/index.js' {
  declare module.exports: $Exports<'fs-xattr'>;
}
