// flow-typed signature: 7c2883f75c7e5d411dde2caf6c6bd697
// flow-typed version: <<STUB>>/hfs-server_vfile:components/hfs-server/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hfs-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hfs-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hfs-server/src/application' {
  declare module.exports: any;
}

declare module 'hfs-server/src/config' {
  declare module.exports: any;
}

declare module 'hfs-server/src/context' {
  declare module.exports: any;
}

declare module 'hfs-server/src/metadata_cache' {
  declare module.exports: any;
}

declare module 'hfs-server/src/metadata_updater' {
  declare module.exports: any;
}

declare module 'hfs-server/src/middleware/errors' {
  declare module.exports: any;
}

declare module 'hfs-server/src/server' {
  declare module.exports: any;
}

declare module 'hfs-server/src/Settings' {
  declare module.exports: any;
}

declare module 'hfs-server/src/tracing/cls' {
  declare module.exports: any;
}

declare module 'hfs-server/src/tracing/middleware/clsWrap' {
  declare module.exports: any;
}

declare module 'hfs-server/src/tracing/middleware/trace' {
  declare module.exports: any;
}

declare module 'hfs-server/src/tracing/mongodb_client' {
  declare module.exports: any;
}

declare module 'hfs-server/src/web/api_constants' {
  declare module.exports: any;
}

declare module 'hfs-server/src/web/controller' {
  declare module.exports: any;
}

declare module 'hfs-server/src/web/op/query_series_data' {
  declare module.exports: any;
}

declare module 'hfs-server/src/web/op/store_series_batch' {
  declare module.exports: any;
}

declare module 'hfs-server/src/web/op/store_series_data' {
  declare module.exports: any;
}

declare module 'hfs-server/src/web/op/traced_operations' {
  declare module.exports: any;
}

declare module 'hfs-server/src/web/SeriesResponse' {
  declare module.exports: any;
}

declare module 'hfs-server/test/acceptance/batch.test' {
  declare module.exports: any;
}

declare module 'hfs-server/test/acceptance/query_data.test' {
  declare module.exports: any;
}

declare module 'hfs-server/test/acceptance/store_data.test' {
  declare module.exports: any;
}

declare module 'hfs-server/test/acceptance/test-helpers' {
  declare module.exports: any;
}

declare module 'hfs-server/test/acceptance/verify_authentication.test' {
  declare module.exports: any;
}

declare module 'hfs-server/test/support/child_process' {
  declare module.exports: any;
}

declare module 'hfs-server/test/test-helpers' {
  declare module.exports: any;
}

declare module 'hfs-server/test/unit/server.test' {
  declare module.exports: any;
}

declare module 'hfs-server/test/unit/Settings.test' {
  declare module.exports: any;
}

declare module 'hfs-server/test/unit/test-helpers' {
  declare module.exports: any;
}

declare module 'hfs-server/test/unit/web/controller.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hfs-server/src/application.js' {
  declare module.exports: $Exports<'hfs-server/src/application'>;
}
declare module 'hfs-server/src/config.js' {
  declare module.exports: $Exports<'hfs-server/src/config'>;
}
declare module 'hfs-server/src/context.js' {
  declare module.exports: $Exports<'hfs-server/src/context'>;
}
declare module 'hfs-server/src/metadata_cache.js' {
  declare module.exports: $Exports<'hfs-server/src/metadata_cache'>;
}
declare module 'hfs-server/src/metadata_updater.js' {
  declare module.exports: $Exports<'hfs-server/src/metadata_updater'>;
}
declare module 'hfs-server/src/middleware/errors.js' {
  declare module.exports: $Exports<'hfs-server/src/middleware/errors'>;
}
declare module 'hfs-server/src/server.js' {
  declare module.exports: $Exports<'hfs-server/src/server'>;
}
declare module 'hfs-server/src/Settings.js' {
  declare module.exports: $Exports<'hfs-server/src/Settings'>;
}
declare module 'hfs-server/src/tracing/cls.js' {
  declare module.exports: $Exports<'hfs-server/src/tracing/cls'>;
}
declare module 'hfs-server/src/tracing/middleware/clsWrap.js' {
  declare module.exports: $Exports<'hfs-server/src/tracing/middleware/clsWrap'>;
}
declare module 'hfs-server/src/tracing/middleware/trace.js' {
  declare module.exports: $Exports<'hfs-server/src/tracing/middleware/trace'>;
}
declare module 'hfs-server/src/tracing/mongodb_client.js' {
  declare module.exports: $Exports<'hfs-server/src/tracing/mongodb_client'>;
}
declare module 'hfs-server/src/web/api_constants.js' {
  declare module.exports: $Exports<'hfs-server/src/web/api_constants'>;
}
declare module 'hfs-server/src/web/controller.js' {
  declare module.exports: $Exports<'hfs-server/src/web/controller'>;
}
declare module 'hfs-server/src/web/op/query_series_data.js' {
  declare module.exports: $Exports<'hfs-server/src/web/op/query_series_data'>;
}
declare module 'hfs-server/src/web/op/store_series_batch.js' {
  declare module.exports: $Exports<'hfs-server/src/web/op/store_series_batch'>;
}
declare module 'hfs-server/src/web/op/store_series_data.js' {
  declare module.exports: $Exports<'hfs-server/src/web/op/store_series_data'>;
}
declare module 'hfs-server/src/web/op/traced_operations.js' {
  declare module.exports: $Exports<'hfs-server/src/web/op/traced_operations'>;
}
declare module 'hfs-server/src/web/SeriesResponse.js' {
  declare module.exports: $Exports<'hfs-server/src/web/SeriesResponse'>;
}
declare module 'hfs-server/test/acceptance/batch.test.js' {
  declare module.exports: $Exports<'hfs-server/test/acceptance/batch.test'>;
}
declare module 'hfs-server/test/acceptance/query_data.test.js' {
  declare module.exports: $Exports<'hfs-server/test/acceptance/query_data.test'>;
}
declare module 'hfs-server/test/acceptance/store_data.test.js' {
  declare module.exports: $Exports<'hfs-server/test/acceptance/store_data.test'>;
}
declare module 'hfs-server/test/acceptance/test-helpers.js' {
  declare module.exports: $Exports<'hfs-server/test/acceptance/test-helpers'>;
}
declare module 'hfs-server/test/acceptance/verify_authentication.test.js' {
  declare module.exports: $Exports<'hfs-server/test/acceptance/verify_authentication.test'>;
}
declare module 'hfs-server/test/support/child_process.js' {
  declare module.exports: $Exports<'hfs-server/test/support/child_process'>;
}
declare module 'hfs-server/test/test-helpers.js' {
  declare module.exports: $Exports<'hfs-server/test/test-helpers'>;
}
declare module 'hfs-server/test/unit/server.test.js' {
  declare module.exports: $Exports<'hfs-server/test/unit/server.test'>;
}
declare module 'hfs-server/test/unit/Settings.test.js' {
  declare module.exports: $Exports<'hfs-server/test/unit/Settings.test'>;
}
declare module 'hfs-server/test/unit/test-helpers.js' {
  declare module.exports: $Exports<'hfs-server/test/unit/test-helpers'>;
}
declare module 'hfs-server/test/unit/web/controller.test.js' {
  declare module.exports: $Exports<'hfs-server/test/unit/web/controller.test'>;
}
