// flow-typed signature: cd91a81fd94cb31e091cba01a235d867
// flow-typed version: <<STUB>>/hfs-server_vfile:source/hfs-server/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hfs-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hfs-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hfs-server/src/promisify' {
  declare module.exports: any;
}

declare module 'hfs-server/src/server' {
  declare module.exports: any;
}

declare module 'hfs-server/src/Settings' {
  declare module.exports: any;
}

declare module 'hfs-server/test/unit/server.test' {
  declare module.exports: any;
}

declare module 'hfs-server/test/unit/Settings.test' {
  declare module.exports: any;
}

declare module 'hfs-server/test/unit/test-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hfs-server/src/promisify.js' {
  declare module.exports: $Exports<'hfs-server/src/promisify'>;
}
declare module 'hfs-server/src/server.js' {
  declare module.exports: $Exports<'hfs-server/src/server'>;
}
declare module 'hfs-server/src/Settings.js' {
  declare module.exports: $Exports<'hfs-server/src/Settings'>;
}
declare module 'hfs-server/test/unit/server.test.js' {
  declare module.exports: $Exports<'hfs-server/test/unit/server.test'>;
}
declare module 'hfs-server/test/unit/Settings.test.js' {
  declare module.exports: $Exports<'hfs-server/test/unit/Settings.test'>;
}
declare module 'hfs-server/test/unit/test-helpers.js' {
  declare module.exports: $Exports<'hfs-server/test/unit/test-helpers'>;
}
