/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 28bcac3a0cfe0849cd317713d9e3bbb7
// flow-typed version: <<STUB>>/hjson_v^3.1.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hjson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hjson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hjson/bundle/hjson' {
  declare module.exports: any;
}

declare module 'hjson/bundle/hjson.min' {
  declare module.exports: any;
}

declare module 'hjson/lib/hjson-comments' {
  declare module.exports: any;
}

declare module 'hjson/lib/hjson-common' {
  declare module.exports: any;
}

declare module 'hjson/lib/hjson-dsf' {
  declare module.exports: any;
}

declare module 'hjson/lib/hjson-parse' {
  declare module.exports: any;
}

declare module 'hjson/lib/hjson-stringify' {
  declare module.exports: any;
}

declare module 'hjson/lib/hjson-version' {
  declare module.exports: any;
}

declare module 'hjson/lib/hjson' {
  declare module.exports: any;
}

declare module 'hjson/lib/require-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hjson/bundle/hjson.js' {
  declare module.exports: $Exports<'hjson/bundle/hjson'>;
}
declare module 'hjson/bundle/hjson.min.js' {
  declare module.exports: $Exports<'hjson/bundle/hjson.min'>;
}
declare module 'hjson/lib/hjson-comments.js' {
  declare module.exports: $Exports<'hjson/lib/hjson-comments'>;
}
declare module 'hjson/lib/hjson-common.js' {
  declare module.exports: $Exports<'hjson/lib/hjson-common'>;
}
declare module 'hjson/lib/hjson-dsf.js' {
  declare module.exports: $Exports<'hjson/lib/hjson-dsf'>;
}
declare module 'hjson/lib/hjson-parse.js' {
  declare module.exports: $Exports<'hjson/lib/hjson-parse'>;
}
declare module 'hjson/lib/hjson-stringify.js' {
  declare module.exports: $Exports<'hjson/lib/hjson-stringify'>;
}
declare module 'hjson/lib/hjson-version.js' {
  declare module.exports: $Exports<'hjson/lib/hjson-version'>;
}
declare module 'hjson/lib/hjson.js' {
  declare module.exports: $Exports<'hjson/lib/hjson'>;
}
declare module 'hjson/lib/require-config.js' {
  declare module.exports: $Exports<'hjson/lib/require-config'>;
}
