// flow-typed signature: 72fdb2058b21125b31e59ad82c8ae7ea
// flow-typed version: <<STUB>>/influx_v^5.0.6/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'influx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'influx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'influx/lib/src/backoff/backoff' {
  declare module.exports: any;
}

declare module 'influx/lib/src/backoff/exponential' {
  declare module.exports: any;
}

declare module 'influx/lib/src/builder' {
  declare module.exports: any;
}

declare module 'influx/lib/src/doc' {
  declare module.exports: any;
}

declare module 'influx/lib/src/grammar/ds' {
  declare module.exports: any;
}

declare module 'influx/lib/src/grammar/escape' {
  declare module.exports: any;
}

declare module 'influx/lib/src/grammar/index' {
  declare module.exports: any;
}

declare module 'influx/lib/src/grammar/times' {
  declare module.exports: any;
}

declare module 'influx/lib/src/host' {
  declare module.exports: any;
}

declare module 'influx/lib/src/index' {
  declare module.exports: any;
}

declare module 'influx/lib/src/pool' {
  declare module.exports: any;
}

declare module 'influx/lib/src/results' {
  declare module.exports: any;
}

declare module 'influx/lib/src/schema' {
  declare module.exports: any;
}

// Filename aliases
declare module 'influx/lib/src/backoff/backoff.js' {
  declare module.exports: $Exports<'influx/lib/src/backoff/backoff'>;
}
declare module 'influx/lib/src/backoff/exponential.js' {
  declare module.exports: $Exports<'influx/lib/src/backoff/exponential'>;
}
declare module 'influx/lib/src/builder.js' {
  declare module.exports: $Exports<'influx/lib/src/builder'>;
}
declare module 'influx/lib/src/doc.js' {
  declare module.exports: $Exports<'influx/lib/src/doc'>;
}
declare module 'influx/lib/src/grammar/ds.js' {
  declare module.exports: $Exports<'influx/lib/src/grammar/ds'>;
}
declare module 'influx/lib/src/grammar/escape.js' {
  declare module.exports: $Exports<'influx/lib/src/grammar/escape'>;
}
declare module 'influx/lib/src/grammar/index.js' {
  declare module.exports: $Exports<'influx/lib/src/grammar/index'>;
}
declare module 'influx/lib/src/grammar/times.js' {
  declare module.exports: $Exports<'influx/lib/src/grammar/times'>;
}
declare module 'influx/lib/src/host.js' {
  declare module.exports: $Exports<'influx/lib/src/host'>;
}
declare module 'influx/lib/src/index.js' {
  declare module.exports: $Exports<'influx/lib/src/index'>;
}
declare module 'influx/lib/src/pool.js' {
  declare module.exports: $Exports<'influx/lib/src/pool'>;
}
declare module 'influx/lib/src/results.js' {
  declare module.exports: $Exports<'influx/lib/src/results'>;
}
declare module 'influx/lib/src/schema.js' {
  declare module.exports: $Exports<'influx/lib/src/schema'>;
}
