/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 23595e38a7c71eee4c1f94831719d08a
// flow-typed version: <<STUB>>/inspect_v^0.0.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inspect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inspect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'inspect/index' {
  declare module.exports: $Exports<'inspect'>;
}
declare module 'inspect/index.js' {
  declare module.exports: $Exports<'inspect'>;
}
