/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: b9a262f8522f6a0c278971939238f72d
// flow-typed version: <<STUB>>/jaeger-client_v^3.8.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jaeger-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jaeger-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jaeger-client/dist/src/_flow/baggage_restriction_manager' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/bufrw' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/context' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/crossdock' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/extractor' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/injector' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/jaeger-thrift' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/legacy_sampler_v1' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/logger' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/metrics' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/process_setter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/reporter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/sampler-thrift' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/socket' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/throttler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/_flow/tracer' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/baggage/baggage_setter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/baggage/default_baggage_restriction_manager' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/baggage/restriction' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/configuration_env' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/configuration' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/constants' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/default_context' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/logger' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/metrics/metrics' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/metrics/noop/counter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/metrics/noop/gauge' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/metrics/noop/metric_factory' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/metrics/noop/timer' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/metrics/prometheus' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/propagators/baggage' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/propagators/binary_codec' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/propagators/text_map_codec' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/propagators/zipkin_b3_text_map_codec' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/rate_limiter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/reporters/composite_reporter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/reporters/http_sender' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/reporters/in_memory_reporter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/reporters/logging_reporter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/reporters/noop_reporter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/reporters/remote_reporter' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/reporters/sender_utils' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/reporters/udp_sender' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/_adapt_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/const_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/constants' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/experimental/priority_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/experimental/tag_equals_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/guaranteed_throughput_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/per_operation_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/probabilistic_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/rate_limiting_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/remote_sampler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/v2/base' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/samplers/v2/sampling_state' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/span_context' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/span' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/tchannel_bridge' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/test_util' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/thrift' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/throttler/default_throttler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/throttler/remote_throttler' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/tracer' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/util' {
  declare module.exports: any;
}

declare module 'jaeger-client/dist/src/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jaeger-client/dist/src/_flow/baggage_restriction_manager.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/baggage_restriction_manager'>;
}
declare module 'jaeger-client/dist/src/_flow/bufrw.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/bufrw'>;
}
declare module 'jaeger-client/dist/src/_flow/context.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/context'>;
}
declare module 'jaeger-client/dist/src/_flow/crossdock.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/crossdock'>;
}
declare module 'jaeger-client/dist/src/_flow/extractor.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/extractor'>;
}
declare module 'jaeger-client/dist/src/_flow/injector.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/injector'>;
}
declare module 'jaeger-client/dist/src/_flow/jaeger-thrift.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/jaeger-thrift'>;
}
declare module 'jaeger-client/dist/src/_flow/legacy_sampler_v1.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/legacy_sampler_v1'>;
}
declare module 'jaeger-client/dist/src/_flow/logger.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/logger'>;
}
declare module 'jaeger-client/dist/src/_flow/metrics.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/metrics'>;
}
declare module 'jaeger-client/dist/src/_flow/process_setter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/process_setter'>;
}
declare module 'jaeger-client/dist/src/_flow/reporter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/reporter'>;
}
declare module 'jaeger-client/dist/src/_flow/sampler-thrift.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/sampler-thrift'>;
}
declare module 'jaeger-client/dist/src/_flow/sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/sampler'>;
}
declare module 'jaeger-client/dist/src/_flow/socket.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/socket'>;
}
declare module 'jaeger-client/dist/src/_flow/throttler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/throttler'>;
}
declare module 'jaeger-client/dist/src/_flow/tracer.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/_flow/tracer'>;
}
declare module 'jaeger-client/dist/src/baggage/baggage_setter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/baggage/baggage_setter'>;
}
declare module 'jaeger-client/dist/src/baggage/default_baggage_restriction_manager.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/baggage/default_baggage_restriction_manager'>;
}
declare module 'jaeger-client/dist/src/baggage/restriction.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/baggage/restriction'>;
}
declare module 'jaeger-client/dist/src/configuration_env.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/configuration_env'>;
}
declare module 'jaeger-client/dist/src/configuration.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/configuration'>;
}
declare module 'jaeger-client/dist/src/constants.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/constants'>;
}
declare module 'jaeger-client/dist/src/default_context.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/default_context'>;
}
declare module 'jaeger-client/dist/src/index' {
  declare module.exports: $Exports<'jaeger-client/dist/src'>;
}
declare module 'jaeger-client/dist/src/index.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src'>;
}
declare module 'jaeger-client/dist/src/logger.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/logger'>;
}
declare module 'jaeger-client/dist/src/metrics/metrics.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/metrics/metrics'>;
}
declare module 'jaeger-client/dist/src/metrics/noop/counter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/metrics/noop/counter'>;
}
declare module 'jaeger-client/dist/src/metrics/noop/gauge.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/metrics/noop/gauge'>;
}
declare module 'jaeger-client/dist/src/metrics/noop/metric_factory.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/metrics/noop/metric_factory'>;
}
declare module 'jaeger-client/dist/src/metrics/noop/timer.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/metrics/noop/timer'>;
}
declare module 'jaeger-client/dist/src/metrics/prometheus.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/metrics/prometheus'>;
}
declare module 'jaeger-client/dist/src/propagators/baggage.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/propagators/baggage'>;
}
declare module 'jaeger-client/dist/src/propagators/binary_codec.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/propagators/binary_codec'>;
}
declare module 'jaeger-client/dist/src/propagators/text_map_codec.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/propagators/text_map_codec'>;
}
declare module 'jaeger-client/dist/src/propagators/zipkin_b3_text_map_codec.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/propagators/zipkin_b3_text_map_codec'>;
}
declare module 'jaeger-client/dist/src/rate_limiter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/rate_limiter'>;
}
declare module 'jaeger-client/dist/src/reporters/composite_reporter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/reporters/composite_reporter'>;
}
declare module 'jaeger-client/dist/src/reporters/http_sender.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/reporters/http_sender'>;
}
declare module 'jaeger-client/dist/src/reporters/in_memory_reporter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/reporters/in_memory_reporter'>;
}
declare module 'jaeger-client/dist/src/reporters/logging_reporter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/reporters/logging_reporter'>;
}
declare module 'jaeger-client/dist/src/reporters/noop_reporter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/reporters/noop_reporter'>;
}
declare module 'jaeger-client/dist/src/reporters/remote_reporter.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/reporters/remote_reporter'>;
}
declare module 'jaeger-client/dist/src/reporters/sender_utils.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/reporters/sender_utils'>;
}
declare module 'jaeger-client/dist/src/reporters/udp_sender.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/reporters/udp_sender'>;
}
declare module 'jaeger-client/dist/src/samplers/_adapt_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/_adapt_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/const_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/const_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/constants.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/constants'>;
}
declare module 'jaeger-client/dist/src/samplers/experimental/priority_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/experimental/priority_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/experimental/tag_equals_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/experimental/tag_equals_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/guaranteed_throughput_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/guaranteed_throughput_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/per_operation_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/per_operation_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/probabilistic_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/probabilistic_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/rate_limiting_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/rate_limiting_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/remote_sampler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/remote_sampler'>;
}
declare module 'jaeger-client/dist/src/samplers/v2/base.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/v2/base'>;
}
declare module 'jaeger-client/dist/src/samplers/v2/sampling_state.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/samplers/v2/sampling_state'>;
}
declare module 'jaeger-client/dist/src/span_context.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/span_context'>;
}
declare module 'jaeger-client/dist/src/span.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/span'>;
}
declare module 'jaeger-client/dist/src/tchannel_bridge.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/tchannel_bridge'>;
}
declare module 'jaeger-client/dist/src/test_util.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/test_util'>;
}
declare module 'jaeger-client/dist/src/thrift.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/thrift'>;
}
declare module 'jaeger-client/dist/src/throttler/default_throttler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/throttler/default_throttler'>;
}
declare module 'jaeger-client/dist/src/throttler/remote_throttler.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/throttler/remote_throttler'>;
}
declare module 'jaeger-client/dist/src/tracer.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/tracer'>;
}
declare module 'jaeger-client/dist/src/util.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/util'>;
}
declare module 'jaeger-client/dist/src/version.js' {
  declare module.exports: $Exports<'jaeger-client/dist/src/version'>;
}
