/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 52e4ad64906000ce84b79f0116fcbc1a
// flow-typed version: <<STUB>>/jsdoc-babel_v^0.3.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc-babel/lib' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc-babel/lib/index' {
  declare module.exports: $Exports<'jsdoc-babel/lib'>;
}
declare module 'jsdoc-babel/lib/index.js' {
  declare module.exports: $Exports<'jsdoc-babel/lib'>;
}
declare module 'jsdoc-babel/src/index' {
  declare module.exports: $Exports<'jsdoc-babel/src'>;
}
declare module 'jsdoc-babel/src/index.js' {
  declare module.exports: $Exports<'jsdoc-babel/src'>;
}
