// flow-typed signature: e93bb81ff3ea7921f99b9f9f85fb5d7d
// flow-typed version: <<STUB>>/lib-reporting_vgit+ssh://git@github.com/pryv/lib-reporting/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lib-reporting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lib-reporting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lib-reporting/src' {
  declare module.exports: any;
}

declare module 'lib-reporting/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lib-reporting/src/index' {
  declare module.exports: $Exports<'lib-reporting/src'>;
}
declare module 'lib-reporting/src/index.js' {
  declare module.exports: $Exports<'lib-reporting/src'>;
}
declare module 'lib-reporting/test/test.js' {
  declare module.exports: $Exports<'lib-reporting/test/test'>;
}
