// flow-typed signature: 20518cbf99e3fed7044553d74222e13e
// flow-typed version: <<STUB>>/middleware_vfile:source/middleware/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'middleware/src/attachmentsAccess' {
  declare module.exports: any;
}

declare module 'middleware/src/commonHeaders' {
  declare module.exports: any;
}

declare module 'middleware/src/contentType' {
  declare module.exports: any;
}

declare module 'middleware/src/filesUploadSupport' {
  declare module.exports: any;
}

declare module 'middleware/src/index' {
  declare module.exports: any;
}

declare module 'middleware/src/initContext' {
  declare module.exports: any;
}

declare module 'middleware/src/notFound' {
  declare module.exports: any;
}

declare module 'middleware/src/override' {
  declare module.exports: any;
}

declare module 'middleware/src/requestTrace' {
  declare module.exports: any;
}

declare module 'middleware/src/subdomainToPath' {
  declare module.exports: any;
}

// Filename aliases
declare module 'middleware/src/attachmentsAccess.js' {
  declare module.exports: $Exports<'middleware/src/attachmentsAccess'>;
}
declare module 'middleware/src/commonHeaders.js' {
  declare module.exports: $Exports<'middleware/src/commonHeaders'>;
}
declare module 'middleware/src/contentType.js' {
  declare module.exports: $Exports<'middleware/src/contentType'>;
}
declare module 'middleware/src/filesUploadSupport.js' {
  declare module.exports: $Exports<'middleware/src/filesUploadSupport'>;
}
declare module 'middleware/src/index.js' {
  declare module.exports: $Exports<'middleware/src/index'>;
}
declare module 'middleware/src/initContext.js' {
  declare module.exports: $Exports<'middleware/src/initContext'>;
}
declare module 'middleware/src/notFound.js' {
  declare module.exports: $Exports<'middleware/src/notFound'>;
}
declare module 'middleware/src/override.js' {
  declare module.exports: $Exports<'middleware/src/override'>;
}
declare module 'middleware/src/requestTrace.js' {
  declare module.exports: $Exports<'middleware/src/requestTrace'>;
}
declare module 'middleware/src/subdomainToPath.js' {
  declare module.exports: $Exports<'middleware/src/subdomainToPath'>;
}
