/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: ff94059a27b31dfa122ed89852935a85
// flow-typed version: <<STUB>>/middleware_vfile:components/middleware/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'middleware/src/commonHeaders' {
  declare module.exports: any;
}

declare module 'middleware/src/contentType' {
  declare module.exports: any;
}

declare module 'middleware/src/filesUploadSupport' {
  declare module.exports: any;
}

declare module 'middleware/src/getAuth' {
  declare module.exports: any;
}

declare module 'middleware/src' {
  declare module.exports: any;
}

declare module 'middleware/src/initContext' {
  declare module.exports: any;
}

declare module 'middleware/src/loadAccess' {
  declare module.exports: any;
}

declare module 'middleware/src/notFound' {
  declare module.exports: any;
}

declare module 'middleware/src/override' {
  declare module.exports: any;
}

declare module 'middleware/src/project_version' {
  declare module.exports: any;
}

declare module 'middleware/src/requestTrace' {
  declare module.exports: any;
}

declare module 'middleware/src/subdomainToPath' {
  declare module.exports: any;
}

declare module 'middleware/test/unit/loadAccess.test' {
  declare module.exports: any;
}

declare module 'middleware/test/unit/project_version.test' {
  declare module.exports: any;
}

declare module 'middleware/test/unit/subdomainToPath.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'middleware/src/commonHeaders.js' {
  declare module.exports: $Exports<'middleware/src/commonHeaders'>;
}
declare module 'middleware/src/contentType.js' {
  declare module.exports: $Exports<'middleware/src/contentType'>;
}
declare module 'middleware/src/filesUploadSupport.js' {
  declare module.exports: $Exports<'middleware/src/filesUploadSupport'>;
}
declare module 'middleware/src/getAuth.js' {
  declare module.exports: $Exports<'middleware/src/getAuth'>;
}
declare module 'middleware/src/index' {
  declare module.exports: $Exports<'middleware/src'>;
}
declare module 'middleware/src/index.js' {
  declare module.exports: $Exports<'middleware/src'>;
}
declare module 'middleware/src/initContext.js' {
  declare module.exports: $Exports<'middleware/src/initContext'>;
}
declare module 'middleware/src/loadAccess.js' {
  declare module.exports: $Exports<'middleware/src/loadAccess'>;
}
declare module 'middleware/src/notFound.js' {
  declare module.exports: $Exports<'middleware/src/notFound'>;
}
declare module 'middleware/src/override.js' {
  declare module.exports: $Exports<'middleware/src/override'>;
}
declare module 'middleware/src/project_version.js' {
  declare module.exports: $Exports<'middleware/src/project_version'>;
}
declare module 'middleware/src/requestTrace.js' {
  declare module.exports: $Exports<'middleware/src/requestTrace'>;
}
declare module 'middleware/src/subdomainToPath.js' {
  declare module.exports: $Exports<'middleware/src/subdomainToPath'>;
}
declare module 'middleware/test/unit/loadAccess.test.js' {
  declare module.exports: $Exports<'middleware/test/unit/loadAccess.test'>;
}
declare module 'middleware/test/unit/project_version.test.js' {
  declare module.exports: $Exports<'middleware/test/unit/project_version.test'>;
}
declare module 'middleware/test/unit/subdomainToPath.test.js' {
  declare module.exports: $Exports<'middleware/test/unit/subdomainToPath.test'>;
}
