/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: c5922cf18b556ff555416835c9a9dc76
// flow-typed version: <<STUB>>/model_vfile:components/model/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'model'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'model' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'model/src/accessLogic' {
  declare module.exports: any;
}

declare module 'model/src' {
  declare module.exports: any;
}

declare module 'model/src/MethodContext' {
  declare module.exports: any;
}

declare module 'model/test/unit/method_context.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'model/src/accessLogic.js' {
  declare module.exports: $Exports<'model/src/accessLogic'>;
}
declare module 'model/src/index' {
  declare module.exports: $Exports<'model/src'>;
}
declare module 'model/src/index.js' {
  declare module.exports: $Exports<'model/src'>;
}
declare module 'model/src/MethodContext.js' {
  declare module.exports: $Exports<'model/src/MethodContext'>;
}
declare module 'model/test/unit/method_context.test.js' {
  declare module.exports: $Exports<'model/test/unit/method_context.test'>;
}
