// flow-typed signature: 77b241ac34fa52174d675d56fe26b0af
// flow-typed version: <<STUB>>/mongodb-core_v^3.2.7/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongodb-core/lib/auth/auth_provider' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/auth/defaultAuthProviders' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/auth/gssapi' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/auth/mongo_credentials' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/auth/mongocr' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/auth/plain' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/auth/scram' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/auth/sspi' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/auth/x509' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/apm' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/command_result' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/commands' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/connect' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/connection' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/logger' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/msg' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/pool' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/connection/utils' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/cursor' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/error' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/sdam/monitoring' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/sdam/server_description' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/sdam/server_selectors' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/sdam/server' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/sdam/topology_description' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/sdam/topology' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/sessions' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/tools/smoke_plugin' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/topologies/mongos' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/topologies/read_preference' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/topologies/replset_state' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/topologies/replset' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/topologies/server' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/topologies/shared' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/transactions' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/uri_parser' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/utils' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol/command' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol/compression' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol/constants' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol/get_more' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol/kill_cursors' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol/query' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol/shared' {
  declare module.exports: any;
}

declare module 'mongodb-core/lib/wireprotocol/write_command' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongodb-core/index' {
  declare module.exports: $Exports<'mongodb-core'>;
}
declare module 'mongodb-core/index.js' {
  declare module.exports: $Exports<'mongodb-core'>;
}
declare module 'mongodb-core/lib/auth/auth_provider.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/auth_provider'>;
}
declare module 'mongodb-core/lib/auth/defaultAuthProviders.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/defaultAuthProviders'>;
}
declare module 'mongodb-core/lib/auth/gssapi.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/gssapi'>;
}
declare module 'mongodb-core/lib/auth/mongo_credentials.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/mongo_credentials'>;
}
declare module 'mongodb-core/lib/auth/mongocr.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/mongocr'>;
}
declare module 'mongodb-core/lib/auth/plain.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/plain'>;
}
declare module 'mongodb-core/lib/auth/scram.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/scram'>;
}
declare module 'mongodb-core/lib/auth/sspi.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/sspi'>;
}
declare module 'mongodb-core/lib/auth/x509.js' {
  declare module.exports: $Exports<'mongodb-core/lib/auth/x509'>;
}
declare module 'mongodb-core/lib/connection/apm.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/apm'>;
}
declare module 'mongodb-core/lib/connection/command_result.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/command_result'>;
}
declare module 'mongodb-core/lib/connection/commands.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/commands'>;
}
declare module 'mongodb-core/lib/connection/connect.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/connect'>;
}
declare module 'mongodb-core/lib/connection/connection.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/connection'>;
}
declare module 'mongodb-core/lib/connection/logger.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/logger'>;
}
declare module 'mongodb-core/lib/connection/msg.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/msg'>;
}
declare module 'mongodb-core/lib/connection/pool.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/pool'>;
}
declare module 'mongodb-core/lib/connection/utils.js' {
  declare module.exports: $Exports<'mongodb-core/lib/connection/utils'>;
}
declare module 'mongodb-core/lib/cursor.js' {
  declare module.exports: $Exports<'mongodb-core/lib/cursor'>;
}
declare module 'mongodb-core/lib/error.js' {
  declare module.exports: $Exports<'mongodb-core/lib/error'>;
}
declare module 'mongodb-core/lib/sdam/monitoring.js' {
  declare module.exports: $Exports<'mongodb-core/lib/sdam/monitoring'>;
}
declare module 'mongodb-core/lib/sdam/server_description.js' {
  declare module.exports: $Exports<'mongodb-core/lib/sdam/server_description'>;
}
declare module 'mongodb-core/lib/sdam/server_selectors.js' {
  declare module.exports: $Exports<'mongodb-core/lib/sdam/server_selectors'>;
}
declare module 'mongodb-core/lib/sdam/server.js' {
  declare module.exports: $Exports<'mongodb-core/lib/sdam/server'>;
}
declare module 'mongodb-core/lib/sdam/topology_description.js' {
  declare module.exports: $Exports<'mongodb-core/lib/sdam/topology_description'>;
}
declare module 'mongodb-core/lib/sdam/topology.js' {
  declare module.exports: $Exports<'mongodb-core/lib/sdam/topology'>;
}
declare module 'mongodb-core/lib/sessions.js' {
  declare module.exports: $Exports<'mongodb-core/lib/sessions'>;
}
declare module 'mongodb-core/lib/tools/smoke_plugin.js' {
  declare module.exports: $Exports<'mongodb-core/lib/tools/smoke_plugin'>;
}
declare module 'mongodb-core/lib/topologies/mongos.js' {
  declare module.exports: $Exports<'mongodb-core/lib/topologies/mongos'>;
}
declare module 'mongodb-core/lib/topologies/read_preference.js' {
  declare module.exports: $Exports<'mongodb-core/lib/topologies/read_preference'>;
}
declare module 'mongodb-core/lib/topologies/replset_state.js' {
  declare module.exports: $Exports<'mongodb-core/lib/topologies/replset_state'>;
}
declare module 'mongodb-core/lib/topologies/replset.js' {
  declare module.exports: $Exports<'mongodb-core/lib/topologies/replset'>;
}
declare module 'mongodb-core/lib/topologies/server.js' {
  declare module.exports: $Exports<'mongodb-core/lib/topologies/server'>;
}
declare module 'mongodb-core/lib/topologies/shared.js' {
  declare module.exports: $Exports<'mongodb-core/lib/topologies/shared'>;
}
declare module 'mongodb-core/lib/transactions.js' {
  declare module.exports: $Exports<'mongodb-core/lib/transactions'>;
}
declare module 'mongodb-core/lib/uri_parser.js' {
  declare module.exports: $Exports<'mongodb-core/lib/uri_parser'>;
}
declare module 'mongodb-core/lib/utils.js' {
  declare module.exports: $Exports<'mongodb-core/lib/utils'>;
}
declare module 'mongodb-core/lib/wireprotocol/command.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol/command'>;
}
declare module 'mongodb-core/lib/wireprotocol/compression.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol/compression'>;
}
declare module 'mongodb-core/lib/wireprotocol/constants.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol/constants'>;
}
declare module 'mongodb-core/lib/wireprotocol/get_more.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol/get_more'>;
}
declare module 'mongodb-core/lib/wireprotocol/index' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol'>;
}
declare module 'mongodb-core/lib/wireprotocol/index.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol'>;
}
declare module 'mongodb-core/lib/wireprotocol/kill_cursors.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol/kill_cursors'>;
}
declare module 'mongodb-core/lib/wireprotocol/query.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol/query'>;
}
declare module 'mongodb-core/lib/wireprotocol/shared.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol/shared'>;
}
declare module 'mongodb-core/lib/wireprotocol/write_command.js' {
  declare module.exports: $Exports<'mongodb-core/lib/wireprotocol/write_command'>;
}
