// flow-typed signature: 36e731fab6a5154cdbf96dff2266f81b
// flow-typed version: <<STUB>>/msgpack5_v^6.0.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'msgpack5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'msgpack5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'msgpack5/benchmarks/encodedecode' {
  declare module.exports: any;
}

declare module 'msgpack5/benchmarks/parseshortmap' {
  declare module.exports: any;
}

declare module 'msgpack5/dist/msgpack5' {
  declare module.exports: any;
}

declare module 'msgpack5/dist/msgpack5.min' {
  declare module.exports: any;
}

declare module 'msgpack5/example' {
  declare module.exports: any;
}

declare module 'msgpack5/lib/codecs/DateCodec' {
  declare module.exports: any;
}

declare module 'msgpack5/lib/decoder' {
  declare module.exports: any;
}

declare module 'msgpack5/lib/encoder' {
  declare module.exports: any;
}

declare module 'msgpack5/lib/helpers' {
  declare module.exports: any;
}

declare module 'msgpack5/lib/streams' {
  declare module.exports: any;
}

declare module 'msgpack5/test/1-byte-length-buffers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/1-byte-length-exts' {
  declare module.exports: any;
}

declare module 'msgpack5/test/1-byte-length-strings' {
  declare module.exports: any;
}

declare module 'msgpack5/test/1-byte-length-uint8arrays' {
  declare module.exports: any;
}

declare module 'msgpack5/test/15-elements-arrays' {
  declare module.exports: any;
}

declare module 'msgpack5/test/15-elements-maps' {
  declare module.exports: any;
}

declare module 'msgpack5/test/16-bits-signed-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/16-bits-unsigned-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/2-bytes-length-arrays' {
  declare module.exports: any;
}

declare module 'msgpack5/test/2-bytes-length-buffers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/2-bytes-length-exts' {
  declare module.exports: any;
}

declare module 'msgpack5/test/2-bytes-length-maps' {
  declare module.exports: any;
}

declare module 'msgpack5/test/2-bytes-length-strings' {
  declare module.exports: any;
}

declare module 'msgpack5/test/2-bytes-length-uint8arrays' {
  declare module.exports: any;
}

declare module 'msgpack5/test/31-chars-strings' {
  declare module.exports: any;
}

declare module 'msgpack5/test/32-bits-signed-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/32-bits-unsigned-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/32-bytes-strings' {
  declare module.exports: any;
}

declare module 'msgpack5/test/4-bytes-length-arrays' {
  declare module.exports: any;
}

declare module 'msgpack5/test/4-bytes-length-buffers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/4-bytes-length-exts' {
  declare module.exports: any;
}

declare module 'msgpack5/test/4-bytes-length-strings' {
  declare module.exports: any;
}

declare module 'msgpack5/test/4-bytes-length-uint8arrays' {
  declare module.exports: any;
}

declare module 'msgpack5/test/5-bits-negative-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/64-bits-signed-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/64-bits-unsigned-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/7-bits-positive-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/8-bits-positive-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/8-bits-signed-integers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/booleans' {
  declare module.exports: any;
}

declare module 'msgpack5/test/compatibility-mode' {
  declare module.exports: any;
}

declare module 'msgpack5/test/datenull' {
  declare module.exports: any;
}

declare module 'msgpack5/test/doubles' {
  declare module.exports: any;
}

declare module 'msgpack5/test/ext-custom-encode-check' {
  declare module.exports: any;
}

declare module 'msgpack5/test/fixexts' {
  declare module.exports: any;
}

declare module 'msgpack5/test/floats' {
  declare module.exports: any;
}

declare module 'msgpack5/test/functions' {
  declare module.exports: any;
}

declare module 'msgpack5/test/levelup-encoding' {
  declare module.exports: any;
}

declare module 'msgpack5/test/map-with-object-key' {
  declare module.exports: any;
}

declare module 'msgpack5/test/NaN' {
  declare module.exports: any;
}

declare module 'msgpack5/test/nested-containers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/null' {
  declare module.exports: any;
}

declare module 'msgpack5/test/numerictypeasserts' {
  declare module.exports: any;
}

declare module 'msgpack5/test/object-prototype-poisoning' {
  declare module.exports: any;
}

declare module 'msgpack5/test/object-with-arrays' {
  declare module.exports: any;
}

declare module 'msgpack5/test/object-with-buffers' {
  declare module.exports: any;
}

declare module 'msgpack5/test/object-with-many-keys' {
  declare module.exports: any;
}

declare module 'msgpack5/test/object-with-strings' {
  declare module.exports: any;
}

declare module 'msgpack5/test/prefer-map' {
  declare module.exports: any;
}

declare module 'msgpack5/test/sparse-arrays' {
  declare module.exports: any;
}

declare module 'msgpack5/test/streams' {
  declare module.exports: any;
}

declare module 'msgpack5/test/timestamps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'msgpack5/benchmarks/encodedecode.js' {
  declare module.exports: $Exports<'msgpack5/benchmarks/encodedecode'>;
}
declare module 'msgpack5/benchmarks/parseshortmap.js' {
  declare module.exports: $Exports<'msgpack5/benchmarks/parseshortmap'>;
}
declare module 'msgpack5/dist/msgpack5.js' {
  declare module.exports: $Exports<'msgpack5/dist/msgpack5'>;
}
declare module 'msgpack5/dist/msgpack5.min.js' {
  declare module.exports: $Exports<'msgpack5/dist/msgpack5.min'>;
}
declare module 'msgpack5/example.js' {
  declare module.exports: $Exports<'msgpack5/example'>;
}
declare module 'msgpack5/index' {
  declare module.exports: $Exports<'msgpack5'>;
}
declare module 'msgpack5/index.js' {
  declare module.exports: $Exports<'msgpack5'>;
}
declare module 'msgpack5/lib/codecs/DateCodec.js' {
  declare module.exports: $Exports<'msgpack5/lib/codecs/DateCodec'>;
}
declare module 'msgpack5/lib/decoder.js' {
  declare module.exports: $Exports<'msgpack5/lib/decoder'>;
}
declare module 'msgpack5/lib/encoder.js' {
  declare module.exports: $Exports<'msgpack5/lib/encoder'>;
}
declare module 'msgpack5/lib/helpers.js' {
  declare module.exports: $Exports<'msgpack5/lib/helpers'>;
}
declare module 'msgpack5/lib/streams.js' {
  declare module.exports: $Exports<'msgpack5/lib/streams'>;
}
declare module 'msgpack5/test/1-byte-length-buffers.js' {
  declare module.exports: $Exports<'msgpack5/test/1-byte-length-buffers'>;
}
declare module 'msgpack5/test/1-byte-length-exts.js' {
  declare module.exports: $Exports<'msgpack5/test/1-byte-length-exts'>;
}
declare module 'msgpack5/test/1-byte-length-strings.js' {
  declare module.exports: $Exports<'msgpack5/test/1-byte-length-strings'>;
}
declare module 'msgpack5/test/1-byte-length-uint8arrays.js' {
  declare module.exports: $Exports<'msgpack5/test/1-byte-length-uint8arrays'>;
}
declare module 'msgpack5/test/15-elements-arrays.js' {
  declare module.exports: $Exports<'msgpack5/test/15-elements-arrays'>;
}
declare module 'msgpack5/test/15-elements-maps.js' {
  declare module.exports: $Exports<'msgpack5/test/15-elements-maps'>;
}
declare module 'msgpack5/test/16-bits-signed-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/16-bits-signed-integers'>;
}
declare module 'msgpack5/test/16-bits-unsigned-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/16-bits-unsigned-integers'>;
}
declare module 'msgpack5/test/2-bytes-length-arrays.js' {
  declare module.exports: $Exports<'msgpack5/test/2-bytes-length-arrays'>;
}
declare module 'msgpack5/test/2-bytes-length-buffers.js' {
  declare module.exports: $Exports<'msgpack5/test/2-bytes-length-buffers'>;
}
declare module 'msgpack5/test/2-bytes-length-exts.js' {
  declare module.exports: $Exports<'msgpack5/test/2-bytes-length-exts'>;
}
declare module 'msgpack5/test/2-bytes-length-maps.js' {
  declare module.exports: $Exports<'msgpack5/test/2-bytes-length-maps'>;
}
declare module 'msgpack5/test/2-bytes-length-strings.js' {
  declare module.exports: $Exports<'msgpack5/test/2-bytes-length-strings'>;
}
declare module 'msgpack5/test/2-bytes-length-uint8arrays.js' {
  declare module.exports: $Exports<'msgpack5/test/2-bytes-length-uint8arrays'>;
}
declare module 'msgpack5/test/31-chars-strings.js' {
  declare module.exports: $Exports<'msgpack5/test/31-chars-strings'>;
}
declare module 'msgpack5/test/32-bits-signed-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/32-bits-signed-integers'>;
}
declare module 'msgpack5/test/32-bits-unsigned-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/32-bits-unsigned-integers'>;
}
declare module 'msgpack5/test/32-bytes-strings.js' {
  declare module.exports: $Exports<'msgpack5/test/32-bytes-strings'>;
}
declare module 'msgpack5/test/4-bytes-length-arrays.js' {
  declare module.exports: $Exports<'msgpack5/test/4-bytes-length-arrays'>;
}
declare module 'msgpack5/test/4-bytes-length-buffers.js' {
  declare module.exports: $Exports<'msgpack5/test/4-bytes-length-buffers'>;
}
declare module 'msgpack5/test/4-bytes-length-exts.js' {
  declare module.exports: $Exports<'msgpack5/test/4-bytes-length-exts'>;
}
declare module 'msgpack5/test/4-bytes-length-strings.js' {
  declare module.exports: $Exports<'msgpack5/test/4-bytes-length-strings'>;
}
declare module 'msgpack5/test/4-bytes-length-uint8arrays.js' {
  declare module.exports: $Exports<'msgpack5/test/4-bytes-length-uint8arrays'>;
}
declare module 'msgpack5/test/5-bits-negative-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/5-bits-negative-integers'>;
}
declare module 'msgpack5/test/64-bits-signed-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/64-bits-signed-integers'>;
}
declare module 'msgpack5/test/64-bits-unsigned-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/64-bits-unsigned-integers'>;
}
declare module 'msgpack5/test/7-bits-positive-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/7-bits-positive-integers'>;
}
declare module 'msgpack5/test/8-bits-positive-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/8-bits-positive-integers'>;
}
declare module 'msgpack5/test/8-bits-signed-integers.js' {
  declare module.exports: $Exports<'msgpack5/test/8-bits-signed-integers'>;
}
declare module 'msgpack5/test/booleans.js' {
  declare module.exports: $Exports<'msgpack5/test/booleans'>;
}
declare module 'msgpack5/test/compatibility-mode.js' {
  declare module.exports: $Exports<'msgpack5/test/compatibility-mode'>;
}
declare module 'msgpack5/test/datenull.js' {
  declare module.exports: $Exports<'msgpack5/test/datenull'>;
}
declare module 'msgpack5/test/doubles.js' {
  declare module.exports: $Exports<'msgpack5/test/doubles'>;
}
declare module 'msgpack5/test/ext-custom-encode-check.js' {
  declare module.exports: $Exports<'msgpack5/test/ext-custom-encode-check'>;
}
declare module 'msgpack5/test/fixexts.js' {
  declare module.exports: $Exports<'msgpack5/test/fixexts'>;
}
declare module 'msgpack5/test/floats.js' {
  declare module.exports: $Exports<'msgpack5/test/floats'>;
}
declare module 'msgpack5/test/functions.js' {
  declare module.exports: $Exports<'msgpack5/test/functions'>;
}
declare module 'msgpack5/test/levelup-encoding.js' {
  declare module.exports: $Exports<'msgpack5/test/levelup-encoding'>;
}
declare module 'msgpack5/test/map-with-object-key.js' {
  declare module.exports: $Exports<'msgpack5/test/map-with-object-key'>;
}
declare module 'msgpack5/test/NaN.js' {
  declare module.exports: $Exports<'msgpack5/test/NaN'>;
}
declare module 'msgpack5/test/nested-containers.js' {
  declare module.exports: $Exports<'msgpack5/test/nested-containers'>;
}
declare module 'msgpack5/test/null.js' {
  declare module.exports: $Exports<'msgpack5/test/null'>;
}
declare module 'msgpack5/test/numerictypeasserts.js' {
  declare module.exports: $Exports<'msgpack5/test/numerictypeasserts'>;
}
declare module 'msgpack5/test/object-prototype-poisoning.js' {
  declare module.exports: $Exports<'msgpack5/test/object-prototype-poisoning'>;
}
declare module 'msgpack5/test/object-with-arrays.js' {
  declare module.exports: $Exports<'msgpack5/test/object-with-arrays'>;
}
declare module 'msgpack5/test/object-with-buffers.js' {
  declare module.exports: $Exports<'msgpack5/test/object-with-buffers'>;
}
declare module 'msgpack5/test/object-with-many-keys.js' {
  declare module.exports: $Exports<'msgpack5/test/object-with-many-keys'>;
}
declare module 'msgpack5/test/object-with-strings.js' {
  declare module.exports: $Exports<'msgpack5/test/object-with-strings'>;
}
declare module 'msgpack5/test/prefer-map.js' {
  declare module.exports: $Exports<'msgpack5/test/prefer-map'>;
}
declare module 'msgpack5/test/sparse-arrays.js' {
  declare module.exports: $Exports<'msgpack5/test/sparse-arrays'>;
}
declare module 'msgpack5/test/streams.js' {
  declare module.exports: $Exports<'msgpack5/test/streams'>;
}
declare module 'msgpack5/test/timestamps.js' {
  declare module.exports: $Exports<'msgpack5/test/timestamps'>;
}
