// flow-typed signature: 0efa79a3784c6db88d7022033a60d2a6
// flow-typed version: <<STUB>>/multistream_v^4.1.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multistream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multistream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'multistream/index' {
  declare module.exports: $Exports<'multistream'>;
}
declare module 'multistream/index.js' {
  declare module.exports: $Exports<'multistream'>;
}
