// flow-typed signature: 71117bbda474e01a358e36b2c868a677
// flow-typed version: <<STUB>>/nats_v^2.1.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nats'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nats' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nats/examples/bench' {
  declare module.exports: any;
}

declare module 'nats/examples/nats-events' {
  declare module.exports: any;
}

declare module 'nats/examples/nats-pub' {
  declare module.exports: any;
}

declare module 'nats/examples/nats-rep' {
  declare module.exports: any;
}

declare module 'nats/examples/nats-req' {
  declare module.exports: any;
}

declare module 'nats/examples/nats-sub' {
  declare module.exports: any;
}

declare module 'nats/examples/util' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/authenticator' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/bench' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/codec' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/databuffer' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/denobuffer' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/encoders' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/error' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/headers' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/heartbeats' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/internal_mod' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/ipparser' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jsbaseclient_api' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jsclient' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jsconsumeropts' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jslister' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jsm' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jsmconsumer_api' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jsmsg' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jsmstream_api' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/jsutil' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/kv' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/mod' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/msg' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/muxsubscription' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/nats' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/nkeys' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/nuid' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/options' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/parser' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/protocol' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/queued_iterator' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/request' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/servers' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/subscription' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/subscriptions' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/transport' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/typedsub' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/types' {
  declare module.exports: any;
}

declare module 'nats/lib/nats-base-client/util' {
  declare module.exports: any;
}

declare module 'nats/lib/src/connect' {
  declare module.exports: any;
}

declare module 'nats/lib/src/mod' {
  declare module.exports: any;
}

declare module 'nats/lib/src/nats-base-client' {
  declare module.exports: any;
}

declare module 'nats/lib/src/node_transport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nats/examples/bench.js' {
  declare module.exports: $Exports<'nats/examples/bench'>;
}
declare module 'nats/examples/nats-events.js' {
  declare module.exports: $Exports<'nats/examples/nats-events'>;
}
declare module 'nats/examples/nats-pub.js' {
  declare module.exports: $Exports<'nats/examples/nats-pub'>;
}
declare module 'nats/examples/nats-rep.js' {
  declare module.exports: $Exports<'nats/examples/nats-rep'>;
}
declare module 'nats/examples/nats-req.js' {
  declare module.exports: $Exports<'nats/examples/nats-req'>;
}
declare module 'nats/examples/nats-sub.js' {
  declare module.exports: $Exports<'nats/examples/nats-sub'>;
}
declare module 'nats/examples/util.js' {
  declare module.exports: $Exports<'nats/examples/util'>;
}
declare module 'nats/index' {
  declare module.exports: $Exports<'nats'>;
}
declare module 'nats/index.js' {
  declare module.exports: $Exports<'nats'>;
}
declare module 'nats/lib/nats-base-client/authenticator.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/authenticator'>;
}
declare module 'nats/lib/nats-base-client/bench.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/bench'>;
}
declare module 'nats/lib/nats-base-client/codec.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/codec'>;
}
declare module 'nats/lib/nats-base-client/databuffer.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/databuffer'>;
}
declare module 'nats/lib/nats-base-client/denobuffer.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/denobuffer'>;
}
declare module 'nats/lib/nats-base-client/encoders.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/encoders'>;
}
declare module 'nats/lib/nats-base-client/error.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/error'>;
}
declare module 'nats/lib/nats-base-client/headers.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/headers'>;
}
declare module 'nats/lib/nats-base-client/heartbeats.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/heartbeats'>;
}
declare module 'nats/lib/nats-base-client/internal_mod.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/internal_mod'>;
}
declare module 'nats/lib/nats-base-client/ipparser.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/ipparser'>;
}
declare module 'nats/lib/nats-base-client/jsbaseclient_api.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jsbaseclient_api'>;
}
declare module 'nats/lib/nats-base-client/jsclient.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jsclient'>;
}
declare module 'nats/lib/nats-base-client/jsconsumeropts.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jsconsumeropts'>;
}
declare module 'nats/lib/nats-base-client/jslister.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jslister'>;
}
declare module 'nats/lib/nats-base-client/jsm.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jsm'>;
}
declare module 'nats/lib/nats-base-client/jsmconsumer_api.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jsmconsumer_api'>;
}
declare module 'nats/lib/nats-base-client/jsmsg.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jsmsg'>;
}
declare module 'nats/lib/nats-base-client/jsmstream_api.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jsmstream_api'>;
}
declare module 'nats/lib/nats-base-client/jsutil.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/jsutil'>;
}
declare module 'nats/lib/nats-base-client/kv.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/kv'>;
}
declare module 'nats/lib/nats-base-client/mod.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/mod'>;
}
declare module 'nats/lib/nats-base-client/msg.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/msg'>;
}
declare module 'nats/lib/nats-base-client/muxsubscription.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/muxsubscription'>;
}
declare module 'nats/lib/nats-base-client/nats.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/nats'>;
}
declare module 'nats/lib/nats-base-client/nkeys.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/nkeys'>;
}
declare module 'nats/lib/nats-base-client/nuid.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/nuid'>;
}
declare module 'nats/lib/nats-base-client/options.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/options'>;
}
declare module 'nats/lib/nats-base-client/parser.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/parser'>;
}
declare module 'nats/lib/nats-base-client/protocol.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/protocol'>;
}
declare module 'nats/lib/nats-base-client/queued_iterator.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/queued_iterator'>;
}
declare module 'nats/lib/nats-base-client/request.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/request'>;
}
declare module 'nats/lib/nats-base-client/servers.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/servers'>;
}
declare module 'nats/lib/nats-base-client/subscription.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/subscription'>;
}
declare module 'nats/lib/nats-base-client/subscriptions.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/subscriptions'>;
}
declare module 'nats/lib/nats-base-client/transport.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/transport'>;
}
declare module 'nats/lib/nats-base-client/typedsub.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/typedsub'>;
}
declare module 'nats/lib/nats-base-client/types.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/types'>;
}
declare module 'nats/lib/nats-base-client/util.js' {
  declare module.exports: $Exports<'nats/lib/nats-base-client/util'>;
}
declare module 'nats/lib/src/connect.js' {
  declare module.exports: $Exports<'nats/lib/src/connect'>;
}
declare module 'nats/lib/src/mod.js' {
  declare module.exports: $Exports<'nats/lib/src/mod'>;
}
declare module 'nats/lib/src/nats-base-client.js' {
  declare module.exports: $Exports<'nats/lib/src/nats-base-client'>;
}
declare module 'nats/lib/src/node_transport.js' {
  declare module.exports: $Exports<'nats/lib/src/node_transport'>;
}
