/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 4ad4d53e35526bc42618da6fba06e606
// flow-typed version: <<STUB>>/nconf_v^0.10.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nconf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nconf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nconf/lib/nconf' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/common' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/formats' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/provider' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/mall/argv' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/mall/env' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/mall/file' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/mall/literal' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/mall/memory' {
  declare module.exports: any;
}

declare module 'nconf/test/common-test' {
  declare module.exports: any;
}

declare module 'nconf/test/complete-test' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/data' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-argv' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-change-argv' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-env' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-defaults-merge' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-file-argv' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-load-merge-with-separator' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-load-merge' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-load-save' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/nconf-nested-env' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/provider-argv' {
  declare module.exports: any;
}

declare module 'nconf/test/fixtures/scripts/provider-env' {
  declare module.exports: any;
}

declare module 'nconf/test/helpers' {
  declare module.exports: any;
}

declare module 'nconf/test/hierarchy-test' {
  declare module.exports: any;
}

declare module 'nconf/test/mocks/mock-store' {
  declare module.exports: any;
}

declare module 'nconf/test/nconf-test' {
  declare module.exports: any;
}

declare module 'nconf/test/provider-save-test' {
  declare module.exports: any;
}

declare module 'nconf/test/provider-test' {
  declare module.exports: any;
}

declare module 'nconf/test/mall/argv-test' {
  declare module.exports: any;
}

declare module 'nconf/test/mall/env-test' {
  declare module.exports: any;
}

declare module 'nconf/test/mall/file-store-test' {
  declare module.exports: any;
}

declare module 'nconf/test/mall/literal-test' {
  declare module.exports: any;
}

declare module 'nconf/test/mall/memory-store-test' {
  declare module.exports: any;
}

declare module 'nconf/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nconf/lib/nconf.js' {
  declare module.exports: $Exports<'nconf/lib/nconf'>;
}
declare module 'nconf/lib/nconf/common.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/common'>;
}
declare module 'nconf/lib/nconf/formats.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/formats'>;
}
declare module 'nconf/lib/nconf/provider.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/provider'>;
}
declare module 'nconf/lib/nconf/mall/argv.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/mall/argv'>;
}
declare module 'nconf/lib/nconf/mall/env.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/mall/env'>;
}
declare module 'nconf/lib/nconf/mall/file.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/mall/file'>;
}
declare module 'nconf/lib/nconf/mall/literal.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/mall/literal'>;
}
declare module 'nconf/lib/nconf/mall/memory.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/mall/memory'>;
}
declare module 'nconf/test/common-test.js' {
  declare module.exports: $Exports<'nconf/test/common-test'>;
}
declare module 'nconf/test/complete-test.js' {
  declare module.exports: $Exports<'nconf/test/complete-test'>;
}
declare module 'nconf/test/fixtures/data.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/data'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-argv.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-argv'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-change-argv.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-change-argv'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-env.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-env'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-defaults-merge.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-hierarchical-defaults-merge'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-file-argv.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-hierarchical-file-argv'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-load-merge-with-separator.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-hierarchical-load-merge-with-separator'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-load-merge.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-hierarchical-load-merge'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-hierarchical-load-save.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-hierarchical-load-save'>;
}
declare module 'nconf/test/fixtures/scripts/nconf-nested-env.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/nconf-nested-env'>;
}
declare module 'nconf/test/fixtures/scripts/provider-argv.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/provider-argv'>;
}
declare module 'nconf/test/fixtures/scripts/provider-env.js' {
  declare module.exports: $Exports<'nconf/test/fixtures/scripts/provider-env'>;
}
declare module 'nconf/test/helpers.js' {
  declare module.exports: $Exports<'nconf/test/helpers'>;
}
declare module 'nconf/test/hierarchy-test.js' {
  declare module.exports: $Exports<'nconf/test/hierarchy-test'>;
}
declare module 'nconf/test/mocks/mock-store.js' {
  declare module.exports: $Exports<'nconf/test/mocks/mock-store'>;
}
declare module 'nconf/test/nconf-test.js' {
  declare module.exports: $Exports<'nconf/test/nconf-test'>;
}
declare module 'nconf/test/provider-save-test.js' {
  declare module.exports: $Exports<'nconf/test/provider-save-test'>;
}
declare module 'nconf/test/provider-test.js' {
  declare module.exports: $Exports<'nconf/test/provider-test'>;
}
declare module 'nconf/test/mall/argv-test.js' {
  declare module.exports: $Exports<'nconf/test/mall/argv-test'>;
}
declare module 'nconf/test/mall/env-test.js' {
  declare module.exports: $Exports<'nconf/test/mall/env-test'>;
}
declare module 'nconf/test/mall/file-store-test.js' {
  declare module.exports: $Exports<'nconf/test/mall/file-store-test'>;
}
declare module 'nconf/test/mall/literal-test.js' {
  declare module.exports: $Exports<'nconf/test/mall/literal-test'>;
}
declare module 'nconf/test/mall/memory-store-test.js' {
  declare module.exports: $Exports<'nconf/test/mall/memory-store-test'>;
}
declare module 'nconf/usage.js' {
  declare module.exports: $Exports<'nconf/usage'>;
}
