// flow-typed signature: c256ff751961559e4921a19112e71d61
// flow-typed version: <<STUB>>/node-foreman_vgit://github.com/pryv/node-foreman.git#4eb501d443432878491b2d0387ded96e7c4154d0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-foreman'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-foreman' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-foreman/demo/server' {
  declare module.exports: any;
}

declare module 'node-foreman/forward' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/colors' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/console' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/envs' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/exporters' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/forward' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/proc' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/procfile' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/proxy' {
  declare module.exports: any;
}

declare module 'node-foreman/lib/requirements' {
  declare module.exports: any;
}

declare module 'node-foreman/nf' {
  declare module.exports: any;
}

declare module 'node-foreman/proxy' {
  declare module.exports: any;
}

declare module 'node-foreman/test/console-output.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/console-trim.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/envs-commented.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/envs-empty.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/envs-json.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/envs-quoted.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/proxy-ssl.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/proxy.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/run-once.test' {
  declare module.exports: any;
}

declare module 'node-foreman/test/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-foreman/demo/server.js' {
  declare module.exports: $Exports<'node-foreman/demo/server'>;
}
declare module 'node-foreman/forward.js' {
  declare module.exports: $Exports<'node-foreman/forward'>;
}
declare module 'node-foreman/lib/colors.js' {
  declare module.exports: $Exports<'node-foreman/lib/colors'>;
}
declare module 'node-foreman/lib/console.js' {
  declare module.exports: $Exports<'node-foreman/lib/console'>;
}
declare module 'node-foreman/lib/envs.js' {
  declare module.exports: $Exports<'node-foreman/lib/envs'>;
}
declare module 'node-foreman/lib/exporters.js' {
  declare module.exports: $Exports<'node-foreman/lib/exporters'>;
}
declare module 'node-foreman/lib/forward.js' {
  declare module.exports: $Exports<'node-foreman/lib/forward'>;
}
declare module 'node-foreman/lib/proc.js' {
  declare module.exports: $Exports<'node-foreman/lib/proc'>;
}
declare module 'node-foreman/lib/procfile.js' {
  declare module.exports: $Exports<'node-foreman/lib/procfile'>;
}
declare module 'node-foreman/lib/proxy.js' {
  declare module.exports: $Exports<'node-foreman/lib/proxy'>;
}
declare module 'node-foreman/lib/requirements.js' {
  declare module.exports: $Exports<'node-foreman/lib/requirements'>;
}
declare module 'node-foreman/nf.js' {
  declare module.exports: $Exports<'node-foreman/nf'>;
}
declare module 'node-foreman/proxy.js' {
  declare module.exports: $Exports<'node-foreman/proxy'>;
}
declare module 'node-foreman/test/console-output.test.js' {
  declare module.exports: $Exports<'node-foreman/test/console-output.test'>;
}
declare module 'node-foreman/test/console-trim.test.js' {
  declare module.exports: $Exports<'node-foreman/test/console-trim.test'>;
}
declare module 'node-foreman/test/envs-commented.test.js' {
  declare module.exports: $Exports<'node-foreman/test/envs-commented.test'>;
}
declare module 'node-foreman/test/envs-empty.test.js' {
  declare module.exports: $Exports<'node-foreman/test/envs-empty.test'>;
}
declare module 'node-foreman/test/envs-json.test.js' {
  declare module.exports: $Exports<'node-foreman/test/envs-json.test'>;
}
declare module 'node-foreman/test/envs-quoted.test.js' {
  declare module.exports: $Exports<'node-foreman/test/envs-quoted.test'>;
}
declare module 'node-foreman/test/proxy-ssl.test.js' {
  declare module.exports: $Exports<'node-foreman/test/proxy-ssl.test'>;
}
declare module 'node-foreman/test/proxy.test.js' {
  declare module.exports: $Exports<'node-foreman/test/proxy.test'>;
}
declare module 'node-foreman/test/run-once.test.js' {
  declare module.exports: $Exports<'node-foreman/test/run-once.test'>;
}
declare module 'node-foreman/test/server.js' {
  declare module.exports: $Exports<'node-foreman/test/server'>;
}
