// flow-typed signature: 7c8ca4399abe324d9d2ff098127f464f
// flow-typed version: <<STUB>>/parallelshell_v^2.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parallelshell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'parallelshell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parallelshell/index' {
  declare module.exports: $Exports<'parallelshell'>;
}
declare module 'parallelshell/index.js' {
  declare module.exports: $Exports<'parallelshell'>;
}
