/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 6eff1f3a8ce7e642d4bf080d28ef3f0a
// flow-typed version: <<STUB>>/parallelshell_v^2.0.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parallelshell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parallelshell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parallelshell/index' {
  declare module.exports: $Exports<'parallelshell'>;
}
declare module 'parallelshell/index.js' {
  declare module.exports: $Exports<'parallelshell'>;
}
