// flow-typed signature: 78facffdfb965216501133aaee780e88
// flow-typed version: <<STUB>>/previews-server_vfile:source/previews-server/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'previews-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'previews-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'previews-server/src/Cache' {
  declare module.exports: any;
}

declare module 'previews-server/src/config' {
  declare module.exports: any;
}

declare module 'previews-server/src/expressApp' {
  declare module.exports: any;
}

declare module 'previews-server/src/middleware/errors' {
  declare module.exports: any;
}

declare module 'previews-server/src/routes/event-previews' {
  declare module.exports: any;
}

declare module 'previews-server/src/routes/index' {
  declare module.exports: any;
}

declare module 'previews-server/src/runCacheCleanup' {
  declare module.exports: any;
}

declare module 'previews-server/src/server' {
  declare module.exports: any;
}

declare module 'previews-server/test/event-previews.test' {
  declare module.exports: any;
}

declare module 'previews-server/test/helpers/dependencies' {
  declare module.exports: any;
}

declare module 'previews-server/test/helpers/index' {
  declare module.exports: any;
}

declare module 'previews-server/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'previews-server/src/Cache.js' {
  declare module.exports: $Exports<'previews-server/src/Cache'>;
}
declare module 'previews-server/src/config.js' {
  declare module.exports: $Exports<'previews-server/src/config'>;
}
declare module 'previews-server/src/expressApp.js' {
  declare module.exports: $Exports<'previews-server/src/expressApp'>;
}
declare module 'previews-server/src/middleware/errors.js' {
  declare module.exports: $Exports<'previews-server/src/middleware/errors'>;
}
declare module 'previews-server/src/routes/event-previews.js' {
  declare module.exports: $Exports<'previews-server/src/routes/event-previews'>;
}
declare module 'previews-server/src/routes/index.js' {
  declare module.exports: $Exports<'previews-server/src/routes/index'>;
}
declare module 'previews-server/src/runCacheCleanup.js' {
  declare module.exports: $Exports<'previews-server/src/runCacheCleanup'>;
}
declare module 'previews-server/src/server.js' {
  declare module.exports: $Exports<'previews-server/src/server'>;
}
declare module 'previews-server/test/event-previews.test.js' {
  declare module.exports: $Exports<'previews-server/test/event-previews.test'>;
}
declare module 'previews-server/test/helpers/dependencies.js' {
  declare module.exports: $Exports<'previews-server/test/helpers/dependencies'>;
}
declare module 'previews-server/test/helpers/index.js' {
  declare module.exports: $Exports<'previews-server/test/helpers/index'>;
}
declare module 'previews-server/test/index.test.js' {
  declare module.exports: $Exports<'previews-server/test/index.test'>;
}
