/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: d48ebbf7fcb3c164251a9376707780dc
// flow-typed version: <<STUB>>/previews-server_vfile:components/previews-server/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'previews-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'previews-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'previews-server/src/cache' {
  declare module.exports: any;
}

declare module 'previews-server/src/config' {
  declare module.exports: any;
}

declare module 'previews-server/src/expressApp' {
  declare module.exports: any;
}

declare module 'previews-server/src/middleware/errors' {
  declare module.exports: any;
}

declare module 'previews-server/src/routes/event-previews' {
  declare module.exports: any;
}

declare module 'previews-server/src/routes' {
  declare module.exports: any;
}

declare module 'previews-server/src/runCacheCleanup' {
  declare module.exports: any;
}

declare module 'previews-server/src/server' {
  declare module.exports: any;
}

declare module 'previews-server/test/event-previews.test' {
  declare module.exports: any;
}

declare module 'previews-server/test/helpers/dependencies' {
  declare module.exports: any;
}

declare module 'previews-server/test/helpers' {
  declare module.exports: any;
}

declare module 'previews-server/test/index.test' {
  declare module.exports: any;
}

declare module 'previews-server/test/test-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'previews-server/src/cache.js' {
  declare module.exports: $Exports<'previews-server/src/cache'>;
}
declare module 'previews-server/src/config.js' {
  declare module.exports: $Exports<'previews-server/src/config'>;
}
declare module 'previews-server/src/expressApp.js' {
  declare module.exports: $Exports<'previews-server/src/expressApp'>;
}
declare module 'previews-server/src/middleware/errors.js' {
  declare module.exports: $Exports<'previews-server/src/middleware/errors'>;
}
declare module 'previews-server/src/routes/event-previews.js' {
  declare module.exports: $Exports<'previews-server/src/routes/event-previews'>;
}
declare module 'previews-server/src/routes/index' {
  declare module.exports: $Exports<'previews-server/src/routes'>;
}
declare module 'previews-server/src/routes/index.js' {
  declare module.exports: $Exports<'previews-server/src/routes'>;
}
declare module 'previews-server/src/runCacheCleanup.js' {
  declare module.exports: $Exports<'previews-server/src/runCacheCleanup'>;
}
declare module 'previews-server/src/server.js' {
  declare module.exports: $Exports<'previews-server/src/server'>;
}
declare module 'previews-server/test/event-previews.test.js' {
  declare module.exports: $Exports<'previews-server/test/event-previews.test'>;
}
declare module 'previews-server/test/helpers/dependencies.js' {
  declare module.exports: $Exports<'previews-server/test/helpers/dependencies'>;
}
declare module 'previews-server/test/helpers/index' {
  declare module.exports: $Exports<'previews-server/test/helpers'>;
}
declare module 'previews-server/test/helpers/index.js' {
  declare module.exports: $Exports<'previews-server/test/helpers'>;
}
declare module 'previews-server/test/index.test.js' {
  declare module.exports: $Exports<'previews-server/test/index.test'>;
}
declare module 'previews-server/test/test-helpers.js' {
  declare module.exports: $Exports<'previews-server/test/test-helpers'>;
}
