/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: e0a1ea7c97fbfcce767103c1c7081738
// flow-typed version: <<STUB>>/protobufjs_v^6.8.6/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protobufjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protobufjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protobufjs/cli' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/lib/tsd-jsdoc/plugin' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/lib/tsd-jsdoc/publish' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/os-tmpdir' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/tmp/lib/tmp' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/pbjs' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/pbts' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/json-module' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/json' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/proto' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/proto2' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/proto3' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/static-module' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/static' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/util' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/amd' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/closure' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/commonjs' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/default' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/es6' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/light/protobuf' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/light/protobuf.min' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/minimal/protobuf' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/minimal/protobuf.min' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/protobuf' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/protobuf.min' {
  declare module.exports: any;
}

declare module 'protobufjs/ext/debug' {
  declare module.exports: any;
}

declare module 'protobufjs/ext/descriptor' {
  declare module.exports: any;
}

declare module 'protobufjs/ext/descriptor/test' {
  declare module.exports: any;
}

declare module 'protobufjs/light' {
  declare module.exports: any;
}

declare module 'protobufjs/minimal' {
  declare module.exports: any;
}

declare module 'protobufjs/scripts/changelog' {
  declare module.exports: any;
}

declare module 'protobufjs/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'protobufjs/src/common' {
  declare module.exports: any;
}

declare module 'protobufjs/src/converter' {
  declare module.exports: any;
}

declare module 'protobufjs/src/decoder' {
  declare module.exports: any;
}

declare module 'protobufjs/src/encoder' {
  declare module.exports: any;
}

declare module 'protobufjs/src/enum' {
  declare module.exports: any;
}

declare module 'protobufjs/src/field' {
  declare module.exports: any;
}

declare module 'protobufjs/src/index-light' {
  declare module.exports: any;
}

declare module 'protobufjs/src/index-minimal' {
  declare module.exports: any;
}

declare module 'protobufjs/src' {
  declare module.exports: any;
}

declare module 'protobufjs/src/mapfield' {
  declare module.exports: any;
}

declare module 'protobufjs/src/message' {
  declare module.exports: any;
}

declare module 'protobufjs/src/method' {
  declare module.exports: any;
}

declare module 'protobufjs/src/namespace' {
  declare module.exports: any;
}

declare module 'protobufjs/src/object' {
  declare module.exports: any;
}

declare module 'protobufjs/src/oneof' {
  declare module.exports: any;
}

declare module 'protobufjs/src/parse' {
  declare module.exports: any;
}

declare module 'protobufjs/src/reader_buffer' {
  declare module.exports: any;
}

declare module 'protobufjs/src/reader' {
  declare module.exports: any;
}

declare module 'protobufjs/src/root' {
  declare module.exports: any;
}

declare module 'protobufjs/src/roots' {
  declare module.exports: any;
}

declare module 'protobufjs/src/rpc' {
  declare module.exports: any;
}

declare module 'protobufjs/src/rpc/service' {
  declare module.exports: any;
}

declare module 'protobufjs/src/service' {
  declare module.exports: any;
}

declare module 'protobufjs/src/tokenize' {
  declare module.exports: any;
}

declare module 'protobufjs/src/type' {
  declare module.exports: any;
}

declare module 'protobufjs/src/types' {
  declare module.exports: any;
}

declare module 'protobufjs/src/util' {
  declare module.exports: any;
}

declare module 'protobufjs/src/util/longbits' {
  declare module.exports: any;
}

declare module 'protobufjs/src/util/minimal' {
  declare module.exports: any;
}

declare module 'protobufjs/src/verifier' {
  declare module.exports: any;
}

declare module 'protobufjs/src/wrappers' {
  declare module.exports: any;
}

declare module 'protobufjs/src/writer_buffer' {
  declare module.exports: any;
}

declare module 'protobufjs/src/writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protobufjs/cli/index' {
  declare module.exports: $Exports<'protobufjs/cli'>;
}
declare module 'protobufjs/cli/index.js' {
  declare module.exports: $Exports<'protobufjs/cli'>;
}
declare module 'protobufjs/cli/lib/tsd-jsdoc/plugin.js' {
  declare module.exports: $Exports<'protobufjs/cli/lib/tsd-jsdoc/plugin'>;
}
declare module 'protobufjs/cli/lib/tsd-jsdoc/publish.js' {
  declare module.exports: $Exports<'protobufjs/cli/lib/tsd-jsdoc/publish'>;
}
declare module 'protobufjs/cli/node_modules/os-tmpdir/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/os-tmpdir'>;
}
declare module 'protobufjs/cli/node_modules/os-tmpdir/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/os-tmpdir'>;
}
declare module 'protobufjs/cli/node_modules/tmp/lib/tmp.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/tmp/lib/tmp'>;
}
declare module 'protobufjs/cli/pbjs.js' {
  declare module.exports: $Exports<'protobufjs/cli/pbjs'>;
}
declare module 'protobufjs/cli/pbts.js' {
  declare module.exports: $Exports<'protobufjs/cli/pbts'>;
}
declare module 'protobufjs/cli/targets/json-module.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/json-module'>;
}
declare module 'protobufjs/cli/targets/json.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/json'>;
}
declare module 'protobufjs/cli/targets/proto.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/proto'>;
}
declare module 'protobufjs/cli/targets/proto2.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/proto2'>;
}
declare module 'protobufjs/cli/targets/proto3.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/proto3'>;
}
declare module 'protobufjs/cli/targets/static-module.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/static-module'>;
}
declare module 'protobufjs/cli/targets/static.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/static'>;
}
declare module 'protobufjs/cli/util.js' {
  declare module.exports: $Exports<'protobufjs/cli/util'>;
}
declare module 'protobufjs/cli/wrappers/amd.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/amd'>;
}
declare module 'protobufjs/cli/wrappers/closure.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/closure'>;
}
declare module 'protobufjs/cli/wrappers/commonjs.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/commonjs'>;
}
declare module 'protobufjs/cli/wrappers/default.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/default'>;
}
declare module 'protobufjs/cli/wrappers/es6.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/es6'>;
}
declare module 'protobufjs/dist/light/protobuf.js' {
  declare module.exports: $Exports<'protobufjs/dist/light/protobuf'>;
}
declare module 'protobufjs/dist/light/protobuf.min.js' {
  declare module.exports: $Exports<'protobufjs/dist/light/protobuf.min'>;
}
declare module 'protobufjs/dist/minimal/protobuf.js' {
  declare module.exports: $Exports<'protobufjs/dist/minimal/protobuf'>;
}
declare module 'protobufjs/dist/minimal/protobuf.min.js' {
  declare module.exports: $Exports<'protobufjs/dist/minimal/protobuf.min'>;
}
declare module 'protobufjs/dist/protobuf.js' {
  declare module.exports: $Exports<'protobufjs/dist/protobuf'>;
}
declare module 'protobufjs/dist/protobuf.min.js' {
  declare module.exports: $Exports<'protobufjs/dist/protobuf.min'>;
}
declare module 'protobufjs/ext/debug/index' {
  declare module.exports: $Exports<'protobufjs/ext/debug'>;
}
declare module 'protobufjs/ext/debug/index.js' {
  declare module.exports: $Exports<'protobufjs/ext/debug'>;
}
declare module 'protobufjs/ext/descriptor/index' {
  declare module.exports: $Exports<'protobufjs/ext/descriptor'>;
}
declare module 'protobufjs/ext/descriptor/index.js' {
  declare module.exports: $Exports<'protobufjs/ext/descriptor'>;
}
declare module 'protobufjs/ext/descriptor/test.js' {
  declare module.exports: $Exports<'protobufjs/ext/descriptor/test'>;
}
declare module 'protobufjs/index' {
  declare module.exports: $Exports<'protobufjs'>;
}
declare module 'protobufjs/index.js' {
  declare module.exports: $Exports<'protobufjs'>;
}
declare module 'protobufjs/light.js' {
  declare module.exports: $Exports<'protobufjs/light'>;
}
declare module 'protobufjs/minimal.js' {
  declare module.exports: $Exports<'protobufjs/minimal'>;
}
declare module 'protobufjs/scripts/changelog.js' {
  declare module.exports: $Exports<'protobufjs/scripts/changelog'>;
}
declare module 'protobufjs/scripts/postinstall.js' {
  declare module.exports: $Exports<'protobufjs/scripts/postinstall'>;
}
declare module 'protobufjs/src/common.js' {
  declare module.exports: $Exports<'protobufjs/src/common'>;
}
declare module 'protobufjs/src/converter.js' {
  declare module.exports: $Exports<'protobufjs/src/converter'>;
}
declare module 'protobufjs/src/decoder.js' {
  declare module.exports: $Exports<'protobufjs/src/decoder'>;
}
declare module 'protobufjs/src/encoder.js' {
  declare module.exports: $Exports<'protobufjs/src/encoder'>;
}
declare module 'protobufjs/src/enum.js' {
  declare module.exports: $Exports<'protobufjs/src/enum'>;
}
declare module 'protobufjs/src/field.js' {
  declare module.exports: $Exports<'protobufjs/src/field'>;
}
declare module 'protobufjs/src/index-light.js' {
  declare module.exports: $Exports<'protobufjs/src/index-light'>;
}
declare module 'protobufjs/src/index-minimal.js' {
  declare module.exports: $Exports<'protobufjs/src/index-minimal'>;
}
declare module 'protobufjs/src/index' {
  declare module.exports: $Exports<'protobufjs/src'>;
}
declare module 'protobufjs/src/index.js' {
  declare module.exports: $Exports<'protobufjs/src'>;
}
declare module 'protobufjs/src/mapfield.js' {
  declare module.exports: $Exports<'protobufjs/src/mapfield'>;
}
declare module 'protobufjs/src/message.js' {
  declare module.exports: $Exports<'protobufjs/src/message'>;
}
declare module 'protobufjs/src/method.js' {
  declare module.exports: $Exports<'protobufjs/src/method'>;
}
declare module 'protobufjs/src/namespace.js' {
  declare module.exports: $Exports<'protobufjs/src/namespace'>;
}
declare module 'protobufjs/src/object.js' {
  declare module.exports: $Exports<'protobufjs/src/object'>;
}
declare module 'protobufjs/src/oneof.js' {
  declare module.exports: $Exports<'protobufjs/src/oneof'>;
}
declare module 'protobufjs/src/parse.js' {
  declare module.exports: $Exports<'protobufjs/src/parse'>;
}
declare module 'protobufjs/src/reader_buffer.js' {
  declare module.exports: $Exports<'protobufjs/src/reader_buffer'>;
}
declare module 'protobufjs/src/reader.js' {
  declare module.exports: $Exports<'protobufjs/src/reader'>;
}
declare module 'protobufjs/src/root.js' {
  declare module.exports: $Exports<'protobufjs/src/root'>;
}
declare module 'protobufjs/src/roots.js' {
  declare module.exports: $Exports<'protobufjs/src/roots'>;
}
declare module 'protobufjs/src/rpc.js' {
  declare module.exports: $Exports<'protobufjs/src/rpc'>;
}
declare module 'protobufjs/src/rpc/service.js' {
  declare module.exports: $Exports<'protobufjs/src/rpc/service'>;
}
declare module 'protobufjs/src/service.js' {
  declare module.exports: $Exports<'protobufjs/src/service'>;
}
declare module 'protobufjs/src/tokenize.js' {
  declare module.exports: $Exports<'protobufjs/src/tokenize'>;
}
declare module 'protobufjs/src/type.js' {
  declare module.exports: $Exports<'protobufjs/src/type'>;
}
declare module 'protobufjs/src/types.js' {
  declare module.exports: $Exports<'protobufjs/src/types'>;
}
declare module 'protobufjs/src/util.js' {
  declare module.exports: $Exports<'protobufjs/src/util'>;
}
declare module 'protobufjs/src/util/longbits.js' {
  declare module.exports: $Exports<'protobufjs/src/util/longbits'>;
}
declare module 'protobufjs/src/util/minimal.js' {
  declare module.exports: $Exports<'protobufjs/src/util/minimal'>;
}
declare module 'protobufjs/src/verifier.js' {
  declare module.exports: $Exports<'protobufjs/src/verifier'>;
}
declare module 'protobufjs/src/wrappers.js' {
  declare module.exports: $Exports<'protobufjs/src/wrappers'>;
}
declare module 'protobufjs/src/writer_buffer.js' {
  declare module.exports: $Exports<'protobufjs/src/writer_buffer'>;
}
declare module 'protobufjs/src/writer.js' {
  declare module.exports: $Exports<'protobufjs/src/writer'>;
}
