// flow-typed signature: 0c11a0cbaf25787222d79aa5d5915fd8
// flow-typed version: <<STUB>>/protobufjs_v^6.8.6/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protobufjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protobufjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protobufjs/cli' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/lib/tsd-jsdoc/plugin' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/lib/tsd-jsdoc/publish' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/acorn-jsx' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/acorn-jsx/xhtml' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/acorn/dist/acorn' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/acorn/dist/bin' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/balanced-match' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/brace-expansion' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/concat-map/example/map' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/concat-map' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/concat-map/test/map' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/deep-is/example/cmp' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/deep-is' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/deep-is/test/cmp' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/deep-is/test/NaN' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/deep-is/test/neg-vs-pos-0' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/escodegen/bin/escodegen' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/escodegen/bin/esgenerate' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/escodegen/escodegen' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/eslint-visitor-keys/lib' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/espree/espree' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/espree/lib/ast-node-types' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/espree/lib/espree' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/espree/lib/features' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/espree/lib/options' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/espree/lib/token-translator' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/espree/lib/visitor-keys' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/esprima/bin/esparse' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/esprima/bin/esvalidate' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/esprima/dist/esprima' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/estraverse/estraverse' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/estraverse/gulpfile' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/esutils/lib/ast' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/esutils/lib/code' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/esutils/lib/keyword' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/esutils/lib/utils' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/fast-levenshtein/levenshtein' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/fs.realpath' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/fs.realpath/old' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/glob/common' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/glob/glob' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/glob/sync' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/inflight/inflight' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/inherits/inherits_browser' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/inherits/inherits' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/levn/lib/cast' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/levn/lib/coerce' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/levn/lib' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/levn/lib/parse-string' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/levn/lib/parse' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/minimatch/minimatch' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/once/once' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/optionator/lib/help' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/optionator/lib' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/optionator/lib/util' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/path-is-absolute' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/prelude-ls/lib/Func' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/prelude-ls/lib' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/prelude-ls/lib/List' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/prelude-ls/lib/Num' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/prelude-ls/lib/Obj' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/prelude-ls/lib/Str' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/rimraf/bin' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/rimraf/rimraf' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/dist/source-map.debug' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/dist/source-map' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/dist/source-map.min' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/array-set' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/base64-vlq' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/base64' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/binary-search' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/mapping-list' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/quick-sort' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/source-map-consumer' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/source-map-generator' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/source-node' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/lib/util' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/source-map/source-map' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/tmp/lib/tmp' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/type-check/lib/check' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/type-check/lib' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/type-check/lib/parse-type' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/word-wrap' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/node_modules/wrappy/wrappy' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/pbjs' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/pbts' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/json-module' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/json' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/proto' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/proto2' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/proto3' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/static-module' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/targets/static' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/util' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/amd' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/closure' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/commonjs' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/default' {
  declare module.exports: any;
}

declare module 'protobufjs/cli/wrappers/es6' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/light/protobuf' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/light/protobuf.min' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/minimal/protobuf' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/minimal/protobuf.min' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/protobuf' {
  declare module.exports: any;
}

declare module 'protobufjs/dist/protobuf.min' {
  declare module.exports: any;
}

declare module 'protobufjs/ext/debug' {
  declare module.exports: any;
}

declare module 'protobufjs/ext/descriptor' {
  declare module.exports: any;
}

declare module 'protobufjs/ext/descriptor/test' {
  declare module.exports: any;
}

declare module 'protobufjs/light' {
  declare module.exports: any;
}

declare module 'protobufjs/minimal' {
  declare module.exports: any;
}

declare module 'protobufjs/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'protobufjs/src/common' {
  declare module.exports: any;
}

declare module 'protobufjs/src/converter' {
  declare module.exports: any;
}

declare module 'protobufjs/src/decoder' {
  declare module.exports: any;
}

declare module 'protobufjs/src/encoder' {
  declare module.exports: any;
}

declare module 'protobufjs/src/enum' {
  declare module.exports: any;
}

declare module 'protobufjs/src/field' {
  declare module.exports: any;
}

declare module 'protobufjs/src/index-light' {
  declare module.exports: any;
}

declare module 'protobufjs/src/index-minimal' {
  declare module.exports: any;
}

declare module 'protobufjs/src' {
  declare module.exports: any;
}

declare module 'protobufjs/src/mapfield' {
  declare module.exports: any;
}

declare module 'protobufjs/src/message' {
  declare module.exports: any;
}

declare module 'protobufjs/src/method' {
  declare module.exports: any;
}

declare module 'protobufjs/src/namespace' {
  declare module.exports: any;
}

declare module 'protobufjs/src/object' {
  declare module.exports: any;
}

declare module 'protobufjs/src/oneof' {
  declare module.exports: any;
}

declare module 'protobufjs/src/parse' {
  declare module.exports: any;
}

declare module 'protobufjs/src/reader_buffer' {
  declare module.exports: any;
}

declare module 'protobufjs/src/reader' {
  declare module.exports: any;
}

declare module 'protobufjs/src/root' {
  declare module.exports: any;
}

declare module 'protobufjs/src/roots' {
  declare module.exports: any;
}

declare module 'protobufjs/src/rpc' {
  declare module.exports: any;
}

declare module 'protobufjs/src/rpc/service' {
  declare module.exports: any;
}

declare module 'protobufjs/src/service' {
  declare module.exports: any;
}

declare module 'protobufjs/src/tokenize' {
  declare module.exports: any;
}

declare module 'protobufjs/src/type' {
  declare module.exports: any;
}

declare module 'protobufjs/src/types' {
  declare module.exports: any;
}

declare module 'protobufjs/src/util' {
  declare module.exports: any;
}

declare module 'protobufjs/src/util/longbits' {
  declare module.exports: any;
}

declare module 'protobufjs/src/util/minimal' {
  declare module.exports: any;
}

declare module 'protobufjs/src/verifier' {
  declare module.exports: any;
}

declare module 'protobufjs/src/wrappers' {
  declare module.exports: any;
}

declare module 'protobufjs/src/writer_buffer' {
  declare module.exports: any;
}

declare module 'protobufjs/src/writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protobufjs/cli/index' {
  declare module.exports: $Exports<'protobufjs/cli'>;
}
declare module 'protobufjs/cli/index.js' {
  declare module.exports: $Exports<'protobufjs/cli'>;
}
declare module 'protobufjs/cli/lib/tsd-jsdoc/plugin.js' {
  declare module.exports: $Exports<'protobufjs/cli/lib/tsd-jsdoc/plugin'>;
}
declare module 'protobufjs/cli/lib/tsd-jsdoc/publish.js' {
  declare module.exports: $Exports<'protobufjs/cli/lib/tsd-jsdoc/publish'>;
}
declare module 'protobufjs/cli/node_modules/acorn-jsx/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/acorn-jsx'>;
}
declare module 'protobufjs/cli/node_modules/acorn-jsx/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/acorn-jsx'>;
}
declare module 'protobufjs/cli/node_modules/acorn-jsx/xhtml.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/acorn-jsx/xhtml'>;
}
declare module 'protobufjs/cli/node_modules/acorn/dist/acorn.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/acorn/dist/acorn'>;
}
declare module 'protobufjs/cli/node_modules/acorn/dist/bin.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/acorn/dist/bin'>;
}
declare module 'protobufjs/cli/node_modules/balanced-match/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/balanced-match'>;
}
declare module 'protobufjs/cli/node_modules/balanced-match/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/balanced-match'>;
}
declare module 'protobufjs/cli/node_modules/brace-expansion/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/brace-expansion'>;
}
declare module 'protobufjs/cli/node_modules/brace-expansion/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/brace-expansion'>;
}
declare module 'protobufjs/cli/node_modules/concat-map/example/map.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/concat-map/example/map'>;
}
declare module 'protobufjs/cli/node_modules/concat-map/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/concat-map'>;
}
declare module 'protobufjs/cli/node_modules/concat-map/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/concat-map'>;
}
declare module 'protobufjs/cli/node_modules/concat-map/test/map.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/concat-map/test/map'>;
}
declare module 'protobufjs/cli/node_modules/deep-is/example/cmp.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/deep-is/example/cmp'>;
}
declare module 'protobufjs/cli/node_modules/deep-is/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/deep-is'>;
}
declare module 'protobufjs/cli/node_modules/deep-is/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/deep-is'>;
}
declare module 'protobufjs/cli/node_modules/deep-is/test/cmp.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/deep-is/test/cmp'>;
}
declare module 'protobufjs/cli/node_modules/deep-is/test/NaN.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/deep-is/test/NaN'>;
}
declare module 'protobufjs/cli/node_modules/deep-is/test/neg-vs-pos-0.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/deep-is/test/neg-vs-pos-0'>;
}
declare module 'protobufjs/cli/node_modules/escodegen/bin/escodegen.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/escodegen/bin/escodegen'>;
}
declare module 'protobufjs/cli/node_modules/escodegen/bin/esgenerate.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/escodegen/bin/esgenerate'>;
}
declare module 'protobufjs/cli/node_modules/escodegen/escodegen.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/escodegen/escodegen'>;
}
declare module 'protobufjs/cli/node_modules/eslint-visitor-keys/lib/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/eslint-visitor-keys/lib'>;
}
declare module 'protobufjs/cli/node_modules/eslint-visitor-keys/lib/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/eslint-visitor-keys/lib'>;
}
declare module 'protobufjs/cli/node_modules/espree/espree.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/espree/espree'>;
}
declare module 'protobufjs/cli/node_modules/espree/lib/ast-node-types.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/espree/lib/ast-node-types'>;
}
declare module 'protobufjs/cli/node_modules/espree/lib/espree.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/espree/lib/espree'>;
}
declare module 'protobufjs/cli/node_modules/espree/lib/features.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/espree/lib/features'>;
}
declare module 'protobufjs/cli/node_modules/espree/lib/options.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/espree/lib/options'>;
}
declare module 'protobufjs/cli/node_modules/espree/lib/token-translator.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/espree/lib/token-translator'>;
}
declare module 'protobufjs/cli/node_modules/espree/lib/visitor-keys.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/espree/lib/visitor-keys'>;
}
declare module 'protobufjs/cli/node_modules/esprima/bin/esparse.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/esprima/bin/esparse'>;
}
declare module 'protobufjs/cli/node_modules/esprima/bin/esvalidate.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/esprima/bin/esvalidate'>;
}
declare module 'protobufjs/cli/node_modules/esprima/dist/esprima.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/esprima/dist/esprima'>;
}
declare module 'protobufjs/cli/node_modules/estraverse/estraverse.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/estraverse/estraverse'>;
}
declare module 'protobufjs/cli/node_modules/estraverse/gulpfile.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/estraverse/gulpfile'>;
}
declare module 'protobufjs/cli/node_modules/esutils/lib/ast.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/esutils/lib/ast'>;
}
declare module 'protobufjs/cli/node_modules/esutils/lib/code.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/esutils/lib/code'>;
}
declare module 'protobufjs/cli/node_modules/esutils/lib/keyword.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/esutils/lib/keyword'>;
}
declare module 'protobufjs/cli/node_modules/esutils/lib/utils.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/esutils/lib/utils'>;
}
declare module 'protobufjs/cli/node_modules/fast-levenshtein/levenshtein.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/fast-levenshtein/levenshtein'>;
}
declare module 'protobufjs/cli/node_modules/fs.realpath/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/fs.realpath'>;
}
declare module 'protobufjs/cli/node_modules/fs.realpath/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/fs.realpath'>;
}
declare module 'protobufjs/cli/node_modules/fs.realpath/old.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/fs.realpath/old'>;
}
declare module 'protobufjs/cli/node_modules/glob/common.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/glob/common'>;
}
declare module 'protobufjs/cli/node_modules/glob/glob.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/glob/glob'>;
}
declare module 'protobufjs/cli/node_modules/glob/sync.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/glob/sync'>;
}
declare module 'protobufjs/cli/node_modules/inflight/inflight.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/inflight/inflight'>;
}
declare module 'protobufjs/cli/node_modules/inherits/inherits_browser.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/inherits/inherits_browser'>;
}
declare module 'protobufjs/cli/node_modules/inherits/inherits.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/inherits/inherits'>;
}
declare module 'protobufjs/cli/node_modules/levn/lib/cast.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/levn/lib/cast'>;
}
declare module 'protobufjs/cli/node_modules/levn/lib/coerce.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/levn/lib/coerce'>;
}
declare module 'protobufjs/cli/node_modules/levn/lib/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/levn/lib'>;
}
declare module 'protobufjs/cli/node_modules/levn/lib/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/levn/lib'>;
}
declare module 'protobufjs/cli/node_modules/levn/lib/parse-string.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/levn/lib/parse-string'>;
}
declare module 'protobufjs/cli/node_modules/levn/lib/parse.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/levn/lib/parse'>;
}
declare module 'protobufjs/cli/node_modules/minimatch/minimatch.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/minimatch/minimatch'>;
}
declare module 'protobufjs/cli/node_modules/once/once.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/once/once'>;
}
declare module 'protobufjs/cli/node_modules/optionator/lib/help.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/optionator/lib/help'>;
}
declare module 'protobufjs/cli/node_modules/optionator/lib/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/optionator/lib'>;
}
declare module 'protobufjs/cli/node_modules/optionator/lib/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/optionator/lib'>;
}
declare module 'protobufjs/cli/node_modules/optionator/lib/util.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/optionator/lib/util'>;
}
declare module 'protobufjs/cli/node_modules/path-is-absolute/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/path-is-absolute'>;
}
declare module 'protobufjs/cli/node_modules/path-is-absolute/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/path-is-absolute'>;
}
declare module 'protobufjs/cli/node_modules/prelude-ls/lib/Func.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/prelude-ls/lib/Func'>;
}
declare module 'protobufjs/cli/node_modules/prelude-ls/lib/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/prelude-ls/lib'>;
}
declare module 'protobufjs/cli/node_modules/prelude-ls/lib/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/prelude-ls/lib'>;
}
declare module 'protobufjs/cli/node_modules/prelude-ls/lib/List.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/prelude-ls/lib/List'>;
}
declare module 'protobufjs/cli/node_modules/prelude-ls/lib/Num.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/prelude-ls/lib/Num'>;
}
declare module 'protobufjs/cli/node_modules/prelude-ls/lib/Obj.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/prelude-ls/lib/Obj'>;
}
declare module 'protobufjs/cli/node_modules/prelude-ls/lib/Str.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/prelude-ls/lib/Str'>;
}
declare module 'protobufjs/cli/node_modules/rimraf/bin.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/rimraf/bin'>;
}
declare module 'protobufjs/cli/node_modules/rimraf/rimraf.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/rimraf/rimraf'>;
}
declare module 'protobufjs/cli/node_modules/source-map/dist/source-map.debug.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/dist/source-map.debug'>;
}
declare module 'protobufjs/cli/node_modules/source-map/dist/source-map.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/dist/source-map'>;
}
declare module 'protobufjs/cli/node_modules/source-map/dist/source-map.min.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/dist/source-map.min'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/array-set.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/array-set'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/base64-vlq.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/base64-vlq'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/base64.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/base64'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/binary-search.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/binary-search'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/mapping-list.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/mapping-list'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/quick-sort.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/quick-sort'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/source-map-consumer.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/source-map-consumer'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/source-map-generator.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/source-map-generator'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/source-node.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/source-node'>;
}
declare module 'protobufjs/cli/node_modules/source-map/lib/util.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/lib/util'>;
}
declare module 'protobufjs/cli/node_modules/source-map/source-map.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/source-map/source-map'>;
}
declare module 'protobufjs/cli/node_modules/tmp/lib/tmp.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/tmp/lib/tmp'>;
}
declare module 'protobufjs/cli/node_modules/type-check/lib/check.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/type-check/lib/check'>;
}
declare module 'protobufjs/cli/node_modules/type-check/lib/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/type-check/lib'>;
}
declare module 'protobufjs/cli/node_modules/type-check/lib/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/type-check/lib'>;
}
declare module 'protobufjs/cli/node_modules/type-check/lib/parse-type.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/type-check/lib/parse-type'>;
}
declare module 'protobufjs/cli/node_modules/word-wrap/index' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/word-wrap'>;
}
declare module 'protobufjs/cli/node_modules/word-wrap/index.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/word-wrap'>;
}
declare module 'protobufjs/cli/node_modules/wrappy/wrappy.js' {
  declare module.exports: $Exports<'protobufjs/cli/node_modules/wrappy/wrappy'>;
}
declare module 'protobufjs/cli/pbjs.js' {
  declare module.exports: $Exports<'protobufjs/cli/pbjs'>;
}
declare module 'protobufjs/cli/pbts.js' {
  declare module.exports: $Exports<'protobufjs/cli/pbts'>;
}
declare module 'protobufjs/cli/targets/json-module.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/json-module'>;
}
declare module 'protobufjs/cli/targets/json.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/json'>;
}
declare module 'protobufjs/cli/targets/proto.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/proto'>;
}
declare module 'protobufjs/cli/targets/proto2.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/proto2'>;
}
declare module 'protobufjs/cli/targets/proto3.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/proto3'>;
}
declare module 'protobufjs/cli/targets/static-module.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/static-module'>;
}
declare module 'protobufjs/cli/targets/static.js' {
  declare module.exports: $Exports<'protobufjs/cli/targets/static'>;
}
declare module 'protobufjs/cli/util.js' {
  declare module.exports: $Exports<'protobufjs/cli/util'>;
}
declare module 'protobufjs/cli/wrappers/amd.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/amd'>;
}
declare module 'protobufjs/cli/wrappers/closure.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/closure'>;
}
declare module 'protobufjs/cli/wrappers/commonjs.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/commonjs'>;
}
declare module 'protobufjs/cli/wrappers/default.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/default'>;
}
declare module 'protobufjs/cli/wrappers/es6.js' {
  declare module.exports: $Exports<'protobufjs/cli/wrappers/es6'>;
}
declare module 'protobufjs/dist/light/protobuf.js' {
  declare module.exports: $Exports<'protobufjs/dist/light/protobuf'>;
}
declare module 'protobufjs/dist/light/protobuf.min.js' {
  declare module.exports: $Exports<'protobufjs/dist/light/protobuf.min'>;
}
declare module 'protobufjs/dist/minimal/protobuf.js' {
  declare module.exports: $Exports<'protobufjs/dist/minimal/protobuf'>;
}
declare module 'protobufjs/dist/minimal/protobuf.min.js' {
  declare module.exports: $Exports<'protobufjs/dist/minimal/protobuf.min'>;
}
declare module 'protobufjs/dist/protobuf.js' {
  declare module.exports: $Exports<'protobufjs/dist/protobuf'>;
}
declare module 'protobufjs/dist/protobuf.min.js' {
  declare module.exports: $Exports<'protobufjs/dist/protobuf.min'>;
}
declare module 'protobufjs/ext/debug/index' {
  declare module.exports: $Exports<'protobufjs/ext/debug'>;
}
declare module 'protobufjs/ext/debug/index.js' {
  declare module.exports: $Exports<'protobufjs/ext/debug'>;
}
declare module 'protobufjs/ext/descriptor/index' {
  declare module.exports: $Exports<'protobufjs/ext/descriptor'>;
}
declare module 'protobufjs/ext/descriptor/index.js' {
  declare module.exports: $Exports<'protobufjs/ext/descriptor'>;
}
declare module 'protobufjs/ext/descriptor/test.js' {
  declare module.exports: $Exports<'protobufjs/ext/descriptor/test'>;
}
declare module 'protobufjs/index' {
  declare module.exports: $Exports<'protobufjs'>;
}
declare module 'protobufjs/index.js' {
  declare module.exports: $Exports<'protobufjs'>;
}
declare module 'protobufjs/light.js' {
  declare module.exports: $Exports<'protobufjs/light'>;
}
declare module 'protobufjs/minimal.js' {
  declare module.exports: $Exports<'protobufjs/minimal'>;
}
declare module 'protobufjs/scripts/postinstall.js' {
  declare module.exports: $Exports<'protobufjs/scripts/postinstall'>;
}
declare module 'protobufjs/src/common.js' {
  declare module.exports: $Exports<'protobufjs/src/common'>;
}
declare module 'protobufjs/src/converter.js' {
  declare module.exports: $Exports<'protobufjs/src/converter'>;
}
declare module 'protobufjs/src/decoder.js' {
  declare module.exports: $Exports<'protobufjs/src/decoder'>;
}
declare module 'protobufjs/src/encoder.js' {
  declare module.exports: $Exports<'protobufjs/src/encoder'>;
}
declare module 'protobufjs/src/enum.js' {
  declare module.exports: $Exports<'protobufjs/src/enum'>;
}
declare module 'protobufjs/src/field.js' {
  declare module.exports: $Exports<'protobufjs/src/field'>;
}
declare module 'protobufjs/src/index-light.js' {
  declare module.exports: $Exports<'protobufjs/src/index-light'>;
}
declare module 'protobufjs/src/index-minimal.js' {
  declare module.exports: $Exports<'protobufjs/src/index-minimal'>;
}
declare module 'protobufjs/src/index' {
  declare module.exports: $Exports<'protobufjs/src'>;
}
declare module 'protobufjs/src/index.js' {
  declare module.exports: $Exports<'protobufjs/src'>;
}
declare module 'protobufjs/src/mapfield.js' {
  declare module.exports: $Exports<'protobufjs/src/mapfield'>;
}
declare module 'protobufjs/src/message.js' {
  declare module.exports: $Exports<'protobufjs/src/message'>;
}
declare module 'protobufjs/src/method.js' {
  declare module.exports: $Exports<'protobufjs/src/method'>;
}
declare module 'protobufjs/src/namespace.js' {
  declare module.exports: $Exports<'protobufjs/src/namespace'>;
}
declare module 'protobufjs/src/object.js' {
  declare module.exports: $Exports<'protobufjs/src/object'>;
}
declare module 'protobufjs/src/oneof.js' {
  declare module.exports: $Exports<'protobufjs/src/oneof'>;
}
declare module 'protobufjs/src/parse.js' {
  declare module.exports: $Exports<'protobufjs/src/parse'>;
}
declare module 'protobufjs/src/reader_buffer.js' {
  declare module.exports: $Exports<'protobufjs/src/reader_buffer'>;
}
declare module 'protobufjs/src/reader.js' {
  declare module.exports: $Exports<'protobufjs/src/reader'>;
}
declare module 'protobufjs/src/root.js' {
  declare module.exports: $Exports<'protobufjs/src/root'>;
}
declare module 'protobufjs/src/roots.js' {
  declare module.exports: $Exports<'protobufjs/src/roots'>;
}
declare module 'protobufjs/src/rpc.js' {
  declare module.exports: $Exports<'protobufjs/src/rpc'>;
}
declare module 'protobufjs/src/rpc/service.js' {
  declare module.exports: $Exports<'protobufjs/src/rpc/service'>;
}
declare module 'protobufjs/src/service.js' {
  declare module.exports: $Exports<'protobufjs/src/service'>;
}
declare module 'protobufjs/src/tokenize.js' {
  declare module.exports: $Exports<'protobufjs/src/tokenize'>;
}
declare module 'protobufjs/src/type.js' {
  declare module.exports: $Exports<'protobufjs/src/type'>;
}
declare module 'protobufjs/src/types.js' {
  declare module.exports: $Exports<'protobufjs/src/types'>;
}
declare module 'protobufjs/src/util.js' {
  declare module.exports: $Exports<'protobufjs/src/util'>;
}
declare module 'protobufjs/src/util/longbits.js' {
  declare module.exports: $Exports<'protobufjs/src/util/longbits'>;
}
declare module 'protobufjs/src/util/minimal.js' {
  declare module.exports: $Exports<'protobufjs/src/util/minimal'>;
}
declare module 'protobufjs/src/verifier.js' {
  declare module.exports: $Exports<'protobufjs/src/verifier'>;
}
declare module 'protobufjs/src/wrappers.js' {
  declare module.exports: $Exports<'protobufjs/src/wrappers'>;
}
declare module 'protobufjs/src/writer_buffer.js' {
  declare module.exports: $Exports<'protobufjs/src/writer_buffer'>;
}
declare module 'protobufjs/src/writer.js' {
  declare module.exports: $Exports<'protobufjs/src/writer'>;
}
