// flow-typed signature: a898acc035a0ea12b107f1d42db08a6b
// flow-typed version: <<STUB>>/pryvuser-cli_vfile:components/pryvuser-cli/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pryvuser-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pryvuser-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pryvuser-cli/src/app' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/configuration' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/connection_manager' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/connection/file_store' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/connection/influxdb' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/connection/mongodb' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/connection/registry' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/sub/delete' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/acceptance/cli.test' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/acceptance/sub/delete.test' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/test-helpers' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/unit/configuration.test' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/unit/connection/file_store.test' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/unit/connection/influxdb.test' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/unit/connection/mongodb.test' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/unit/connection/registry.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pryvuser-cli/src/app.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/app'>;
}
declare module 'pryvuser-cli/src/configuration.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/configuration'>;
}
declare module 'pryvuser-cli/src/connection_manager.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/connection_manager'>;
}
declare module 'pryvuser-cli/src/connection/file_store.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/connection/file_store'>;
}
declare module 'pryvuser-cli/src/connection/influxdb.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/connection/influxdb'>;
}
declare module 'pryvuser-cli/src/connection/mongodb.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/connection/mongodb'>;
}
declare module 'pryvuser-cli/src/connection/registry.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/connection/registry'>;
}
declare module 'pryvuser-cli/src/sub/delete.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/sub/delete'>;
}
declare module 'pryvuser-cli/test/acceptance/cli.test.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/acceptance/cli.test'>;
}
declare module 'pryvuser-cli/test/acceptance/sub/delete.test.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/acceptance/sub/delete.test'>;
}
declare module 'pryvuser-cli/test/test-helpers.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/test-helpers'>;
}
declare module 'pryvuser-cli/test/unit/configuration.test.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/unit/configuration.test'>;
}
declare module 'pryvuser-cli/test/unit/connection/file_store.test.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/unit/connection/file_store.test'>;
}
declare module 'pryvuser-cli/test/unit/connection/influxdb.test.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/unit/connection/influxdb.test'>;
}
declare module 'pryvuser-cli/test/unit/connection/mongodb.test.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/unit/connection/mongodb.test'>;
}
declare module 'pryvuser-cli/test/unit/connection/registry.test.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/unit/connection/registry.test'>;
}
