// flow-typed signature: b017530f07655cbaad0f3970094ae2fc
// flow-typed version: <<STUB>>/pryvuser-cli_vfile:components/pryvuser-cli/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pryvuser-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pryvuser-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pryvuser-cli/src/cli' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/commands/delete' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/src/utils/output' {
  declare module.exports: any;
}

declare module 'pryvuser-cli/test/delete-user.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pryvuser-cli/src/cli.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/cli'>;
}
declare module 'pryvuser-cli/src/commands/delete.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/commands/delete'>;
}
declare module 'pryvuser-cli/src/utils/output.js' {
  declare module.exports: $Exports<'pryvuser-cli/src/utils/output'>;
}
declare module 'pryvuser-cli/test/delete-user.test.js' {
  declare module.exports: $Exports<'pryvuser-cli/test/delete-user.test'>;
}
