/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 7705e92daff2d7a4b9b1efae6d582b08
// flow-typed version: <<STUB>>/should_v^11.2.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'should'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'should' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'should/as-function' {
  declare module.exports: any;
}

declare module 'should/cjs/should' {
  declare module.exports: any;
}

declare module 'should/es6/should' {
  declare module.exports: any;
}

declare module 'should/should' {
  declare module.exports: any;
}

// Filename aliases
declare module 'should/as-function.js' {
  declare module.exports: $Exports<'should/as-function'>;
}
declare module 'should/cjs/should.js' {
  declare module.exports: $Exports<'should/cjs/should'>;
}
declare module 'should/es6/should.js' {
  declare module.exports: $Exports<'should/es6/should'>;
}
declare module 'should/index' {
  declare module.exports: $Exports<'should'>;
}
declare module 'should/index.js' {
  declare module.exports: $Exports<'should'>;
}
declare module 'should/should.js' {
  declare module.exports: $Exports<'should/should'>;
}
