// flow-typed signature: aadc1242e9382aa634f6216070c71def
// flow-typed version: <<STUB>>/slug_v^5.3.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slug/slug' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slug/slug.js' {
  declare module.exports: $Exports<'slug/slug'>;
}
