// flow-typed signature: 54585dbd00d1425a66e34e62f369cff3
// flow-typed version: <<STUB>>/socket.io-client_v0.9.x/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socket.io-client/bin/builder' {
  declare module.exports: any;
}

declare module 'socket.io-client/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io.min' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/events' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/io' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/json' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/namespace' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/parser' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/socket' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/transport' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/transports/flashsocket' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/transports/htmlfile' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/transports/jsonp-polling' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/transports/websocket' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/transports/xhr-polling' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/transports/xhr' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/util' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/vendor/web-socket-js/swfobject' {
  declare module.exports: any;
}

declare module 'socket.io-client/lib/vendor/web-socket-js/web_socket' {
  declare module.exports: any;
}

declare module 'socket.io-client/test/events.test' {
  declare module.exports: any;
}

declare module 'socket.io-client/test/io.test' {
  declare module.exports: any;
}

declare module 'socket.io-client/test/node/builder.common' {
  declare module.exports: any;
}

declare module 'socket.io-client/test/node/builder.test' {
  declare module.exports: any;
}

declare module 'socket.io-client/test/parser.test' {
  declare module.exports: any;
}

declare module 'socket.io-client/test/socket.test' {
  declare module.exports: any;
}

declare module 'socket.io-client/test/util.test' {
  declare module.exports: any;
}

declare module 'socket.io-client/test/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socket.io-client/bin/builder.js' {
  declare module.exports: $Exports<'socket.io-client/bin/builder'>;
}
declare module 'socket.io-client/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'socket.io-client/coverage/lcov-report/prettify'>;
}
declare module 'socket.io-client/dist/socket.io.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io'>;
}
declare module 'socket.io-client/dist/socket.io.min.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io.min'>;
}
declare module 'socket.io-client/lib/events.js' {
  declare module.exports: $Exports<'socket.io-client/lib/events'>;
}
declare module 'socket.io-client/lib/io.js' {
  declare module.exports: $Exports<'socket.io-client/lib/io'>;
}
declare module 'socket.io-client/lib/json.js' {
  declare module.exports: $Exports<'socket.io-client/lib/json'>;
}
declare module 'socket.io-client/lib/namespace.js' {
  declare module.exports: $Exports<'socket.io-client/lib/namespace'>;
}
declare module 'socket.io-client/lib/parser.js' {
  declare module.exports: $Exports<'socket.io-client/lib/parser'>;
}
declare module 'socket.io-client/lib/socket.js' {
  declare module.exports: $Exports<'socket.io-client/lib/socket'>;
}
declare module 'socket.io-client/lib/transport.js' {
  declare module.exports: $Exports<'socket.io-client/lib/transport'>;
}
declare module 'socket.io-client/lib/transports/flashsocket.js' {
  declare module.exports: $Exports<'socket.io-client/lib/transports/flashsocket'>;
}
declare module 'socket.io-client/lib/transports/htmlfile.js' {
  declare module.exports: $Exports<'socket.io-client/lib/transports/htmlfile'>;
}
declare module 'socket.io-client/lib/transports/jsonp-polling.js' {
  declare module.exports: $Exports<'socket.io-client/lib/transports/jsonp-polling'>;
}
declare module 'socket.io-client/lib/transports/websocket.js' {
  declare module.exports: $Exports<'socket.io-client/lib/transports/websocket'>;
}
declare module 'socket.io-client/lib/transports/xhr-polling.js' {
  declare module.exports: $Exports<'socket.io-client/lib/transports/xhr-polling'>;
}
declare module 'socket.io-client/lib/transports/xhr.js' {
  declare module.exports: $Exports<'socket.io-client/lib/transports/xhr'>;
}
declare module 'socket.io-client/lib/util.js' {
  declare module.exports: $Exports<'socket.io-client/lib/util'>;
}
declare module 'socket.io-client/lib/vendor/web-socket-js/swfobject.js' {
  declare module.exports: $Exports<'socket.io-client/lib/vendor/web-socket-js/swfobject'>;
}
declare module 'socket.io-client/lib/vendor/web-socket-js/web_socket.js' {
  declare module.exports: $Exports<'socket.io-client/lib/vendor/web-socket-js/web_socket'>;
}
declare module 'socket.io-client/test/events.test.js' {
  declare module.exports: $Exports<'socket.io-client/test/events.test'>;
}
declare module 'socket.io-client/test/io.test.js' {
  declare module.exports: $Exports<'socket.io-client/test/io.test'>;
}
declare module 'socket.io-client/test/node/builder.common.js' {
  declare module.exports: $Exports<'socket.io-client/test/node/builder.common'>;
}
declare module 'socket.io-client/test/node/builder.test.js' {
  declare module.exports: $Exports<'socket.io-client/test/node/builder.test'>;
}
declare module 'socket.io-client/test/parser.test.js' {
  declare module.exports: $Exports<'socket.io-client/test/parser.test'>;
}
declare module 'socket.io-client/test/socket.test.js' {
  declare module.exports: $Exports<'socket.io-client/test/socket.test'>;
}
declare module 'socket.io-client/test/util.test.js' {
  declare module.exports: $Exports<'socket.io-client/test/util.test'>;
}
declare module 'socket.io-client/test/worker.js' {
  declare module.exports: $Exports<'socket.io-client/test/worker'>;
}
