// flow-typed signature: c79d580e90913f6ceb79bae6f911b643
// flow-typed version: <<STUB>>/socket.io_v^3.1.2/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socket.io/client-dist/socket.io' {
  declare module.exports: any;
}

declare module 'socket.io/client-dist/socket.io.min' {
  declare module.exports: any;
}

declare module 'socket.io/client-dist/socket.io.msgpack.min' {
  declare module.exports: any;
}

declare module 'socket.io/dist/client' {
  declare module.exports: any;
}

declare module 'socket.io/dist' {
  declare module.exports: any;
}

declare module 'socket.io/dist/namespace' {
  declare module.exports: any;
}

declare module 'socket.io/dist/parent-namespace' {
  declare module.exports: any;
}

declare module 'socket.io/dist/socket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socket.io/client-dist/socket.io.js' {
  declare module.exports: $Exports<'socket.io/client-dist/socket.io'>;
}
declare module 'socket.io/client-dist/socket.io.min.js' {
  declare module.exports: $Exports<'socket.io/client-dist/socket.io.min'>;
}
declare module 'socket.io/client-dist/socket.io.msgpack.min.js' {
  declare module.exports: $Exports<'socket.io/client-dist/socket.io.msgpack.min'>;
}
declare module 'socket.io/dist/client.js' {
  declare module.exports: $Exports<'socket.io/dist/client'>;
}
declare module 'socket.io/dist/index' {
  declare module.exports: $Exports<'socket.io/dist'>;
}
declare module 'socket.io/dist/index.js' {
  declare module.exports: $Exports<'socket.io/dist'>;
}
declare module 'socket.io/dist/namespace.js' {
  declare module.exports: $Exports<'socket.io/dist/namespace'>;
}
declare module 'socket.io/dist/parent-namespace.js' {
  declare module.exports: $Exports<'socket.io/dist/parent-namespace'>;
}
declare module 'socket.io/dist/socket.js' {
  declare module.exports: $Exports<'socket.io/dist/socket'>;
}
