// flow-typed signature: 67a86480671a31e1a5e8fa597a14413c
// flow-typed version: <<STUB>>/source-licenser_v^2.0.3/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-licenser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-licenser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-licenser/src/actions/action' {
  declare module.exports: any;
}

declare module 'source-licenser/src/actions/footer' {
  declare module.exports: any;
}

declare module 'source-licenser/src/actions/header' {
  declare module.exports: any;
}

declare module 'source-licenser/src/actions' {
  declare module.exports: any;
}

declare module 'source-licenser/src/actions/json' {
  declare module.exports: any;
}

declare module 'source-licenser/src/actions/siblingLicenseFile' {
  declare module.exports: any;
}

declare module 'source-licenser/src/actions/textAction' {
  declare module.exports: any;
}

declare module 'source-licenser/src/loadConfig' {
  declare module.exports: any;
}

declare module 'source-licenser/src/logger' {
  declare module.exports: any;
}

declare module 'source-licenser/src/main' {
  declare module.exports: any;
}

declare module 'source-licenser/src/substitutions' {
  declare module.exports: any;
}

declare module 'source-licenser/test/fixtures/expected-results/header-existing' {
  declare module.exports: any;
}

declare module 'source-licenser/test/fixtures/expected-results/header-none' {
  declare module.exports: any;
}

declare module 'source-licenser/test/fixtures/expected-results/ignore-me/some-module' {
  declare module.exports: any;
}

declare module 'source-licenser/test/fixtures/source/header-existing' {
  declare module.exports: any;
}

declare module 'source-licenser/test/fixtures/source/header-none' {
  declare module.exports: any;
}

declare module 'source-licenser/test/fixtures/source/ignore-me/some-module' {
  declare module.exports: any;
}

declare module 'source-licenser/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-licenser/src/actions/action.js' {
  declare module.exports: $Exports<'source-licenser/src/actions/action'>;
}
declare module 'source-licenser/src/actions/footer.js' {
  declare module.exports: $Exports<'source-licenser/src/actions/footer'>;
}
declare module 'source-licenser/src/actions/header.js' {
  declare module.exports: $Exports<'source-licenser/src/actions/header'>;
}
declare module 'source-licenser/src/actions/index' {
  declare module.exports: $Exports<'source-licenser/src/actions'>;
}
declare module 'source-licenser/src/actions/index.js' {
  declare module.exports: $Exports<'source-licenser/src/actions'>;
}
declare module 'source-licenser/src/actions/json.js' {
  declare module.exports: $Exports<'source-licenser/src/actions/json'>;
}
declare module 'source-licenser/src/actions/siblingLicenseFile.js' {
  declare module.exports: $Exports<'source-licenser/src/actions/siblingLicenseFile'>;
}
declare module 'source-licenser/src/actions/textAction.js' {
  declare module.exports: $Exports<'source-licenser/src/actions/textAction'>;
}
declare module 'source-licenser/src/loadConfig.js' {
  declare module.exports: $Exports<'source-licenser/src/loadConfig'>;
}
declare module 'source-licenser/src/logger.js' {
  declare module.exports: $Exports<'source-licenser/src/logger'>;
}
declare module 'source-licenser/src/main.js' {
  declare module.exports: $Exports<'source-licenser/src/main'>;
}
declare module 'source-licenser/src/substitutions.js' {
  declare module.exports: $Exports<'source-licenser/src/substitutions'>;
}
declare module 'source-licenser/test/fixtures/expected-results/header-existing.js' {
  declare module.exports: $Exports<'source-licenser/test/fixtures/expected-results/header-existing'>;
}
declare module 'source-licenser/test/fixtures/expected-results/header-none.js' {
  declare module.exports: $Exports<'source-licenser/test/fixtures/expected-results/header-none'>;
}
declare module 'source-licenser/test/fixtures/expected-results/ignore-me/some-module.js' {
  declare module.exports: $Exports<'source-licenser/test/fixtures/expected-results/ignore-me/some-module'>;
}
declare module 'source-licenser/test/fixtures/source/header-existing.js' {
  declare module.exports: $Exports<'source-licenser/test/fixtures/source/header-existing'>;
}
declare module 'source-licenser/test/fixtures/source/header-none.js' {
  declare module.exports: $Exports<'source-licenser/test/fixtures/source/header-none'>;
}
declare module 'source-licenser/test/fixtures/source/ignore-me/some-module.js' {
  declare module.exports: $Exports<'source-licenser/test/fixtures/source/ignore-me/some-module'>;
}
declare module 'source-licenser/test/test.js' {
  declare module.exports: $Exports<'source-licenser/test/test'>;
}
