/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 5ea685fbe5dfaaf5e53fac480c83c0f3
// flow-typed version: <<STUB>>/storage_vfile:components/storage/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storage/src/ApplyEventsFromDbStream' {
  declare module.exports: any;
}

declare module 'storage/src/converters' {
  declare module.exports: any;
}

declare module 'storage/src/Database' {
  declare module.exports: any;
}

declare module 'storage/src' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/0.2.0' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/0.3.0' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/0.4.0' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/0.5.0' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/0.7.0' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/0.7.1' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/1.2.0' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/1.2.5' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/1.3.40' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/1.4.0' {
  declare module.exports: any;
}

declare module 'storage/src/migrations' {
  declare module.exports: any;
}

declare module 'storage/src/migrations/MigrationContext' {
  declare module.exports: any;
}

declare module 'storage/src/PasswordResetRequests' {
  declare module.exports: any;
}

declare module 'storage/src/Sessions' {
  declare module.exports: any;
}

declare module 'storage/src/Size' {
  declare module.exports: any;
}

declare module 'storage/src/storage_layer' {
  declare module.exports: any;
}

declare module 'storage/src/user/Accesses' {
  declare module.exports: any;
}

declare module 'storage/src/user/BaseStorage' {
  declare module.exports: any;
}

declare module 'storage/src/user/EventFiles' {
  declare module.exports: any;
}

declare module 'storage/src/user/Events' {
  declare module.exports: any;
}

declare module 'storage/src/user/FollowedSlices' {
  declare module.exports: any;
}

declare module 'storage/src/user/Profile' {
  declare module.exports: any;
}

declare module 'storage/src/user/Streams' {
  declare module.exports: any;
}

declare module 'storage/src/user/Webhooks' {
  declare module.exports: any;
}

declare module 'storage/src/Users' {
  declare module.exports: any;
}

declare module 'storage/src/Versions' {
  declare module.exports: any;
}

declare module 'storage/test/unit/database.test' {
  declare module.exports: any;
}

declare module 'storage/test/Versions.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storage/src/ApplyEventsFromDbStream.js' {
  declare module.exports: $Exports<'storage/src/ApplyEventsFromDbStream'>;
}
declare module 'storage/src/converters.js' {
  declare module.exports: $Exports<'storage/src/converters'>;
}
declare module 'storage/src/Database.js' {
  declare module.exports: $Exports<'storage/src/Database'>;
}
declare module 'storage/src/index' {
  declare module.exports: $Exports<'storage/src'>;
}
declare module 'storage/src/index.js' {
  declare module.exports: $Exports<'storage/src'>;
}
declare module 'storage/src/migrations/0.2.0.js' {
  declare module.exports: $Exports<'storage/src/migrations/0.2.0'>;
}
declare module 'storage/src/migrations/0.3.0.js' {
  declare module.exports: $Exports<'storage/src/migrations/0.3.0'>;
}
declare module 'storage/src/migrations/0.4.0.js' {
  declare module.exports: $Exports<'storage/src/migrations/0.4.0'>;
}
declare module 'storage/src/migrations/0.5.0.js' {
  declare module.exports: $Exports<'storage/src/migrations/0.5.0'>;
}
declare module 'storage/src/migrations/0.7.0.js' {
  declare module.exports: $Exports<'storage/src/migrations/0.7.0'>;
}
declare module 'storage/src/migrations/0.7.1.js' {
  declare module.exports: $Exports<'storage/src/migrations/0.7.1'>;
}
declare module 'storage/src/migrations/1.2.0.js' {
  declare module.exports: $Exports<'storage/src/migrations/1.2.0'>;
}
declare module 'storage/src/migrations/1.2.5.js' {
  declare module.exports: $Exports<'storage/src/migrations/1.2.5'>;
}
declare module 'storage/src/migrations/1.3.40.js' {
  declare module.exports: $Exports<'storage/src/migrations/1.3.40'>;
}
declare module 'storage/src/migrations/1.4.0.js' {
  declare module.exports: $Exports<'storage/src/migrations/1.4.0'>;
}
declare module 'storage/src/migrations/index' {
  declare module.exports: $Exports<'storage/src/migrations'>;
}
declare module 'storage/src/migrations/index.js' {
  declare module.exports: $Exports<'storage/src/migrations'>;
}
declare module 'storage/src/migrations/MigrationContext.js' {
  declare module.exports: $Exports<'storage/src/migrations/MigrationContext'>;
}
declare module 'storage/src/PasswordResetRequests.js' {
  declare module.exports: $Exports<'storage/src/PasswordResetRequests'>;
}
declare module 'storage/src/Sessions.js' {
  declare module.exports: $Exports<'storage/src/Sessions'>;
}
declare module 'storage/src/Size.js' {
  declare module.exports: $Exports<'storage/src/Size'>;
}
declare module 'storage/src/storage_layer.js' {
  declare module.exports: $Exports<'storage/src/storage_layer'>;
}
declare module 'storage/src/user/Accesses.js' {
  declare module.exports: $Exports<'storage/src/user/Accesses'>;
}
declare module 'storage/src/user/BaseStorage.js' {
  declare module.exports: $Exports<'storage/src/user/BaseStorage'>;
}
declare module 'storage/src/user/EventFiles.js' {
  declare module.exports: $Exports<'storage/src/user/EventFiles'>;
}
declare module 'storage/src/user/Events.js' {
  declare module.exports: $Exports<'storage/src/user/Events'>;
}
declare module 'storage/src/user/FollowedSlices.js' {
  declare module.exports: $Exports<'storage/src/user/FollowedSlices'>;
}
declare module 'storage/src/user/Profile.js' {
  declare module.exports: $Exports<'storage/src/user/Profile'>;
}
declare module 'storage/src/user/Streams.js' {
  declare module.exports: $Exports<'storage/src/user/Streams'>;
}
declare module 'storage/src/user/Webhooks.js' {
  declare module.exports: $Exports<'storage/src/user/Webhooks'>;
}
declare module 'storage/src/Users.js' {
  declare module.exports: $Exports<'storage/src/Users'>;
}
declare module 'storage/src/Versions.js' {
  declare module.exports: $Exports<'storage/src/Versions'>;
}
declare module 'storage/test/unit/database.test.js' {
  declare module.exports: $Exports<'storage/test/unit/database.test'>;
}
declare module 'storage/test/Versions.test.js' {
  declare module.exports: $Exports<'storage/test/Versions.test'>;
}
