// flow-typed signature: 0b773cde8a6c85545b9fc2de894763a7
// flow-typed version: <<STUB>>/tchannel_vhttps://github.com/pryv/tchannel-node#v4.0.2/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tchannel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tchannel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tchannel/argstream' {
  declare module.exports: any;
}

declare module 'tchannel/as/http' {
  declare module.exports: any;
}

declare module 'tchannel/as/json' {
  declare module.exports: any;
}

declare module 'tchannel/as/thrift' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/bench_server' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/compare' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/d8_peer_heap' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/http' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/micro/reading-all-important-fields' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/micro/reading-arg1-str' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/micro/reading-caller-name-str' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/micro/reading-service-name-str' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/micro/reading-tracing-value' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/multi_bench' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/peer_heap' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/random_sample' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/read-bench-config' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/relay_server' {
  declare module.exports: any;
}

declare module 'tchannel/benchmarks/trace_server' {
  declare module.exports: any;
}

declare module 'tchannel/bin/adhoc-multi' {
  declare module.exports: any;
}

declare module 'tchannel/bin/adhoc' {
  declare module.exports: any;
}

declare module 'tchannel/channel' {
  declare module.exports: any;
}

declare module 'tchannel/connection' {
  declare module.exports: any;
}

declare module 'tchannel/drain' {
  declare module.exports: any;
}

declare module 'tchannel/endpoint-handler' {
  declare module.exports: any;
}

declare module 'tchannel/errors' {
  declare module.exports: any;
}

declare module 'tchannel/examples/as_example1' {
  declare module.exports: any;
}

declare module 'tchannel/examples/as-thrift' {
  declare module.exports: any;
}

declare module 'tchannel/examples/example1' {
  declare module.exports: any;
}

declare module 'tchannel/examples/example2' {
  declare module.exports: any;
}

declare module 'tchannel/examples/http_egress' {
  declare module.exports: any;
}

declare module 'tchannel/examples/http_ingress' {
  declare module.exports: any;
}

declare module 'tchannel/examples/josh_test_client' {
  declare module.exports: any;
}

declare module 'tchannel/examples/josh_test_server' {
  declare module.exports: any;
}

declare module 'tchannel/examples/keyvalue/client' {
  declare module.exports: any;
}

declare module 'tchannel/examples/keyvalue/server' {
  declare module.exports: any;
}

declare module 'tchannel/examples/legacy_example' {
  declare module.exports: any;
}

declare module 'tchannel/examples/repl_client' {
  declare module.exports: any;
}

declare module 'tchannel/examples/repl_server' {
  declare module.exports: any;
}

declare module 'tchannel/examples/send_test' {
  declare module.exports: any;
}

declare module 'tchannel/examples/term_client' {
  declare module.exports: any;
}

declare module 'tchannel/examples/term_server' {
  declare module.exports: any;
}

declare module 'tchannel/host-port' {
  declare module.exports: any;
}

declare module 'tchannel/hyperbahn-client' {
  declare module.exports: any;
}

declare module 'tchannel/hyperbahn' {
  declare module.exports: any;
}

declare module 'tchannel/in_request' {
  declare module.exports: any;
}

declare module 'tchannel/in_response' {
  declare module.exports: any;
}

declare module 'tchannel/lazy_relay' {
  declare module.exports: any;
}

declare module 'tchannel/lib/event_emitter' {
  declare module.exports: any;
}

declare module 'tchannel/lib/lcg' {
  declare module.exports: any;
}

declare module 'tchannel/lib/multicast_ctl' {
  declare module.exports: any;
}

declare module 'tchannel/lib/object_pool' {
  declare module.exports: any;
}

declare module 'tchannel/lib/part-list' {
  declare module.exports: any;
}

declare module 'tchannel/lib/pipeline_streams' {
  declare module.exports: any;
}

declare module 'tchannel/lib/rate_counter' {
  declare module.exports: any;
}

declare module 'tchannel/lib/retry_ratio_tracker' {
  declare module.exports: any;
}

declare module 'tchannel/lib/statsd' {
  declare module.exports: any;
}

declare module 'tchannel/monitor' {
  declare module.exports: any;
}

declare module 'tchannel/null-logger' {
  declare module.exports: any;
}

declare module 'tchannel/operations' {
  declare module.exports: any;
}

declare module 'tchannel/out_request' {
  declare module.exports: any;
}

declare module 'tchannel/out_response' {
  declare module.exports: any;
}

declare module 'tchannel/peer_heap' {
  declare module.exports: any;
}

declare module 'tchannel/peer_score_strategies' {
  declare module.exports: any;
}

declare module 'tchannel/peer-file-watcher' {
  declare module.exports: any;
}

declare module 'tchannel/peer' {
  declare module.exports: any;
}

declare module 'tchannel/peers_base' {
  declare module.exports: any;
}

declare module 'tchannel/range' {
  declare module.exports: any;
}

declare module 'tchannel/relay_handler' {
  declare module.exports: any;
}

declare module 'tchannel/reqres_states' {
  declare module.exports: any;
}

declare module 'tchannel/request-handler' {
  declare module.exports: any;
}

declare module 'tchannel/request' {
  declare module.exports: any;
}

declare module 'tchannel/retry-flags' {
  declare module.exports: any;
}

declare module 'tchannel/root_peers' {
  declare module.exports: any;
}

declare module 'tchannel/scripts/xlang_test' {
  declare module.exports: any;
}

declare module 'tchannel/service-name-handler' {
  declare module.exports: any;
}

declare module 'tchannel/services' {
  declare module.exports: any;
}

declare module 'tchannel/stat-tags' {
  declare module.exports: any;
}

declare module 'tchannel/streaming_in_request' {
  declare module.exports: any;
}

declare module 'tchannel/streaming_in_response' {
  declare module.exports: any;
}

declare module 'tchannel/streaming_out_request' {
  declare module.exports: any;
}

declare module 'tchannel/streaming_out_response' {
  declare module.exports: any;
}

declare module 'tchannel/sub_peers' {
  declare module.exports: any;
}

declare module 'tchannel/tcollector/reporter' {
  declare module.exports: any;
}

declare module 'tchannel/test/argstream' {
  declare module.exports: any;
}

declare module 'tchannel/test/as-http' {
  declare module.exports: any;
}

declare module 'tchannel/test/as-json' {
  declare module.exports: any;
}

declare module 'tchannel/test/as-thrift' {
  declare module.exports: any;
}

declare module 'tchannel/test/balance_peer_requests' {
  declare module.exports: any;
}

declare module 'tchannel/test/busy' {
  declare module.exports: any;
}

declare module 'tchannel/test/chan_drain' {
  declare module.exports: any;
}

declare module 'tchannel/test/connection-stats' {
  declare module.exports: any;
}

declare module 'tchannel/test/connection-with-statsd' {
  declare module.exports: any;
}

declare module 'tchannel/test/double-response' {
  declare module.exports: any;
}

declare module 'tchannel/test/ephemeral-client' {
  declare module.exports: any;
}

declare module 'tchannel/test/errors' {
  declare module.exports: any;
}

declare module 'tchannel/test/event_emitter' {
  declare module.exports: any;
}

declare module 'tchannel/test/examples' {
  declare module.exports: any;
}

declare module 'tchannel/test/health' {
  declare module.exports: any;
}

declare module 'tchannel/test/hyperbahn-client/constructor' {
  declare module.exports: any;
}

declare module 'tchannel/test/hyperbahn-client/sub-channel' {
  declare module.exports: any;
}

declare module 'tchannel/test/hyperbahn-client/thrift-codec' {
  declare module.exports: any;
}

declare module 'tchannel/test/identify' {
  declare module.exports: any;
}

declare module 'tchannel/test' {
  declare module.exports: any;
}

declare module 'tchannel/test/large-send' {
  declare module.exports: any;
}

declare module 'tchannel/test/lazy_conn_handler' {
  declare module.exports: any;
}

declare module 'tchannel/test/lazy_handler' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/alloc-cluster' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/barplot' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/barrier' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/base2' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/batch-client' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/cluster_search' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/collapsed-assert' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/count_stream' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/iter_stream' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/load_config' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/peer_score_obs' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/raw_service' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/resource_pool' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/rng_stream' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/run_server' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/simple_validators' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/stream_check' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/stream_search' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/test_isolate_search' {
  declare module.exports: any;
}

declare module 'tchannel/test/lib/test_search' {
  declare module.exports: any;
}

declare module 'tchannel/test/max_pending' {
  declare module.exports: any;
}

declare module 'tchannel/test/max-call-overhead' {
  declare module.exports: any;
}

declare module 'tchannel/test/no_frag_arg1' {
  declare module.exports: any;
}

declare module 'tchannel/test/non-zero-ttl' {
  declare module.exports: any;
}

declare module 'tchannel/test/object_pool' {
  declare module.exports: any;
}

declare module 'tchannel/test/peer_drain' {
  declare module.exports: any;
}

declare module 'tchannel/test/peer_strategies' {
  declare module.exports: any;
}

declare module 'tchannel/test/peer-file-watcher' {
  declare module.exports: any;
}

declare module 'tchannel/test/peer-to-peer-load-balance' {
  declare module.exports: any;
}

declare module 'tchannel/test/peer' {
  declare module.exports: any;
}

declare module 'tchannel/test/peers' {
  declare module.exports: any;
}

declare module 'tchannel/test/ping' {
  declare module.exports: any;
}

declare module 'tchannel/test/pool-of-servers' {
  declare module.exports: any;
}

declare module 'tchannel/test/rate_counter' {
  declare module.exports: any;
}

declare module 'tchannel/test/register' {
  declare module.exports: any;
}

declare module 'tchannel/test/regression-conn-double-buildResponse' {
  declare module.exports: any;
}

declare module 'tchannel/test/regression-inOps-leak' {
  declare module.exports: any;
}

declare module 'tchannel/test/regression-listening-on-used-port' {
  declare module.exports: any;
}

declare module 'tchannel/test/relay_lazy' {
  declare module.exports: any;
}

declare module 'tchannel/test/relay-clamps-the-ttl' {
  declare module.exports: any;
}

declare module 'tchannel/test/relay-kills-socket-after-timeouts' {
  declare module.exports: any;
}

declare module 'tchannel/test/relay-stats' {
  declare module.exports: any;
}

declare module 'tchannel/test/relay-to-dead' {
  declare module.exports: any;
}

declare module 'tchannel/test/relay-under-timeouts' {
  declare module.exports: any;
}

declare module 'tchannel/test/relay' {
  declare module.exports: any;
}

declare module 'tchannel/test/request-error-context' {
  declare module.exports: any;
}

declare module 'tchannel/test/request-stats' {
  declare module.exports: any;
}

declare module 'tchannel/test/request-with-statsd' {
  declare module.exports: any;
}

declare module 'tchannel/test/response-stats' {
  declare module.exports: any;
}

declare module 'tchannel/test/response-with-statsd' {
  declare module.exports: any;
}

declare module 'tchannel/test/retry' {
  declare module.exports: any;
}

declare module 'tchannel/test/safe-quit' {
  declare module.exports: any;
}

declare module 'tchannel/test/send' {
  declare module.exports: any;
}

declare module 'tchannel/test/streaming_bisect' {
  declare module.exports: any;
}

declare module 'tchannel/test/streaming-resp-err' {
  declare module.exports: any;
}

declare module 'tchannel/test/streaming' {
  declare module.exports: any;
}

declare module 'tchannel/test/tchannel' {
  declare module.exports: any;
}

declare module 'tchannel/test/tcollector-reporter' {
  declare module.exports: any;
}

declare module 'tchannel/test/time_heap' {
  declare module.exports: any;
}

declare module 'tchannel/test/timeouts' {
  declare module.exports: any;
}

declare module 'tchannel/test/trace/basic_server' {
  declare module.exports: any;
}

declare module 'tchannel/test/trace/lib/basic_server_fixture' {
  declare module.exports: any;
}

declare module 'tchannel/test/trace/lib/server_2_requests_fixture' {
  declare module.exports: any;
}

declare module 'tchannel/test/trace/outpeer_span_handle' {
  declare module.exports: any;
}

declare module 'tchannel/test/trace/server_2_requests' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/args' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/call' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/cancel' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/checksum' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/claim' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/cont' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/error_response' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/frame' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/header' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/init' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/lazy_frame' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/lib/test_body' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/ping' {
  declare module.exports: any;
}

declare module 'tchannel/test/v2/tracing' {
  declare module.exports: any;
}

declare module 'tchannel/time_heap' {
  declare module.exports: any;
}

declare module 'tchannel/trace/agent' {
  declare module.exports: any;
}

declare module 'tchannel/trace/span' {
  declare module.exports: any;
}

declare module 'tchannel/v1/frame' {
  declare module.exports: any;
}

declare module 'tchannel/v1/handler' {
  declare module.exports: any;
}

declare module 'tchannel/v1/header' {
  declare module.exports: any;
}

declare module 'tchannel/v1' {
  declare module.exports: any;
}

declare module 'tchannel/v1/parser' {
  declare module.exports: any;
}

declare module 'tchannel/v2/args' {
  declare module.exports: any;
}

declare module 'tchannel/v2/call_flags' {
  declare module.exports: any;
}

declare module 'tchannel/v2/call' {
  declare module.exports: any;
}

declare module 'tchannel/v2/cancel' {
  declare module.exports: any;
}

declare module 'tchannel/v2/checksum' {
  declare module.exports: any;
}

declare module 'tchannel/v2/claim' {
  declare module.exports: any;
}

declare module 'tchannel/v2/cont' {
  declare module.exports: any;
}

declare module 'tchannel/v2/error_response' {
  declare module.exports: any;
}

declare module 'tchannel/v2/frame' {
  declare module.exports: any;
}

declare module 'tchannel/v2/handler' {
  declare module.exports: any;
}

declare module 'tchannel/v2/header' {
  declare module.exports: any;
}

declare module 'tchannel/v2' {
  declare module.exports: any;
}

declare module 'tchannel/v2/init' {
  declare module.exports: any;
}

declare module 'tchannel/v2/lazy_frame' {
  declare module.exports: any;
}

declare module 'tchannel/v2/out_request' {
  declare module.exports: any;
}

declare module 'tchannel/v2/out_response' {
  declare module.exports: any;
}

declare module 'tchannel/v2/ping' {
  declare module.exports: any;
}

declare module 'tchannel/v2/tracing' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tchannel/argstream.js' {
  declare module.exports: $Exports<'tchannel/argstream'>;
}
declare module 'tchannel/as/http.js' {
  declare module.exports: $Exports<'tchannel/as/http'>;
}
declare module 'tchannel/as/json.js' {
  declare module.exports: $Exports<'tchannel/as/json'>;
}
declare module 'tchannel/as/thrift.js' {
  declare module.exports: $Exports<'tchannel/as/thrift'>;
}
declare module 'tchannel/benchmarks/bench_server.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/bench_server'>;
}
declare module 'tchannel/benchmarks/compare.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/compare'>;
}
declare module 'tchannel/benchmarks/d8_peer_heap.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/d8_peer_heap'>;
}
declare module 'tchannel/benchmarks/http/index' {
  declare module.exports: $Exports<'tchannel/benchmarks/http'>;
}
declare module 'tchannel/benchmarks/http/index.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/http'>;
}
declare module 'tchannel/benchmarks/index' {
  declare module.exports: $Exports<'tchannel/benchmarks'>;
}
declare module 'tchannel/benchmarks/index.js' {
  declare module.exports: $Exports<'tchannel/benchmarks'>;
}
declare module 'tchannel/benchmarks/micro/reading-all-important-fields.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/micro/reading-all-important-fields'>;
}
declare module 'tchannel/benchmarks/micro/reading-arg1-str.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/micro/reading-arg1-str'>;
}
declare module 'tchannel/benchmarks/micro/reading-caller-name-str.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/micro/reading-caller-name-str'>;
}
declare module 'tchannel/benchmarks/micro/reading-service-name-str.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/micro/reading-service-name-str'>;
}
declare module 'tchannel/benchmarks/micro/reading-tracing-value.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/micro/reading-tracing-value'>;
}
declare module 'tchannel/benchmarks/multi_bench.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/multi_bench'>;
}
declare module 'tchannel/benchmarks/peer_heap.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/peer_heap'>;
}
declare module 'tchannel/benchmarks/random_sample.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/random_sample'>;
}
declare module 'tchannel/benchmarks/read-bench-config.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/read-bench-config'>;
}
declare module 'tchannel/benchmarks/relay_server.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/relay_server'>;
}
declare module 'tchannel/benchmarks/trace_server.js' {
  declare module.exports: $Exports<'tchannel/benchmarks/trace_server'>;
}
declare module 'tchannel/bin/adhoc-multi.js' {
  declare module.exports: $Exports<'tchannel/bin/adhoc-multi'>;
}
declare module 'tchannel/bin/adhoc.js' {
  declare module.exports: $Exports<'tchannel/bin/adhoc'>;
}
declare module 'tchannel/channel.js' {
  declare module.exports: $Exports<'tchannel/channel'>;
}
declare module 'tchannel/connection.js' {
  declare module.exports: $Exports<'tchannel/connection'>;
}
declare module 'tchannel/drain.js' {
  declare module.exports: $Exports<'tchannel/drain'>;
}
declare module 'tchannel/endpoint-handler.js' {
  declare module.exports: $Exports<'tchannel/endpoint-handler'>;
}
declare module 'tchannel/errors.js' {
  declare module.exports: $Exports<'tchannel/errors'>;
}
declare module 'tchannel/examples/as_example1.js' {
  declare module.exports: $Exports<'tchannel/examples/as_example1'>;
}
declare module 'tchannel/examples/as-thrift.js' {
  declare module.exports: $Exports<'tchannel/examples/as-thrift'>;
}
declare module 'tchannel/examples/example1.js' {
  declare module.exports: $Exports<'tchannel/examples/example1'>;
}
declare module 'tchannel/examples/example2.js' {
  declare module.exports: $Exports<'tchannel/examples/example2'>;
}
declare module 'tchannel/examples/http_egress.js' {
  declare module.exports: $Exports<'tchannel/examples/http_egress'>;
}
declare module 'tchannel/examples/http_ingress.js' {
  declare module.exports: $Exports<'tchannel/examples/http_ingress'>;
}
declare module 'tchannel/examples/josh_test_client.js' {
  declare module.exports: $Exports<'tchannel/examples/josh_test_client'>;
}
declare module 'tchannel/examples/josh_test_server.js' {
  declare module.exports: $Exports<'tchannel/examples/josh_test_server'>;
}
declare module 'tchannel/examples/keyvalue/client.js' {
  declare module.exports: $Exports<'tchannel/examples/keyvalue/client'>;
}
declare module 'tchannel/examples/keyvalue/server.js' {
  declare module.exports: $Exports<'tchannel/examples/keyvalue/server'>;
}
declare module 'tchannel/examples/legacy_example.js' {
  declare module.exports: $Exports<'tchannel/examples/legacy_example'>;
}
declare module 'tchannel/examples/repl_client.js' {
  declare module.exports: $Exports<'tchannel/examples/repl_client'>;
}
declare module 'tchannel/examples/repl_server.js' {
  declare module.exports: $Exports<'tchannel/examples/repl_server'>;
}
declare module 'tchannel/examples/send_test.js' {
  declare module.exports: $Exports<'tchannel/examples/send_test'>;
}
declare module 'tchannel/examples/term_client.js' {
  declare module.exports: $Exports<'tchannel/examples/term_client'>;
}
declare module 'tchannel/examples/term_server.js' {
  declare module.exports: $Exports<'tchannel/examples/term_server'>;
}
declare module 'tchannel/host-port.js' {
  declare module.exports: $Exports<'tchannel/host-port'>;
}
declare module 'tchannel/hyperbahn-client.js' {
  declare module.exports: $Exports<'tchannel/hyperbahn-client'>;
}
declare module 'tchannel/hyperbahn/index' {
  declare module.exports: $Exports<'tchannel/hyperbahn'>;
}
declare module 'tchannel/hyperbahn/index.js' {
  declare module.exports: $Exports<'tchannel/hyperbahn'>;
}
declare module 'tchannel/in_request.js' {
  declare module.exports: $Exports<'tchannel/in_request'>;
}
declare module 'tchannel/in_response.js' {
  declare module.exports: $Exports<'tchannel/in_response'>;
}
declare module 'tchannel/lazy_relay.js' {
  declare module.exports: $Exports<'tchannel/lazy_relay'>;
}
declare module 'tchannel/lib/event_emitter.js' {
  declare module.exports: $Exports<'tchannel/lib/event_emitter'>;
}
declare module 'tchannel/lib/lcg.js' {
  declare module.exports: $Exports<'tchannel/lib/lcg'>;
}
declare module 'tchannel/lib/multicast_ctl.js' {
  declare module.exports: $Exports<'tchannel/lib/multicast_ctl'>;
}
declare module 'tchannel/lib/object_pool.js' {
  declare module.exports: $Exports<'tchannel/lib/object_pool'>;
}
declare module 'tchannel/lib/part-list.js' {
  declare module.exports: $Exports<'tchannel/lib/part-list'>;
}
declare module 'tchannel/lib/pipeline_streams.js' {
  declare module.exports: $Exports<'tchannel/lib/pipeline_streams'>;
}
declare module 'tchannel/lib/rate_counter.js' {
  declare module.exports: $Exports<'tchannel/lib/rate_counter'>;
}
declare module 'tchannel/lib/retry_ratio_tracker.js' {
  declare module.exports: $Exports<'tchannel/lib/retry_ratio_tracker'>;
}
declare module 'tchannel/lib/statsd.js' {
  declare module.exports: $Exports<'tchannel/lib/statsd'>;
}
declare module 'tchannel/monitor.js' {
  declare module.exports: $Exports<'tchannel/monitor'>;
}
declare module 'tchannel/null-logger.js' {
  declare module.exports: $Exports<'tchannel/null-logger'>;
}
declare module 'tchannel/operations.js' {
  declare module.exports: $Exports<'tchannel/operations'>;
}
declare module 'tchannel/out_request.js' {
  declare module.exports: $Exports<'tchannel/out_request'>;
}
declare module 'tchannel/out_response.js' {
  declare module.exports: $Exports<'tchannel/out_response'>;
}
declare module 'tchannel/peer_heap.js' {
  declare module.exports: $Exports<'tchannel/peer_heap'>;
}
declare module 'tchannel/peer_score_strategies.js' {
  declare module.exports: $Exports<'tchannel/peer_score_strategies'>;
}
declare module 'tchannel/peer-file-watcher.js' {
  declare module.exports: $Exports<'tchannel/peer-file-watcher'>;
}
declare module 'tchannel/peer.js' {
  declare module.exports: $Exports<'tchannel/peer'>;
}
declare module 'tchannel/peers_base.js' {
  declare module.exports: $Exports<'tchannel/peers_base'>;
}
declare module 'tchannel/range.js' {
  declare module.exports: $Exports<'tchannel/range'>;
}
declare module 'tchannel/relay_handler.js' {
  declare module.exports: $Exports<'tchannel/relay_handler'>;
}
declare module 'tchannel/reqres_states.js' {
  declare module.exports: $Exports<'tchannel/reqres_states'>;
}
declare module 'tchannel/request-handler.js' {
  declare module.exports: $Exports<'tchannel/request-handler'>;
}
declare module 'tchannel/request.js' {
  declare module.exports: $Exports<'tchannel/request'>;
}
declare module 'tchannel/retry-flags.js' {
  declare module.exports: $Exports<'tchannel/retry-flags'>;
}
declare module 'tchannel/root_peers.js' {
  declare module.exports: $Exports<'tchannel/root_peers'>;
}
declare module 'tchannel/scripts/xlang_test.js' {
  declare module.exports: $Exports<'tchannel/scripts/xlang_test'>;
}
declare module 'tchannel/service-name-handler.js' {
  declare module.exports: $Exports<'tchannel/service-name-handler'>;
}
declare module 'tchannel/services.js' {
  declare module.exports: $Exports<'tchannel/services'>;
}
declare module 'tchannel/stat-tags.js' {
  declare module.exports: $Exports<'tchannel/stat-tags'>;
}
declare module 'tchannel/streaming_in_request.js' {
  declare module.exports: $Exports<'tchannel/streaming_in_request'>;
}
declare module 'tchannel/streaming_in_response.js' {
  declare module.exports: $Exports<'tchannel/streaming_in_response'>;
}
declare module 'tchannel/streaming_out_request.js' {
  declare module.exports: $Exports<'tchannel/streaming_out_request'>;
}
declare module 'tchannel/streaming_out_response.js' {
  declare module.exports: $Exports<'tchannel/streaming_out_response'>;
}
declare module 'tchannel/sub_peers.js' {
  declare module.exports: $Exports<'tchannel/sub_peers'>;
}
declare module 'tchannel/tcollector/reporter.js' {
  declare module.exports: $Exports<'tchannel/tcollector/reporter'>;
}
declare module 'tchannel/test/argstream.js' {
  declare module.exports: $Exports<'tchannel/test/argstream'>;
}
declare module 'tchannel/test/as-http.js' {
  declare module.exports: $Exports<'tchannel/test/as-http'>;
}
declare module 'tchannel/test/as-json.js' {
  declare module.exports: $Exports<'tchannel/test/as-json'>;
}
declare module 'tchannel/test/as-thrift.js' {
  declare module.exports: $Exports<'tchannel/test/as-thrift'>;
}
declare module 'tchannel/test/balance_peer_requests.js' {
  declare module.exports: $Exports<'tchannel/test/balance_peer_requests'>;
}
declare module 'tchannel/test/busy.js' {
  declare module.exports: $Exports<'tchannel/test/busy'>;
}
declare module 'tchannel/test/chan_drain.js' {
  declare module.exports: $Exports<'tchannel/test/chan_drain'>;
}
declare module 'tchannel/test/connection-stats.js' {
  declare module.exports: $Exports<'tchannel/test/connection-stats'>;
}
declare module 'tchannel/test/connection-with-statsd.js' {
  declare module.exports: $Exports<'tchannel/test/connection-with-statsd'>;
}
declare module 'tchannel/test/double-response.js' {
  declare module.exports: $Exports<'tchannel/test/double-response'>;
}
declare module 'tchannel/test/ephemeral-client.js' {
  declare module.exports: $Exports<'tchannel/test/ephemeral-client'>;
}
declare module 'tchannel/test/errors.js' {
  declare module.exports: $Exports<'tchannel/test/errors'>;
}
declare module 'tchannel/test/event_emitter.js' {
  declare module.exports: $Exports<'tchannel/test/event_emitter'>;
}
declare module 'tchannel/test/examples.js' {
  declare module.exports: $Exports<'tchannel/test/examples'>;
}
declare module 'tchannel/test/health.js' {
  declare module.exports: $Exports<'tchannel/test/health'>;
}
declare module 'tchannel/test/hyperbahn-client/constructor.js' {
  declare module.exports: $Exports<'tchannel/test/hyperbahn-client/constructor'>;
}
declare module 'tchannel/test/hyperbahn-client/sub-channel.js' {
  declare module.exports: $Exports<'tchannel/test/hyperbahn-client/sub-channel'>;
}
declare module 'tchannel/test/hyperbahn-client/thrift-codec.js' {
  declare module.exports: $Exports<'tchannel/test/hyperbahn-client/thrift-codec'>;
}
declare module 'tchannel/test/identify.js' {
  declare module.exports: $Exports<'tchannel/test/identify'>;
}
declare module 'tchannel/test/index' {
  declare module.exports: $Exports<'tchannel/test'>;
}
declare module 'tchannel/test/index.js' {
  declare module.exports: $Exports<'tchannel/test'>;
}
declare module 'tchannel/test/large-send.js' {
  declare module.exports: $Exports<'tchannel/test/large-send'>;
}
declare module 'tchannel/test/lazy_conn_handler.js' {
  declare module.exports: $Exports<'tchannel/test/lazy_conn_handler'>;
}
declare module 'tchannel/test/lazy_handler.js' {
  declare module.exports: $Exports<'tchannel/test/lazy_handler'>;
}
declare module 'tchannel/test/lib/alloc-cluster.js' {
  declare module.exports: $Exports<'tchannel/test/lib/alloc-cluster'>;
}
declare module 'tchannel/test/lib/barplot.js' {
  declare module.exports: $Exports<'tchannel/test/lib/barplot'>;
}
declare module 'tchannel/test/lib/barrier.js' {
  declare module.exports: $Exports<'tchannel/test/lib/barrier'>;
}
declare module 'tchannel/test/lib/base2.js' {
  declare module.exports: $Exports<'tchannel/test/lib/base2'>;
}
declare module 'tchannel/test/lib/batch-client.js' {
  declare module.exports: $Exports<'tchannel/test/lib/batch-client'>;
}
declare module 'tchannel/test/lib/cluster_search.js' {
  declare module.exports: $Exports<'tchannel/test/lib/cluster_search'>;
}
declare module 'tchannel/test/lib/collapsed-assert.js' {
  declare module.exports: $Exports<'tchannel/test/lib/collapsed-assert'>;
}
declare module 'tchannel/test/lib/count_stream.js' {
  declare module.exports: $Exports<'tchannel/test/lib/count_stream'>;
}
declare module 'tchannel/test/lib/iter_stream.js' {
  declare module.exports: $Exports<'tchannel/test/lib/iter_stream'>;
}
declare module 'tchannel/test/lib/load_config.js' {
  declare module.exports: $Exports<'tchannel/test/lib/load_config'>;
}
declare module 'tchannel/test/lib/peer_score_obs.js' {
  declare module.exports: $Exports<'tchannel/test/lib/peer_score_obs'>;
}
declare module 'tchannel/test/lib/raw_service.js' {
  declare module.exports: $Exports<'tchannel/test/lib/raw_service'>;
}
declare module 'tchannel/test/lib/resource_pool.js' {
  declare module.exports: $Exports<'tchannel/test/lib/resource_pool'>;
}
declare module 'tchannel/test/lib/rng_stream.js' {
  declare module.exports: $Exports<'tchannel/test/lib/rng_stream'>;
}
declare module 'tchannel/test/lib/run_server.js' {
  declare module.exports: $Exports<'tchannel/test/lib/run_server'>;
}
declare module 'tchannel/test/lib/simple_validators.js' {
  declare module.exports: $Exports<'tchannel/test/lib/simple_validators'>;
}
declare module 'tchannel/test/lib/stream_check.js' {
  declare module.exports: $Exports<'tchannel/test/lib/stream_check'>;
}
declare module 'tchannel/test/lib/stream_search.js' {
  declare module.exports: $Exports<'tchannel/test/lib/stream_search'>;
}
declare module 'tchannel/test/lib/test_isolate_search.js' {
  declare module.exports: $Exports<'tchannel/test/lib/test_isolate_search'>;
}
declare module 'tchannel/test/lib/test_search.js' {
  declare module.exports: $Exports<'tchannel/test/lib/test_search'>;
}
declare module 'tchannel/test/max_pending.js' {
  declare module.exports: $Exports<'tchannel/test/max_pending'>;
}
declare module 'tchannel/test/max-call-overhead.js' {
  declare module.exports: $Exports<'tchannel/test/max-call-overhead'>;
}
declare module 'tchannel/test/no_frag_arg1.js' {
  declare module.exports: $Exports<'tchannel/test/no_frag_arg1'>;
}
declare module 'tchannel/test/non-zero-ttl.js' {
  declare module.exports: $Exports<'tchannel/test/non-zero-ttl'>;
}
declare module 'tchannel/test/object_pool.js' {
  declare module.exports: $Exports<'tchannel/test/object_pool'>;
}
declare module 'tchannel/test/peer_drain.js' {
  declare module.exports: $Exports<'tchannel/test/peer_drain'>;
}
declare module 'tchannel/test/peer_strategies.js' {
  declare module.exports: $Exports<'tchannel/test/peer_strategies'>;
}
declare module 'tchannel/test/peer-file-watcher.js' {
  declare module.exports: $Exports<'tchannel/test/peer-file-watcher'>;
}
declare module 'tchannel/test/peer-to-peer-load-balance.js' {
  declare module.exports: $Exports<'tchannel/test/peer-to-peer-load-balance'>;
}
declare module 'tchannel/test/peer.js' {
  declare module.exports: $Exports<'tchannel/test/peer'>;
}
declare module 'tchannel/test/peers.js' {
  declare module.exports: $Exports<'tchannel/test/peers'>;
}
declare module 'tchannel/test/ping.js' {
  declare module.exports: $Exports<'tchannel/test/ping'>;
}
declare module 'tchannel/test/pool-of-servers.js' {
  declare module.exports: $Exports<'tchannel/test/pool-of-servers'>;
}
declare module 'tchannel/test/rate_counter.js' {
  declare module.exports: $Exports<'tchannel/test/rate_counter'>;
}
declare module 'tchannel/test/register.js' {
  declare module.exports: $Exports<'tchannel/test/register'>;
}
declare module 'tchannel/test/regression-conn-double-buildResponse.js' {
  declare module.exports: $Exports<'tchannel/test/regression-conn-double-buildResponse'>;
}
declare module 'tchannel/test/regression-inOps-leak.js' {
  declare module.exports: $Exports<'tchannel/test/regression-inOps-leak'>;
}
declare module 'tchannel/test/regression-listening-on-used-port.js' {
  declare module.exports: $Exports<'tchannel/test/regression-listening-on-used-port'>;
}
declare module 'tchannel/test/relay_lazy.js' {
  declare module.exports: $Exports<'tchannel/test/relay_lazy'>;
}
declare module 'tchannel/test/relay-clamps-the-ttl.js' {
  declare module.exports: $Exports<'tchannel/test/relay-clamps-the-ttl'>;
}
declare module 'tchannel/test/relay-kills-socket-after-timeouts.js' {
  declare module.exports: $Exports<'tchannel/test/relay-kills-socket-after-timeouts'>;
}
declare module 'tchannel/test/relay-stats.js' {
  declare module.exports: $Exports<'tchannel/test/relay-stats'>;
}
declare module 'tchannel/test/relay-to-dead.js' {
  declare module.exports: $Exports<'tchannel/test/relay-to-dead'>;
}
declare module 'tchannel/test/relay-under-timeouts.js' {
  declare module.exports: $Exports<'tchannel/test/relay-under-timeouts'>;
}
declare module 'tchannel/test/relay.js' {
  declare module.exports: $Exports<'tchannel/test/relay'>;
}
declare module 'tchannel/test/request-error-context.js' {
  declare module.exports: $Exports<'tchannel/test/request-error-context'>;
}
declare module 'tchannel/test/request-stats.js' {
  declare module.exports: $Exports<'tchannel/test/request-stats'>;
}
declare module 'tchannel/test/request-with-statsd.js' {
  declare module.exports: $Exports<'tchannel/test/request-with-statsd'>;
}
declare module 'tchannel/test/response-stats.js' {
  declare module.exports: $Exports<'tchannel/test/response-stats'>;
}
declare module 'tchannel/test/response-with-statsd.js' {
  declare module.exports: $Exports<'tchannel/test/response-with-statsd'>;
}
declare module 'tchannel/test/retry.js' {
  declare module.exports: $Exports<'tchannel/test/retry'>;
}
declare module 'tchannel/test/safe-quit.js' {
  declare module.exports: $Exports<'tchannel/test/safe-quit'>;
}
declare module 'tchannel/test/send.js' {
  declare module.exports: $Exports<'tchannel/test/send'>;
}
declare module 'tchannel/test/streaming_bisect.js' {
  declare module.exports: $Exports<'tchannel/test/streaming_bisect'>;
}
declare module 'tchannel/test/streaming-resp-err.js' {
  declare module.exports: $Exports<'tchannel/test/streaming-resp-err'>;
}
declare module 'tchannel/test/streaming.js' {
  declare module.exports: $Exports<'tchannel/test/streaming'>;
}
declare module 'tchannel/test/tchannel.js' {
  declare module.exports: $Exports<'tchannel/test/tchannel'>;
}
declare module 'tchannel/test/tcollector-reporter.js' {
  declare module.exports: $Exports<'tchannel/test/tcollector-reporter'>;
}
declare module 'tchannel/test/time_heap.js' {
  declare module.exports: $Exports<'tchannel/test/time_heap'>;
}
declare module 'tchannel/test/timeouts.js' {
  declare module.exports: $Exports<'tchannel/test/timeouts'>;
}
declare module 'tchannel/test/trace/basic_server.js' {
  declare module.exports: $Exports<'tchannel/test/trace/basic_server'>;
}
declare module 'tchannel/test/trace/lib/basic_server_fixture.js' {
  declare module.exports: $Exports<'tchannel/test/trace/lib/basic_server_fixture'>;
}
declare module 'tchannel/test/trace/lib/server_2_requests_fixture.js' {
  declare module.exports: $Exports<'tchannel/test/trace/lib/server_2_requests_fixture'>;
}
declare module 'tchannel/test/trace/outpeer_span_handle.js' {
  declare module.exports: $Exports<'tchannel/test/trace/outpeer_span_handle'>;
}
declare module 'tchannel/test/trace/server_2_requests.js' {
  declare module.exports: $Exports<'tchannel/test/trace/server_2_requests'>;
}
declare module 'tchannel/test/v2/args.js' {
  declare module.exports: $Exports<'tchannel/test/v2/args'>;
}
declare module 'tchannel/test/v2/call.js' {
  declare module.exports: $Exports<'tchannel/test/v2/call'>;
}
declare module 'tchannel/test/v2/cancel.js' {
  declare module.exports: $Exports<'tchannel/test/v2/cancel'>;
}
declare module 'tchannel/test/v2/checksum.js' {
  declare module.exports: $Exports<'tchannel/test/v2/checksum'>;
}
declare module 'tchannel/test/v2/claim.js' {
  declare module.exports: $Exports<'tchannel/test/v2/claim'>;
}
declare module 'tchannel/test/v2/cont.js' {
  declare module.exports: $Exports<'tchannel/test/v2/cont'>;
}
declare module 'tchannel/test/v2/error_response.js' {
  declare module.exports: $Exports<'tchannel/test/v2/error_response'>;
}
declare module 'tchannel/test/v2/frame.js' {
  declare module.exports: $Exports<'tchannel/test/v2/frame'>;
}
declare module 'tchannel/test/v2/header.js' {
  declare module.exports: $Exports<'tchannel/test/v2/header'>;
}
declare module 'tchannel/test/v2/init.js' {
  declare module.exports: $Exports<'tchannel/test/v2/init'>;
}
declare module 'tchannel/test/v2/lazy_frame.js' {
  declare module.exports: $Exports<'tchannel/test/v2/lazy_frame'>;
}
declare module 'tchannel/test/v2/lib/test_body.js' {
  declare module.exports: $Exports<'tchannel/test/v2/lib/test_body'>;
}
declare module 'tchannel/test/v2/ping.js' {
  declare module.exports: $Exports<'tchannel/test/v2/ping'>;
}
declare module 'tchannel/test/v2/tracing.js' {
  declare module.exports: $Exports<'tchannel/test/v2/tracing'>;
}
declare module 'tchannel/time_heap.js' {
  declare module.exports: $Exports<'tchannel/time_heap'>;
}
declare module 'tchannel/trace/agent.js' {
  declare module.exports: $Exports<'tchannel/trace/agent'>;
}
declare module 'tchannel/trace/span.js' {
  declare module.exports: $Exports<'tchannel/trace/span'>;
}
declare module 'tchannel/v1/frame.js' {
  declare module.exports: $Exports<'tchannel/v1/frame'>;
}
declare module 'tchannel/v1/handler.js' {
  declare module.exports: $Exports<'tchannel/v1/handler'>;
}
declare module 'tchannel/v1/header.js' {
  declare module.exports: $Exports<'tchannel/v1/header'>;
}
declare module 'tchannel/v1/index' {
  declare module.exports: $Exports<'tchannel/v1'>;
}
declare module 'tchannel/v1/index.js' {
  declare module.exports: $Exports<'tchannel/v1'>;
}
declare module 'tchannel/v1/parser.js' {
  declare module.exports: $Exports<'tchannel/v1/parser'>;
}
declare module 'tchannel/v2/args.js' {
  declare module.exports: $Exports<'tchannel/v2/args'>;
}
declare module 'tchannel/v2/call_flags.js' {
  declare module.exports: $Exports<'tchannel/v2/call_flags'>;
}
declare module 'tchannel/v2/call.js' {
  declare module.exports: $Exports<'tchannel/v2/call'>;
}
declare module 'tchannel/v2/cancel.js' {
  declare module.exports: $Exports<'tchannel/v2/cancel'>;
}
declare module 'tchannel/v2/checksum.js' {
  declare module.exports: $Exports<'tchannel/v2/checksum'>;
}
declare module 'tchannel/v2/claim.js' {
  declare module.exports: $Exports<'tchannel/v2/claim'>;
}
declare module 'tchannel/v2/cont.js' {
  declare module.exports: $Exports<'tchannel/v2/cont'>;
}
declare module 'tchannel/v2/error_response.js' {
  declare module.exports: $Exports<'tchannel/v2/error_response'>;
}
declare module 'tchannel/v2/frame.js' {
  declare module.exports: $Exports<'tchannel/v2/frame'>;
}
declare module 'tchannel/v2/handler.js' {
  declare module.exports: $Exports<'tchannel/v2/handler'>;
}
declare module 'tchannel/v2/header.js' {
  declare module.exports: $Exports<'tchannel/v2/header'>;
}
declare module 'tchannel/v2/index' {
  declare module.exports: $Exports<'tchannel/v2'>;
}
declare module 'tchannel/v2/index.js' {
  declare module.exports: $Exports<'tchannel/v2'>;
}
declare module 'tchannel/v2/init.js' {
  declare module.exports: $Exports<'tchannel/v2/init'>;
}
declare module 'tchannel/v2/lazy_frame.js' {
  declare module.exports: $Exports<'tchannel/v2/lazy_frame'>;
}
declare module 'tchannel/v2/out_request.js' {
  declare module.exports: $Exports<'tchannel/v2/out_request'>;
}
declare module 'tchannel/v2/out_response.js' {
  declare module.exports: $Exports<'tchannel/v2/out_response'>;
}
declare module 'tchannel/v2/ping.js' {
  declare module.exports: $Exports<'tchannel/v2/ping'>;
}
declare module 'tchannel/v2/tracing.js' {
  declare module.exports: $Exports<'tchannel/v2/tracing'>;
}
