// flow-typed signature: 5de9b075acfdc0aaef82a099ca63be3a
// flow-typed version: <<STUB>>/test-helpers_vfile:components/test-helpers/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'test-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'test-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'test-helpers/scripts/dump-test-data' {
  declare module.exports: any;
}

declare module 'test-helpers/scripts/restore-test-data' {
  declare module.exports: any;
}

declare module 'test-helpers/src/attachmentsCheck' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/accesses' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/events' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/followedSlices' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/migrated/0.3.0/accesses' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/migrated/0.3.0/attachments' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/migrated/0.3.0/events' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/migrated/0.3.0/streams' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/migrated/0.4.0/accesses' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/migrated/0.4.0/streams' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/migrated/0.5.0/events' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/migrated/0.5.0/streams' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/profile' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/streams' {
  declare module.exports: any;
}

declare module 'test-helpers/src/data/users' {
  declare module.exports: any;
}

declare module 'test-helpers/src/dependencies' {
  declare module.exports: any;
}

declare module 'test-helpers/src/index' {
  declare module.exports: any;
}

declare module 'test-helpers/src/InstanceManager' {
  declare module.exports: any;
}

declare module 'test-helpers/src/instanceTestSetup' {
  declare module.exports: any;
}

declare module 'test-helpers/src/request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'test-helpers/scripts/dump-test-data.js' {
  declare module.exports: $Exports<'test-helpers/scripts/dump-test-data'>;
}
declare module 'test-helpers/scripts/restore-test-data.js' {
  declare module.exports: $Exports<'test-helpers/scripts/restore-test-data'>;
}
declare module 'test-helpers/src/attachmentsCheck.js' {
  declare module.exports: $Exports<'test-helpers/src/attachmentsCheck'>;
}
declare module 'test-helpers/src/data.js' {
  declare module.exports: $Exports<'test-helpers/src/data'>;
}
declare module 'test-helpers/src/data/accesses.js' {
  declare module.exports: $Exports<'test-helpers/src/data/accesses'>;
}
declare module 'test-helpers/src/data/events.js' {
  declare module.exports: $Exports<'test-helpers/src/data/events'>;
}
declare module 'test-helpers/src/data/followedSlices.js' {
  declare module.exports: $Exports<'test-helpers/src/data/followedSlices'>;
}
declare module 'test-helpers/src/data/migrated/0.3.0/accesses.js' {
  declare module.exports: $Exports<'test-helpers/src/data/migrated/0.3.0/accesses'>;
}
declare module 'test-helpers/src/data/migrated/0.3.0/attachments.js' {
  declare module.exports: $Exports<'test-helpers/src/data/migrated/0.3.0/attachments'>;
}
declare module 'test-helpers/src/data/migrated/0.3.0/events.js' {
  declare module.exports: $Exports<'test-helpers/src/data/migrated/0.3.0/events'>;
}
declare module 'test-helpers/src/data/migrated/0.3.0/streams.js' {
  declare module.exports: $Exports<'test-helpers/src/data/migrated/0.3.0/streams'>;
}
declare module 'test-helpers/src/data/migrated/0.4.0/accesses.js' {
  declare module.exports: $Exports<'test-helpers/src/data/migrated/0.4.0/accesses'>;
}
declare module 'test-helpers/src/data/migrated/0.4.0/streams.js' {
  declare module.exports: $Exports<'test-helpers/src/data/migrated/0.4.0/streams'>;
}
declare module 'test-helpers/src/data/migrated/0.5.0/events.js' {
  declare module.exports: $Exports<'test-helpers/src/data/migrated/0.5.0/events'>;
}
declare module 'test-helpers/src/data/migrated/0.5.0/streams.js' {
  declare module.exports: $Exports<'test-helpers/src/data/migrated/0.5.0/streams'>;
}
declare module 'test-helpers/src/data/profile.js' {
  declare module.exports: $Exports<'test-helpers/src/data/profile'>;
}
declare module 'test-helpers/src/data/streams.js' {
  declare module.exports: $Exports<'test-helpers/src/data/streams'>;
}
declare module 'test-helpers/src/data/users.js' {
  declare module.exports: $Exports<'test-helpers/src/data/users'>;
}
declare module 'test-helpers/src/dependencies.js' {
  declare module.exports: $Exports<'test-helpers/src/dependencies'>;
}
declare module 'test-helpers/src/index.js' {
  declare module.exports: $Exports<'test-helpers/src/index'>;
}
declare module 'test-helpers/src/InstanceManager.js' {
  declare module.exports: $Exports<'test-helpers/src/InstanceManager'>;
}
declare module 'test-helpers/src/instanceTestSetup.js' {
  declare module.exports: $Exports<'test-helpers/src/instanceTestSetup'>;
}
declare module 'test-helpers/src/request.js' {
  declare module.exports: $Exports<'test-helpers/src/request'>;
}
