/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: be390c2bb683db2ec3399fcc810c745e
// flow-typed version: <<STUB>>/tmp_v^0.0.33/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tmp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tmp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tmp/lib/tmp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tmp/lib/tmp.js' {
  declare module.exports: $Exports<'tmp/lib/tmp'>;
}
