/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 8a17bbefeaa8d79863b035765ef06f3e
// flow-typed version: <<STUB>>/tprpc_vfile:components/tprpc/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tprpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tprpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tprpc/src/client' {
  declare module.exports: any;
}

declare module 'tprpc/src/definition' {
  declare module.exports: any;
}

declare module 'tprpc/src/errors' {
  declare module.exports: any;
}

declare module 'tprpc/src' {
  declare module.exports: any;
}

declare module 'tprpc/src/server' {
  declare module.exports: any;
}

declare module 'tprpc/test/acceptance/base.test' {
  declare module.exports: any;
}

declare module 'tprpc/test/acceptance/compile.test' {
  declare module.exports: any;
}

declare module 'tprpc/test/fixtures/base' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tprpc/src/client.js' {
  declare module.exports: $Exports<'tprpc/src/client'>;
}
declare module 'tprpc/src/definition.js' {
  declare module.exports: $Exports<'tprpc/src/definition'>;
}
declare module 'tprpc/src/errors.js' {
  declare module.exports: $Exports<'tprpc/src/errors'>;
}
declare module 'tprpc/src/index' {
  declare module.exports: $Exports<'tprpc/src'>;
}
declare module 'tprpc/src/index.js' {
  declare module.exports: $Exports<'tprpc/src'>;
}
declare module 'tprpc/src/server.js' {
  declare module.exports: $Exports<'tprpc/src/server'>;
}
declare module 'tprpc/test/acceptance/base.test.js' {
  declare module.exports: $Exports<'tprpc/test/acceptance/base.test'>;
}
declare module 'tprpc/test/acceptance/compile.test.js' {
  declare module.exports: $Exports<'tprpc/test/acceptance/compile.test'>;
}
declare module 'tprpc/test/fixtures/base.js' {
  declare module.exports: $Exports<'tprpc/test/fixtures/base'>;
}
