/**
 * @license
 * Copyright (C) 2012-2022 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: a472562fdf807c653828c2b1d5b74097
// flow-typed version: <<STUB>>/unicode_v^12.1.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unicode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unicode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unicode/category/Cc' {
  declare module.exports: any;
}

declare module 'unicode/category/Cf' {
  declare module.exports: any;
}

declare module 'unicode/category/Co' {
  declare module.exports: any;
}

declare module 'unicode/category/Cs' {
  declare module.exports: any;
}

declare module 'unicode/category' {
  declare module.exports: any;
}

declare module 'unicode/category/Ll' {
  declare module.exports: any;
}

declare module 'unicode/category/Lm' {
  declare module.exports: any;
}

declare module 'unicode/category/Lo' {
  declare module.exports: any;
}

declare module 'unicode/category/Lt' {
  declare module.exports: any;
}

declare module 'unicode/category/Lu' {
  declare module.exports: any;
}

declare module 'unicode/category/Mc' {
  declare module.exports: any;
}

declare module 'unicode/category/Me' {
  declare module.exports: any;
}

declare module 'unicode/category/Mn' {
  declare module.exports: any;
}

declare module 'unicode/category/Nd' {
  declare module.exports: any;
}

declare module 'unicode/category/Nl' {
  declare module.exports: any;
}

declare module 'unicode/category/No' {
  declare module.exports: any;
}

declare module 'unicode/category/Pc' {
  declare module.exports: any;
}

declare module 'unicode/category/Pd' {
  declare module.exports: any;
}

declare module 'unicode/category/Pe' {
  declare module.exports: any;
}

declare module 'unicode/category/Pf' {
  declare module.exports: any;
}

declare module 'unicode/category/Pi' {
  declare module.exports: any;
}

declare module 'unicode/category/Po' {
  declare module.exports: any;
}

declare module 'unicode/category/Ps' {
  declare module.exports: any;
}

declare module 'unicode/category/Sc' {
  declare module.exports: any;
}

declare module 'unicode/category/Sk' {
  declare module.exports: any;
}

declare module 'unicode/category/Sm' {
  declare module.exports: any;
}

declare module 'unicode/category/So' {
  declare module.exports: any;
}

declare module 'unicode/category/Zl' {
  declare module.exports: any;
}

declare module 'unicode/category/Zp' {
  declare module.exports: any;
}

declare module 'unicode/category/Zs' {
  declare module.exports: any;
}

declare module 'unicode/generate' {
  declare module.exports: any;
}

declare module 'unicode/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unicode/category/Cc.js' {
  declare module.exports: $Exports<'unicode/category/Cc'>;
}
declare module 'unicode/category/Cf.js' {
  declare module.exports: $Exports<'unicode/category/Cf'>;
}
declare module 'unicode/category/Co.js' {
  declare module.exports: $Exports<'unicode/category/Co'>;
}
declare module 'unicode/category/Cs.js' {
  declare module.exports: $Exports<'unicode/category/Cs'>;
}
declare module 'unicode/category/index' {
  declare module.exports: $Exports<'unicode/category'>;
}
declare module 'unicode/category/index.js' {
  declare module.exports: $Exports<'unicode/category'>;
}
declare module 'unicode/category/Ll.js' {
  declare module.exports: $Exports<'unicode/category/Ll'>;
}
declare module 'unicode/category/Lm.js' {
  declare module.exports: $Exports<'unicode/category/Lm'>;
}
declare module 'unicode/category/Lo.js' {
  declare module.exports: $Exports<'unicode/category/Lo'>;
}
declare module 'unicode/category/Lt.js' {
  declare module.exports: $Exports<'unicode/category/Lt'>;
}
declare module 'unicode/category/Lu.js' {
  declare module.exports: $Exports<'unicode/category/Lu'>;
}
declare module 'unicode/category/Mc.js' {
  declare module.exports: $Exports<'unicode/category/Mc'>;
}
declare module 'unicode/category/Me.js' {
  declare module.exports: $Exports<'unicode/category/Me'>;
}
declare module 'unicode/category/Mn.js' {
  declare module.exports: $Exports<'unicode/category/Mn'>;
}
declare module 'unicode/category/Nd.js' {
  declare module.exports: $Exports<'unicode/category/Nd'>;
}
declare module 'unicode/category/Nl.js' {
  declare module.exports: $Exports<'unicode/category/Nl'>;
}
declare module 'unicode/category/No.js' {
  declare module.exports: $Exports<'unicode/category/No'>;
}
declare module 'unicode/category/Pc.js' {
  declare module.exports: $Exports<'unicode/category/Pc'>;
}
declare module 'unicode/category/Pd.js' {
  declare module.exports: $Exports<'unicode/category/Pd'>;
}
declare module 'unicode/category/Pe.js' {
  declare module.exports: $Exports<'unicode/category/Pe'>;
}
declare module 'unicode/category/Pf.js' {
  declare module.exports: $Exports<'unicode/category/Pf'>;
}
declare module 'unicode/category/Pi.js' {
  declare module.exports: $Exports<'unicode/category/Pi'>;
}
declare module 'unicode/category/Po.js' {
  declare module.exports: $Exports<'unicode/category/Po'>;
}
declare module 'unicode/category/Ps.js' {
  declare module.exports: $Exports<'unicode/category/Ps'>;
}
declare module 'unicode/category/Sc.js' {
  declare module.exports: $Exports<'unicode/category/Sc'>;
}
declare module 'unicode/category/Sk.js' {
  declare module.exports: $Exports<'unicode/category/Sk'>;
}
declare module 'unicode/category/Sm.js' {
  declare module.exports: $Exports<'unicode/category/Sm'>;
}
declare module 'unicode/category/So.js' {
  declare module.exports: $Exports<'unicode/category/So'>;
}
declare module 'unicode/category/Zl.js' {
  declare module.exports: $Exports<'unicode/category/Zl'>;
}
declare module 'unicode/category/Zp.js' {
  declare module.exports: $Exports<'unicode/category/Zp'>;
}
declare module 'unicode/category/Zs.js' {
  declare module.exports: $Exports<'unicode/category/Zs'>;
}
declare module 'unicode/generate.js' {
  declare module.exports: $Exports<'unicode/generate'>;
}
declare module 'unicode/test.js' {
  declare module.exports: $Exports<'unicode/test'>;
}
