/**
 * @license
 * Copyright (C) 2012-2021 Pryv S.A. https://pryv.com - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
// flow-typed signature: 8a256fddbc449a0bd1b8557d4a467ecd
// flow-typed version: <<STUB>>/unix-timestamp_v^0.2.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unix-timestamp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unix-timestamp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unix-timestamp/lib/timestamp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unix-timestamp/lib/timestamp.js' {
  declare module.exports: $Exports<'unix-timestamp/lib/timestamp'>;
}
