// flow-typed signature: c77fea1091f2f5f32c3cdaf4476c08da
// flow-typed version: <<STUB>>/utils_vfile:components/utils/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utils/src/config' {
  declare module.exports: any;
}

declare module 'utils/src/config/value' {
  declare module.exports: any;
}

declare module 'utils/src/encryption' {
  declare module.exports: any;
}

declare module 'utils/src/extension' {
  declare module.exports: any;
}

declare module 'utils/src' {
  declare module.exports: any;
}

declare module 'utils/src/logging' {
  declare module.exports: any;
}

declare module 'utils/src/messaging' {
  declare module.exports: any;
}

declare module 'utils/src/toString' {
  declare module.exports: any;
}

declare module 'utils/src/treeUtils' {
  declare module.exports: any;
}

declare module 'utils/test/treeUtils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utils/src/config.js' {
  declare module.exports: $Exports<'utils/src/config'>;
}
declare module 'utils/src/config/value.js' {
  declare module.exports: $Exports<'utils/src/config/value'>;
}
declare module 'utils/src/encryption.js' {
  declare module.exports: $Exports<'utils/src/encryption'>;
}
declare module 'utils/src/extension.js' {
  declare module.exports: $Exports<'utils/src/extension'>;
}
declare module 'utils/src/index' {
  declare module.exports: $Exports<'utils/src'>;
}
declare module 'utils/src/index.js' {
  declare module.exports: $Exports<'utils/src'>;
}
declare module 'utils/src/logging.js' {
  declare module.exports: $Exports<'utils/src/logging'>;
}
declare module 'utils/src/messaging.js' {
  declare module.exports: $Exports<'utils/src/messaging'>;
}
declare module 'utils/src/toString.js' {
  declare module.exports: $Exports<'utils/src/toString'>;
}
declare module 'utils/src/treeUtils.js' {
  declare module.exports: $Exports<'utils/src/treeUtils'>;
}
declare module 'utils/test/treeUtils.test.js' {
  declare module.exports: $Exports<'utils/test/treeUtils.test'>;
}
