// flow-typed signature: d5444f4468932d46874ecf03f8ed7d6c
// flow-typed version: <<STUB>>/winston-syslog_v^2.4.4/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-syslog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-syslog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-syslog/lib/utils' {
  declare module.exports: any;
}

declare module 'winston-syslog/lib/winston-syslog' {
  declare module.exports: any;
}

declare module 'winston-syslog/test/format-test' {
  declare module.exports: any;
}

declare module 'winston-syslog/test/message-test' {
  declare module.exports: any;
}

declare module 'winston-syslog/test/syslog-test' {
  declare module.exports: any;
}

declare module 'winston-syslog/test/unix-connect-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-syslog/lib/utils.js' {
  declare module.exports: $Exports<'winston-syslog/lib/utils'>;
}
declare module 'winston-syslog/lib/winston-syslog.js' {
  declare module.exports: $Exports<'winston-syslog/lib/winston-syslog'>;
}
declare module 'winston-syslog/test/format-test.js' {
  declare module.exports: $Exports<'winston-syslog/test/format-test'>;
}
declare module 'winston-syslog/test/message-test.js' {
  declare module.exports: $Exports<'winston-syslog/test/message-test'>;
}
declare module 'winston-syslog/test/syslog-test.js' {
  declare module.exports: $Exports<'winston-syslog/test/syslog-test'>;
}
declare module 'winston-syslog/test/unix-connect-test.js' {
  declare module.exports: $Exports<'winston-syslog/test/unix-connect-test'>;
}
