// flow-typed signature: 92d885e154951192ca7f4c2a267d0deb
// flow-typed version: <<STUB>>/z-schema_v^5.0.3/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'z-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'z-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'z-schema/dist/ZSchema-browser-min' {
  declare module.exports: any;
}

declare module 'z-schema/dist/ZSchema-browser-test' {
  declare module.exports: any;
}

declare module 'z-schema/dist/ZSchema-browser' {
  declare module.exports: any;
}

declare module 'z-schema/src/Errors' {
  declare module.exports: any;
}

declare module 'z-schema/src/FormatValidators' {
  declare module.exports: any;
}

declare module 'z-schema/src/JsonValidation' {
  declare module.exports: any;
}

declare module 'z-schema/src/Polyfills' {
  declare module.exports: any;
}

declare module 'z-schema/src/Report' {
  declare module.exports: any;
}

declare module 'z-schema/src/SchemaCache' {
  declare module.exports: any;
}

declare module 'z-schema/src/SchemaCompilation' {
  declare module.exports: any;
}

declare module 'z-schema/src/SchemaValidation' {
  declare module.exports: any;
}

declare module 'z-schema/src/Utils' {
  declare module.exports: any;
}

declare module 'z-schema/src/ZSchema' {
  declare module.exports: any;
}

// Filename aliases
declare module 'z-schema/dist/ZSchema-browser-min.js' {
  declare module.exports: $Exports<'z-schema/dist/ZSchema-browser-min'>;
}
declare module 'z-schema/dist/ZSchema-browser-test.js' {
  declare module.exports: $Exports<'z-schema/dist/ZSchema-browser-test'>;
}
declare module 'z-schema/dist/ZSchema-browser.js' {
  declare module.exports: $Exports<'z-schema/dist/ZSchema-browser'>;
}
declare module 'z-schema/src/Errors.js' {
  declare module.exports: $Exports<'z-schema/src/Errors'>;
}
declare module 'z-schema/src/FormatValidators.js' {
  declare module.exports: $Exports<'z-schema/src/FormatValidators'>;
}
declare module 'z-schema/src/JsonValidation.js' {
  declare module.exports: $Exports<'z-schema/src/JsonValidation'>;
}
declare module 'z-schema/src/Polyfills.js' {
  declare module.exports: $Exports<'z-schema/src/Polyfills'>;
}
declare module 'z-schema/src/Report.js' {
  declare module.exports: $Exports<'z-schema/src/Report'>;
}
declare module 'z-schema/src/SchemaCache.js' {
  declare module.exports: $Exports<'z-schema/src/SchemaCache'>;
}
declare module 'z-schema/src/SchemaCompilation.js' {
  declare module.exports: $Exports<'z-schema/src/SchemaCompilation'>;
}
declare module 'z-schema/src/SchemaValidation.js' {
  declare module.exports: $Exports<'z-schema/src/SchemaValidation'>;
}
declare module 'z-schema/src/Utils.js' {
  declare module.exports: $Exports<'z-schema/src/Utils'>;
}
declare module 'z-schema/src/ZSchema.js' {
  declare module.exports: $Exports<'z-schema/src/ZSchema'>;
}
