---
http: 
  ip: '127.0.0.1'
  port: 3000

dnsLess:
  isActive: true
  publicUrl: http://localhost:3000/

database:
  authUser: ''
  authPassword: ''
  host: 'localhost'
  port: 27017
  name: 'pryv-node-test' # Change this !!!! or make sure defaults does not override anything
  connectTimeoutMS: 60000
  socketTimeoutMS: 60000

logs:
  airbrake:
    active: false

influxdb:
  host: 127.0.0.1
  port: 8086

eventFiles:
  attachmentsDirPath: '/Users/perki/wActiv/service-core-files/attachments' # Make the two last dynamic
  previewsDirPath: '/Users/perki/wActiv/service-core-files/previews'

updates: 
  ignoreProtectedFields: false

webhooks:
  minIntervalMs: 5000
  maxRetries: 5
  runsSize: 20

auth:
  filesReadTokenSecret: 'OVERRIDE ME'
  adminAccessKey: 'REPLACE_ME_WITH_SOMETHING'
  trustedApps: '*@http://*.pryv.local*, *@https://*.rec.la*, *@http://pryv.github.io'
  sessionMaxAge: 1209600000
  ssoCookieDomain: ''
  ssoCookieSignSecret: 'OVERRIDE ME'
  passwordResetRequestMaxAge: 3600000
  passwordResetPageURL: 'http://localhost:3000/www/access/reset-password.html'

audit: 
  forceKeepHistory: false
  deletionMode: 'keep-nothing'