---
dnsLess:
  isActive: true
  publicUrl: http://localhost:3000/
database:
  authUser: ''
  authPassword: ''
  host: 'localhost'
  port: 27017
  name: 'pryv-node'
  connectTimeoutMS: 60000
  socketTimeoutMS: 60000
