---

openSource:
  isActive: false

dnsLess:
  isActive: true

reporting:
  licenseName: 'REPLACE ME'
  templateVersion: '1.0.0'

http: 
  ip: '127.0.0.1'
  port: 3000

database:
  authUser: ''
  authPassword: ''
  host: 'localhost'
  port: 27017
  name: 'pryv-node'
  connectTimeoutMS: 60000
  socketTimeoutMS: 60000

userFiles:
  path: 'REPLACE ME'

eventFiles: 
  attachmentsDirPath: 'REPLACE ME'
  previewsDirPath: 'REPLACE ME'

auth:
  filesReadTokenSecret: 'REPLACE ME'

customExtensions: 
  defaultFolder: 'REPLACE ME'
  customAuthStepFn: ''

axonMessaging:
  enabled: false
  host: 'localhost'
  port: 4000
  pubConnectInsteadOfBind: false

updates: 
  ignoreProtectedFields: false 

influxdb:
  host: 127.0.0.1
  port: 8086

webhooks:
  minIntervalMs: 5000
  maxRetries: 5
  runsSize: 20

versioning: 
  forceKeepHistory: false
  deletionMode: 'keep-nothing'

user-account:
  delete: # array of entities that can delete a user account
    - 'adminToken' # enable deletion from admin Panel
    #- 'personalToken' # enable self deletion request with a personal token

backwardCompatibility:
  systemStreams:
    prefix:
      isActive: false
  tags:
    isActive: true
    rootStreamId: 'tags-migrated'
    streamIdPrefix: 'tag-migrated-'

custom:
  systemStreams:
    account:
    - id: email
      isIndexed: true
      isUnique: true
      isShown: true
      isEditable: true
      type: email/string
      name: Email
      isRequiredInValidation: true

stores:
  loadExternal: []

caching:
  isActive: true

logs:
  console:
    active: false
    level: info
  file:
    active: false
    path: "var-pryv/logs/core.log"
    level: info
    rotation:
      isActive: true
      days: 14

uploads:
  maxSizeMb: 50

trace:
  enable: false

integrity:
  isActive:
    attachments: true
    events: true
    accesses: true
  algorithm: sha256