---
logs:
  console:
    active: true
    level: info
  file:
    active: true
    path: "var-pryv/logs/core.log"
    level: info
    rotation:
      isActive: true
      days: 14
auth:
  adminAccessKey: CHANGE_ME_WITH_SOMETHING
  trustedApps: "*@https://pryv.github.io*, *@https://*.rec.la*, *@https://*.backloop.dev*, *@http://127.0.0.1*"
serviceInfoUrl: file://test/service-info.json
services:
  email:
    enabled:
      welcome: false
      resetPassword: false
  register:
    url: http://127.0.0.1:8080
    key: test-system-key
reporting:
  templateVersion: 1.0.0
axonMessaging:
  enabled: false
openSource:
  isActive: false
dnsLess:
  isActive: true
  publicUrl: http://127.0.0.1:3000/
custom:
  systemStreams:
    account:
      -
        isIndexed: true
        isUnique: true
        isShown: true
        isEditable: true
        type: email/string
        name: Email
        id: email
        isRequiredInValidation: true
    other:
      -
        isShown: true
        isEditable: true
        type: my-custom-stream/string
        name: myCustomStream
        id: myCustomStream
user-account:
  delete: # array of entities that can delete a user account
    - 'adminToken' # enable deletion from admin Panel
    - 'personalToken' # enable self deletion request with a personal token
backwardCompatibility:
  systemStreams:
    prefix:
      isActive: false
trace:
  enable: true
