---
logs:
  console:
    active: true
    level: debug
auth:
  adminAccessKey: CHANGE_ME_WITH_SOMETHING
  trustedApps: "*@https://pryv.github.io*, *@https://*.rec.la*"
serviceInfoUrl: file://test/service-info.json
services:
  email:
    enabled: false
  register:
    url: http://127.0.0.1:8080
    key: test-system-key
reporting:
  licenseName: pryv.io-dev-license
  templateVersion: 1.0.0
tcpMessaging:
  enabled: false
openSource:
  isActive: false
dnsLess:
  isActive: true
  publicUrl: http://localhost:3000/
custom:
  systemStreams:
    account:
    - isIndexed: true
      isUnique: true
      isShown: true
      isEditable: true
      type: email/string
      name: Email
      id: email
      isRequiredInValidation: true
    myCustomStream:
    - isShown: true
      isEditable: true
      type: myCustomStream/string
      name: myCustomStream
      id: myCustomStream

