// @flow

// THIS FILE IS AUTOGENERATED FROM components/metadata/src/metadata_updater/interface.proto
// PLEASE DONT EDIT MANUALLY

export interface IUpdateRequest {
  userId: string;  // id = 1
  eventId: string;  // id = 2
  author: string;  // id = 3
  timestamp: number;  // id = 4
  dataExtent: ITimeRange;  // id = 5
}
export interface ITimeRange {
  from: number;  // id = 1
  to: number;  // id = 2
}
export interface IUpdateResponse {
  deadline: number;  // id = 1
}
export interface IUpdateId {
  userId: string;  // id = 1
  eventId: string;  // id = 2
}
export interface IPendingUpdate {
  found: boolean;  // id = 1
  deadline: number;  // id = 2
}
export interface IMetadataUpdaterService {
  scheduleUpdate(req: IUpdateRequest): Promise<IUpdateResponse>;
  getPendingUpdate(req: IUpdateId): Promise<IPendingUpdate>;
}
