# previous version made to publish on Azure should be adapted to publish on dockerHub
name: Service core publish release

on:
  push:
    tags:
      - '*'
jobs:
  build:

    # IMPORTANT: Ubuntu version must match our Docker base image's (see release-packaging repo)
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        # IMPORTANT: Node.js version must match our Docker base image's (see release-packaging repo)
        node-version: [18.16.0]

    steps:
    - name: Install `just`
      uses: extractions/setup-just@v2

    - name: Download master branch
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Login to github
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.TECH_PRYV_SSH_KEY }}

    - name: Login to the docker containers registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
        username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
        password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

    - name: Build and deploy
      run: ./build/build
