---
logs:
  console:
    active: true
    level: info
    colorize: true
database:
  host: 127.0.0.1
  port: 27017
  name: pryv-node
postgresql:
  host: '127.0.0.1'
  port: 5432
  database: 'pryv-node'
  user: 'pryv'
  password: ''
  max: 20
tcpBroker:
  port: 4222

integrity:
  isActive:
    attachments: true
    events: true
    accesses: true
  algorithm: sha256

