#!/bin/bash
set -e

# working dir fix
SERVICE_CORE_FOLDER=$(cd $(dirname "$0"); cd .. ; pwd)
cd $SERVICE_CORE_FOLDER/

DEV_MODULES_FOLDER=$SERVICE_CORE_FOLDER/dev-modules
mkdir -p $DEV_MODULES_FOLDER

cd $DEV_MODULES_FOLDER

DATASTORE_MODULE_FOLDER=$DEV_MODULES_FOLDER/pryv-datastore

if [[ ! -d $DATASTORE_MODULE_FOLDER ]]; then
  echo "...creating dev directory for @pryv/datastore"
  echo ""

  git clone git@github.com:pryv/pryv-datastore.git
  cd $SERVICE_CORE_FOLDER
  rm -rf node_modules/@pryv/datastore
  ln -s $DATASTORE_MODULE_FOLDER node_modules/@pryv/datastore
else
  echo "dev directory for @pryv/datastore already installed"
fi