#!/bin/bash

# Sets up the dev environment on a MacOS or GNU/Linux system

set -e

# working dir fix
SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/.. # root

# setup git pre-commit hook if appropriate
PRE_COMMIT="scripts/pre-commit"
if [[ -d .git ]]; then
  cp $PRE_COMMIT .git/hooks/
  echo ""
  echo "Git pre-commit hook setup from '$PRE_COMMIT'"
  echo ""
fi

## used in Open Pryv
SCRIPT_EXTRAS="./scripts/setup-open.bash"
if [[ -f $SCRIPT_EXTRAS ]]; then
  echo "installing service mail"
  bash $SCRIPT_EXTRAS
fi

echo ""
echo "Setup complete!"
echo ""

export DATA_FOLDER=$SCRIPT_FOLDER/../var-pryv
export LOGS_FOLDER=${DATA_FOLDER}/logs
export ATTACHMENTS_FOLDER=${DATA_FOLDER}/attachment-files

export MONGO_BASE_FOLDER=$DATA_FOLDER

# file structure

mkdir -p $DATA_FOLDER
mkdir -p $LOGS_FOLDER
mkdir -p $ATTACHMENTS_FOLDER

# database

. scripts/setup-mongodb
EXIT_CODE=$?
if [[ ${EXIT_CODE} -ne 0 ]]; then
  echo ""
  echo "Error setting up database; setup aborted"
  echo ""
  exit ${EXIT_CODE}
fi
