#!/bin/bash
set -e

# Sets up MongoDB (engine and data) for server app(s)
# Meant to be run from dev env setup scripts

# Check OS and prepare download URL
# https://www.mongodb.com/try/download/community
if [ `uname` = "Linux" ]; then
  MONGO_NAME=mongodb-linux-x86_64-ubuntu1804-v4.2-latest
  MONGO_DL_BASE_URL=https://fastdl.mongodb.org/linux
elif [ `uname` = "Darwin" ]; then # MacOS
  MONGO_NAME=mongodb-macos-x86_64-4.2.8
  MONGO_DL_BASE_URL=https://fastdl.mongodb.org/osx
else
  echo "Installation is meant to be on Linux or MacOS"
  exit 1
fi

# working dir fix
SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/

# Check & create file structure

MONGO_FOLDER_NAME=mongodb-bin

if [[ -z "$VAR_PRYV_FOLDER" ]]; then
  echo ""
  echo "Error: Missing environment variable VAR_PRYV_FOLDER (root installation folder)"
  echo "(MongoDB will be installed (if needed) in 'VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME')"
  echo ""
  exit 1
fi

mkdir -p $VAR_PRYV_FOLDER

MONGO_DATA_FOLDER=$VAR_PRYV_FOLDER/mongodb-data
mkdir -p $MONGO_DATA_FOLDER

MONGO_LOGS_FOLDER=$VAR_PRYV_FOLDER/mongodb-logs
mkdir -p $MONGO_LOGS_FOLDER

echo ""
echo "Checking for MongoDB ($VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME)..."
if [[ ! -d $VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME ]]; then
  echo "...installing $MONGO_NAME"
  echo ""

  curl -C - -o "$VAR_PRYV_FOLDER/$MONGO_NAME.tgz" $MONGO_DL_BASE_URL/$MONGO_NAME.tgz

  cd $VAR_PRYV_FOLDER
  # extract into standardized mongo folder name to be OS-independant
  mkdir $MONGO_FOLDER_NAME
  tar -xzf $MONGO_NAME.tgz -C $MONGO_FOLDER_NAME --strip-components 1
  rm $MONGO_NAME.tgz
else
  echo "...already installed"
fi

echo ""
echo "Database setup complete."
echo ""
echo "To run MongoDB:"
echo "    ./scripts/start-mongo"
echo ""
