#!/bin/bash

# Adding private libraries

# working dir fix
SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/..

PRIVATE_LIBS_DIR="private-libs"
if [[ ! -d $PRIVATE_LIBS_DIR ]]; then
  mkdir -p $PRIVATE_LIBS_DIR
  cd $PRIVATE_LIBS_DIR
  git clone git@github.com:pryv/lib-reporting.git
fi