#!/usr/bin/env bash

set -e

command -v ronn >/dev/null 2>&1 || {
  echo "Cannot find 'ronn' command. Install using 'gem install ronn'."
}

set default_opts="--organization='Pryv SA' --manual='pryv-cli' --style='dark'"

ronn $default_opts ../README.md 

mv ../*.1 .
mv ../*.html .
