// flow-typed signature: f81e9f3da27ce11b6b23a61cbd45b276
// flow-typed version: <<STUB>>/@pryv/boiler_vhttps://github.com/pryv/pryv-boiler.git#1.0.5/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pryv/boiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pryv/boiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pryv/boiler/examples/configs/extra-config' {
  declare module.exports: any;
}

declare module '@pryv/boiler/examples/configs/extra-js-async' {
  declare module.exports: any;
}

declare module '@pryv/boiler/examples/doubleinit' {
  declare module.exports: any;
}

declare module '@pryv/boiler/examples' {
  declare module.exports: any;
}

declare module '@pryv/boiler/examples/plugins/plugin-async' {
  declare module.exports: any;
}

declare module '@pryv/boiler/examples/plugins/plugin-sync' {
  declare module.exports: any;
}

declare module '@pryv/boiler/src/airbrake' {
  declare module.exports: any;
}

declare module '@pryv/boiler/src/compute-learn' {
  declare module.exports: any;
}

declare module '@pryv/boiler/src/config' {
  declare module.exports: any;
}

declare module '@pryv/boiler/src' {
  declare module.exports: any;
}

declare module '@pryv/boiler/src/lib/nconf-yaml' {
  declare module.exports: any;
}

declare module '@pryv/boiler/src/logging' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pryv/boiler/examples/configs/extra-config.js' {
  declare module.exports: $Exports<'@pryv/boiler/examples/configs/extra-config'>;
}
declare module '@pryv/boiler/examples/configs/extra-js-async.js' {
  declare module.exports: $Exports<'@pryv/boiler/examples/configs/extra-js-async'>;
}
declare module '@pryv/boiler/examples/doubleinit.js' {
  declare module.exports: $Exports<'@pryv/boiler/examples/doubleinit'>;
}
declare module '@pryv/boiler/examples/index' {
  declare module.exports: $Exports<'@pryv/boiler/examples'>;
}
declare module '@pryv/boiler/examples/index.js' {
  declare module.exports: $Exports<'@pryv/boiler/examples'>;
}
declare module '@pryv/boiler/examples/plugins/plugin-async.js' {
  declare module.exports: $Exports<'@pryv/boiler/examples/plugins/plugin-async'>;
}
declare module '@pryv/boiler/examples/plugins/plugin-sync.js' {
  declare module.exports: $Exports<'@pryv/boiler/examples/plugins/plugin-sync'>;
}
declare module '@pryv/boiler/src/airbrake.js' {
  declare module.exports: $Exports<'@pryv/boiler/src/airbrake'>;
}
declare module '@pryv/boiler/src/compute-learn.js' {
  declare module.exports: $Exports<'@pryv/boiler/src/compute-learn'>;
}
declare module '@pryv/boiler/src/config.js' {
  declare module.exports: $Exports<'@pryv/boiler/src/config'>;
}
declare module '@pryv/boiler/src/index' {
  declare module.exports: $Exports<'@pryv/boiler/src'>;
}
declare module '@pryv/boiler/src/index.js' {
  declare module.exports: $Exports<'@pryv/boiler/src'>;
}
declare module '@pryv/boiler/src/lib/nconf-yaml.js' {
  declare module.exports: $Exports<'@pryv/boiler/src/lib/nconf-yaml'>;
}
declare module '@pryv/boiler/src/logging.js' {
  declare module.exports: $Exports<'@pryv/boiler/src/logging'>;
}
