// flow-typed signature: 27afa47a0915c15a1a38f6f5dd221972
// flow-typed version: <<STUB>>/@pryv/stable-object-representation_v^1.1.4/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pryv/stable-object-representation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pryv/stable-object-representation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pryv/stable-object-representation/src/access' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/src/event' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/src' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/src/lib/hash' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/src/lib' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/src/lib/stable-stringify' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/src/utils/config' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/src/utils/logger' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/test/default' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/test/unit/access.test' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/test/unit/event.test' {
  declare module.exports: any;
}

declare module '@pryv/stable-object-representation/test/unit/stringy.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pryv/stable-object-representation/src/access.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src/access'>;
}
declare module '@pryv/stable-object-representation/src/event.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src/event'>;
}
declare module '@pryv/stable-object-representation/src/index' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src'>;
}
declare module '@pryv/stable-object-representation/src/index.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src'>;
}
declare module '@pryv/stable-object-representation/src/lib/hash.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src/lib/hash'>;
}
declare module '@pryv/stable-object-representation/src/lib/index' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src/lib'>;
}
declare module '@pryv/stable-object-representation/src/lib/index.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src/lib'>;
}
declare module '@pryv/stable-object-representation/src/lib/stable-stringify.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src/lib/stable-stringify'>;
}
declare module '@pryv/stable-object-representation/src/utils/config.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src/utils/config'>;
}
declare module '@pryv/stable-object-representation/src/utils/logger.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/src/utils/logger'>;
}
declare module '@pryv/stable-object-representation/test/default.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/test/default'>;
}
declare module '@pryv/stable-object-representation/test/unit/access.test.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/test/unit/access.test'>;
}
declare module '@pryv/stable-object-representation/test/unit/event.test.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/test/unit/event.test'>;
}
declare module '@pryv/stable-object-representation/test/unit/stringy.test.js' {
  declare module.exports: $Exports<'@pryv/stable-object-representation/test/unit/stringy.test'>;
}
